### ISSUE TITLE
Fsck & mount failing with  s3ql.backends.s3c.S3Error: EntityTooLarge: Your proposed upload exceeds the maximum allowed size

### ISSUE THREAD

**Issue by rgammans** [s3ql/s3ql#101]
This is on 2.33 as I was running 2.30 when I got a crash with this error; and didn't want to upgrade without a succesful fsck.

```
$ /my/pythonpath/bin/fsck.s3ql $S3QLFS_OPTS $S3_BUCKET  --force
Starting fsck of s3://eu-west-1/my-bucket/a-path/
Using cached metadata.
WARNING: Remote metadata is outdated.
Checking DB integrity...
Creating temporary extra indices...
Checking lost+found...
Checking for dirty cache objects...
Checking names (refcounts)...
Checking contents (names)...
Checking contents (inodes)...
Checking contents (parent inodes)...
Checking objects (reference counts)...
Checking objects (backend)...
..processed 2898000 objects so far..
Checking objects (sizes)...
Checking blocks (referenced objects)...
Checking blocks (refcounts)...
Checking blocks (checksums)...
Checking inode-block mapping (blocks)...
Checking inode-block mapping (inodes)...
Checking inodes (refcounts)...
Checking inodes (sizes)...
Checking extended attributes (names)...
Checking extended attributes (inodes)...
Checking symlinks (inodes)...
Checking directory reachability...
Checking unix conventions...
Checking referential integrity...
Dropping temporary indices...
Dumping metadata...
..objects..
..blocks..
..inodes..
..inode_blocks..
..symlink_targets..
..names..
..contents..
..ext_attributes..
Compressing and uploading metadata...
ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/my/pythonpath/bin/fsck.s3ql", line 11, in <module>
    load_entry_point('s3ql==2.33', 'console_scripts', 'fsck.s3ql')()
  File "/my/pythonpath/lib/python3.6/site-packages/s3ql-2.33-py3.6-linux-x86_64.egg/s3ql/fsck.py", line 1290, in main
    dump_and_upload_metadata(backend, db, param)
  File "/my/pythonpath/lib/python3.6/site-packages/s3ql-2.33-py3.6-linux-x86_64.egg/s3ql/metadata.py", line 313, in dump_and_upload_metadata
    upload_metadata(backend, fh, param)
  File "/my/pythonpath/lib/python3.6/site-packages/s3ql-2.33-py3.6-linux-x86_64.egg/s3ql/metadata.py", line 322, in upload_metadata
    metadata=param, is_compressed=True)
  File "/my/pythonpath/lib/python3.6/site-packages/s3ql-2.33-py3.6-linux-x86_64.egg/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/my/pythonpath/lib/python3.6/site-packages/s3ql-2.33-py3.6-linux-x86_64.egg/s3ql/backends/common.py", line 347, in perform_write
    return fn(fh)
  File "/my/pythonpath/lib/python3.6/site-packages/s3ql-2.33-py3.6-linux-x86_64.egg/s3ql/backends/comprenc.py", line 541, in __exit__
    self.close()
  File "/my/pythonpath/lib/python3.6/site-packages/s3ql-2.33-py3.6-linux-x86_64.egg/s3ql/backends/comprenc.py", line 535, in close
    self.fh.close()
  File "/my/pythonpath/lib/python3.6/site-packages/s3ql-2.33-py3.6-linux-x86_64.egg/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/my/pythonpath/lib/python3.6/site-packages/s3ql-2.33-py3.6-linux-x86_64.egg/s3ql/backends/s3c.py", line 940, in close
    headers=self.headers, body=self.fh)
  File "/my/pythonpath/lib/python3.6/site-packages/s3ql-2.33-py3.6-linux-x86_64.egg/s3ql/backends/s3c.py", line 549, in _do_request
    self._parse_error_response(resp)
  File "/my/pythonpath/lib/python3.6/site-packages/s3ql-2.33-py3.6-linux-x86_64.egg/s3ql/backends/s3c.py", line 583, in _parse_error_response
    raise get_S3Error(tree.findtext('Code'), tree.findtext('Message'), resp.headers)
s3ql.backends.s3c.S3Error: EntityTooLarge: Your proposed upload exceeds the maximum allowed size
```

**Comment by Nikratio** [comment]
Thanks for the report! I think you're hitting issue #53 here.

**Comment by rgammans** [comment]
So is there no way I can mount this filesystem? Have I lost all the 200+ TB of data on it ?

**Comment by Nikratio** [comment]
Not at all, mounting should work perfectly but mount.s3ql refuses to do this because you wouldn't be able to upload anymore.

Please:

- Make a backup of your metadata (~/.s3ql by default)
- Apply the patch below (to enable mounting despite the unclean unmount)
- Delete some directory entries to get the metadata limit below 5 GB (it's the number of directory entries that counts, not the amount of file data). Note that `s3qlstat` will not immediately show size changes, so you may have to experiment a little and re-mount several times.
- Once this has worked, revert the patch 
- Then think about submitting a pull request for issue #53, or consider if there is a way to split your data among several filesystems 

```
diff --git a/src/s3ql/mount.py b/src/s3ql/mount.py
index b769339..f341a48 100644
--- a/src/s3ql/mount.py
+++ b/src/s3ql/mount.py
@@ -372,8 +372,9 @@ def get_metadata(backend, cachepath):
             log.info('Ignoring locally cached metadata (outdated).')
             param = backend.lookup(meta_obj_name)
         elif param['seq_no'] > seq_no:
-            raise QuietError("File system not unmounted cleanly, run fsck!",
-                             exitcode=30)
+            #raise QuietError("File system not unmounted cleanly, run fsck!",
+            #                 exitcode=30)
+            log.warning('Filesystem not unmounted cleanly, mounting anyway')
         else:
             log.info('Using cached metadata.')
             db = Connection(cachepath + '.db')
```

**Comment by rgammans** [comment]
Thanks. I srill  can't mount:
```
# $S3MOUNT $S3QLFS_OPTS $S3QL_MOUNT_OPTS $S3_BUCKET $S3QL_MOUNT
Using 10 upload threads.
Autodetected 65474 file descriptors available for cache entries
Using cached metadata.
ERROR: File system damaged or not unmounted cleanly, run fsck!

```

Looking at the code this seme to be the needs_fsck flag wasn't reset be fsck before the failed metadata upload. Is it safe to make the same change to this error as the other?

**Comment by Nikratio** [comment]
Yeah, a similar change should be fine
