### ISSUE TITLE
benchmark.py  ERROR: Uncaught top-level exception:

### ISSUE THREAD

**Issue by letran3691** [s3ql/s3ql#103]
hello  team!!!
I run benchmark.py  './benchmark.py --authfile /xxx/xxxx.authen --backend-options 'no-ssl'  s3c://s3.xxxxxx:80/xxxxxxx.storage 1.rar', and file '1.rar' about 1G. I run on centos7.
I don't know where is problem. Please help me
Sorry because my english not good

return 'ERROR: Uncaught top-level exception:'
detail:
Measuring throughput to cache...
Cache throughput with   4 KiB blocks: 11904 KiB/sec
Cache throughput with   8 KiB blocks: 6958 KiB/sec
Cache throughput with  16 KiB blocks: 7365 KiB/sec
Cache throughput with  32 KiB blocks: 7378 KiB/sec
Cache throughput with  64 KiB blocks: 7227 KiB/sec
Cache throughput with 128 KiB blocks: 7525 KiB/sec
Measuring raw backend throughput..
ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "./benchmark.py", line 244, in <module>
    main(sys.argv[1:])
  File "./benchmark.py", line 168, in main
    (upload_size, upload_time) = backend.perform_write(do_write, 's3ql_testdata')
  File "/root/s3ql-3.1/src/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/root/s3ql-3.1/src/s3ql/backends/common.py", line 279, in perform_write
    return fn(fh)
  File "/root/s3ql-3.1/src/s3ql/backends/s3c.py", line 929, in __exit__
    self.close()
  File "/root/s3ql-3.1/src/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/root/s3ql-3.1/src/s3ql/backends/s3c.py", line 910, in close
    headers=self.headers, body=self.fh)
  File "/root/s3ql-3.1/src/s3ql/backends/s3c.py", line 528, in _do_request
    self._parse_error_response(resp)
  File "/root/s3ql-3.1/src/s3ql/backends/s3c.py", line 562, in _parse_error_response
    raise get_S3Error(tree.findtext('Code'), tree.findtext('Message'), resp.headers)
s3ql.backends.s3c.S3Error: ObjectUnderRetention: The object is under retention and can't be deleted or modified.

**Comment by Nikratio** [comment]
Thanks for the report! My best guess is that your storage provider is configured to not allow removal of objects. S3QL is just showing you the error that it got from the server.
