### ISSUE TITLE
ConstraintError: UNIQUE constraint failed: obj_ids.id

### ISSUE THREAD

**Issue by eleaner** [s3ql/s3ql#109]
Version S3QL 3.1
stored on local

My filesystem run out of space while writing to S3QL.
Now during fsck I am getting this error

```
Starting fsck of local:///mnt/.s3qldata/
Using cached metadata.
WARNING: Remote metadata is outdated.
Checking DB integrity...
Creating temporary extra indices...
Checking lost+found...
Checking for dirty cache objects...
Checking names (refcounts)...
Checking contents (names)...
Checking contents (inodes)...
Checking contents (parent inodes)...
Checking for temporary objects (backend)...
Checking objects (reference counts)...
Checking objects (backend)...
..processed 692625 objects so far..
Dropping temporary indices...
ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/local/bin/fsck.s3ql", line 11, in <module>
    load_entry_point('s3ql==3.1', 'console_scripts', 'fsck.s3ql')()
  File "/usr/local/lib/python3.5/dist-packages/s3ql-3.1-py3.5-linux-x86_64.egg/s3ql/fsck.py", line 1273, in main
    fsck.check(check_cache)
  File "/usr/local/lib/python3.5/dist-packages/s3ql-3.1-py3.5-linux-x86_64.egg/s3ql/fsck.py", line 92, in check
    self.check_objects_id()
  File "/usr/local/lib/python3.5/dist-packages/s3ql-3.1-py3.5-linux-x86_64.egg/s3ql/fsck.py", line 965, in check_objects_id
    self.conn.execute('INSERT INTO obj_ids VALUES(?)', (obj_id,))
  File "/usr/local/lib/python3.5/dist-packages/s3ql-3.1-py3.5-linux-x86_64.egg/s3ql/database.py", line 98, in execute
    self.conn.cursor().execute(*a, **kw)
  File "src/cursor.c", line 236, in resetcursor
apsw.ConstraintError: ConstraintError: UNIQUE constraint failed: obj_ids.id
```

I cleaned up cache but it did not help
any chance to get it running?

**Comment by eleaner** [comment]
raised in google groups
