### ISSUE TITLE
dugong.StateError when error running fsck

### ISSUE THREAD

**Issue by bortnik84** [s3ql/s3ql#115]
run fsck 
I get the following error

 968:MainThread s3ql.fsck.main: Starting fsck 
2019-07-25 19:25:37.977 968:MainThread s3ql.fsck.main: Using cached metadata.
2019-07-25 19:25:38.082 968:MainThread s3ql.fsck.main: Checking DB integrity...
2019-07-25 19:25:45.211 968:MainThread s3ql.fsck.check: Creating temporary extra indices...
2019-07-25 19:25:46.650 968:MainThread s3ql.fsck.check_lof: Checking lost+found...
2019-07-25 19:25:46.650 968:MainThread s3ql.fsck.check_cache: Checking cached objects...
2019-07-25 19:25:46.650 968:MainThread s3ql.fsck.check_names_refcount: Checking names (refcounts)...
2019-07-25 19:25:49.539 968:MainThread s3ql.fsck.check_contents_name: Checking contents (names)...
2019-07-25 19:25:49.919 968:MainThread s3ql.fsck.check_contents_inode: Checking contents (inodes)...
2019-07-25 19:25:50.240 968:MainThread s3ql.fsck.check_contents_parent_inode: Checking contents (parent inodes)...
2019-07-25 19:25:50.327 968:MainThread s3ql.fsck.check_objects_refcount: Checking objects (reference counts)...
2019-07-25 19:25:51.266 968:MainThread s3ql.fsck.check_objects_id: Checking objects (backend)...
2019-07-25 19:30:37.270 968:MainThread s3ql.fsck.check: Dropping temporary indices...
2019-07-25 19:30:37.366 968:MainThread root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/bin/fsck.s3ql", line 11, in <module>
    load_entry_point('s3ql==2.21', 'console_scripts', 'fsck.s3ql')()
  File "/usr/lib/s3ql/s3ql/fsck.py", line 1266, in main
    fsck.check()
  File "/usr/lib/s3ql/s3ql/fsck.py", line 87, in check
    self.check_objects_id()
  File "/usr/lib/s3ql/s3ql/fsck.py", line 898, in check_objects_id
    for (i, obj_name) in enumerate(self.backend.list('s3ql_data_')):
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 217, in __next__
    el = next(self.iterator)
  File "/usr/lib/s3ql/s3ql/backends/swift.py", line 481, in list
    'limit': batch_size })
  File "/usr/lib/s3ql/s3ql/backends/swift.py", line 232, in _do_request
    resp = self._do_request_inner(method, path, body=body, headers=headers)
  File "/usr/lib/s3ql/s3ql/backends/swift.py", line 270, in _do_request_inner
    return self.conn.read_response()
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 765, in read_response
    return eval_coroutine(self.co_read_response(), self.timeout)
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 1496, in eval_coroutine
    if not next(crt).poll(timeout=timeout):
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 781, in co_read_response
    raise StateError('Previous response not read completely')
dugong.StateError: Previous response not read completely

**Comment by Nikratio** [comment]
Thanks for the report! This error should disappear when you re-run fsck.s3ql.

I have a long-term plan to move from dugong to a h11, which should fix this problem. Tracking this down in dugong would be too much for work too little gain, I think.
