### ISSUE TITLE
fsck.s3ql crashes on uninitialized file system

### ISSUE THREAD

**Issue by ravenpride** [s3ql/s3ql#133]
Hello,

first of all - thank you for this great file system! I'm currently trying to put it together with Nextcloud in a docker container. The container should create the file system the first time it is run and then mount it. I'm trying to use `fsck.s3ql` to check whether the file system is already initialized. According to the documentation I would expect to get exit code 18 back from `fsck.s3ql`, but `fsck.s3ql` crashes with the following:

```
ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/s3ql-3.3.2-py3.7-linux-x86_64.egg/s3ql/backends/s3c.py", line 320, in open_read
    resp = self._do_request('GET', '/%s%s' % (self.prefix, key))
  File "/usr/lib/python3.7/site-packages/s3ql-3.3.2-py3.7-linux-x86_64.egg/s3ql/backends/s3c.py", line 528, in _do_request
    self._parse_error_response(resp)
  File "/usr/lib/python3.7/site-packages/s3ql-3.3.2-py3.7-linux-x86_64.egg/s3ql/backends/s3c.py", line 562, in _parse_error_response
    raise get_S3Error(tree.findtext('Code'), tree.findtext('Message'), resp.headers)
s3ql.backends.s3c.NoSuchKeyError: NoSuchKey: The specified key does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/fsck.s3ql", line 11, in <module>
    load_entry_point('s3ql==3.3.2', 'console_scripts', 'fsck.s3ql')()
  File "/usr/lib/python3.7/site-packages/s3ql-3.3.2-py3.7-linux-x86_64.egg/s3ql/fsck.py", line 1141, in main
    backend = get_backend(options)
  File "/usr/lib/python3.7/site-packages/s3ql-3.3.2-py3.7-linux-x86_64.egg/s3ql/common.py", line 248, in get_backend
    return get_backend_factory(options)()
  File "/usr/lib/python3.7/site-packages/s3ql-3.3.2-py3.7-linux-x86_64.egg/s3ql/common.py", line 323, in get_backend_factory
    tmp_backend.fetch('s3ql_metadata')
  File "/usr/lib/python3.7/site-packages/s3ql-3.3.2-py3.7-linux-x86_64.egg/s3ql/backends/common.py", line 293, in fetch
    return self.perform_read(do_read, key)
  File "/usr/lib/python3.7/site-packages/s3ql-3.3.2-py3.7-linux-x86_64.egg/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/lib/python3.7/site-packages/s3ql-3.3.2-py3.7-linux-x86_64.egg/s3ql/backends/common.py", line 256, in perform_read
    fh = self.open_read(key)
  File "/usr/lib/python3.7/site-packages/s3ql-3.3.2-py3.7-linux-x86_64.egg/s3ql/backends/comprenc.py", line 194, in open_read
    fh = self.backend.open_read(key)
  File "/usr/lib/python3.7/site-packages/s3ql-3.3.2-py3.7-linux-x86_64.egg/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/lib/python3.7/site-packages/s3ql-3.3.2-py3.7-linux-x86_64.egg/s3ql/backends/s3c.py", line 322, in open_read
    raise NoSuchObject(key)
s3ql.backends.common.NoSuchObject: Backend does not have anything stored under key 's3ql_metadata'
```

**Comment by tkrill** [comment]
Similar use case here, We ran into problems when upgrading our system to Debian Buster (S3QL v ~3.0) Previously working in S3QL 2.21  where fsck terminates with an " ERROR: No S3QL file system found at given storage URL." and exit code 18.

**Comment by tkrill** [comment]
Ok, i ran a git bisect. Turns out the bug seems to be introduced in:

```
 commit c05770b9515169581f336a985b640678972d95a2
Author: Nikolaus Rath <Nikolaus@rath.org>
Date:   Thu Jun 14 11:24:43 2018 +0100

    Fix upgrade of unencrypted filesystems

    Since we use checksum_basic_mapping() in the unencrypted storage backends
    as well, we need to rewrite metadata for unencrypted file systems as well.
```
Attached patch **seems** to fix it for me.
[missing_filesystem.patch.gz](https://github.com/s3ql/s3ql/files/4185057/missing_filesystem.patch.gz)

**Comment by Nikratio** [comment]
Pull request was merged, thanks!
