### ISSUE TITLE
s3qladm upgrade  v 3.3.2

### ISSUE THREAD

**Issue by bortnikov84** [s3ql/s3ql#154]
Good afternoon! I'm trying to upgrade the file system to version 3.3.2 with the following command
```
s3qladm --authfile /etc/s3ql/s3ql.auth --backend-options tcp-timeout = 200 upgrade swiftks: //auth.cloud.ovh.net/***: ***"
```

and after a while the hollow next error:
```
" s3qladm  --authfile /etc/s3ql/s3ql.auth --backend-options tcp-timeout=200 upgrade swiftks://auth.cloud.ovh.net/***:***
Getting file system parameters..
Detected Swift features for storage.gra.cloud.ovh.net:443: copy via COPY, Bulk delete 1000 keys at a time, maximum meta value length is 255 bytes

I am about to update the file system to the newest revision.
You will not be able to access the file system with any older version
of S3QL after this operation.

You should make very sure that this command is not interrupted and
that no one else tries to mount, fsck or upgrade the file system at
the same time. You may interrupt the update with Ctrl+C and resume
at a later time, but the filesystem will not be in a usable state
until the upgrade is complete.

Please enter "yes" to continue.
> yes
Downloading and decompressing metadata...
Reading metadata...
..objects..
..blocks..
..inodes..
..inode_blocks..
..symlink_targets..
..names..
..contents..
..ext_attributes..
Upgrading from revision 23 to 24...
..processed 500452/1198310 objects (41%)..ERROR: Thread Thread-16 terminated with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/s3ql-3.3.2-py3.5-linux-x86_64.egg/s3ql/common.py", line 373, in run
    self.run_protected()
  File "/usr/local/lib/python3.5/dist-packages/s3ql-3.3.2-py3.5-linux-x86_64.egg/s3ql/common.py", line 425, in run_protected
    self.target(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/s3ql-3.3.2-py3.5-linux-x86_64.egg/s3ql/adm.py", line 494, in upgrade_loop
    backend.update_meta(key, meta)
  File "/usr/local/lib/python3.5/dist-packages/s3ql-3.3.2-py3.5-linux-x86_64.egg/s3ql/backends/comprenc.py", line 304, in update_meta
    metadata=metadata)
  File "/usr/local/lib/python3.5/dist-packages/s3ql-3.3.2-py3.5-linux-x86_64.egg/s3ql/backends/comprenc.py", line 339, in _copy_or_rename
    self.backend.update_meta(src, meta_raw)
  File "/usr/local/lib/python3.5/dist-packages/s3ql-3.3.2-py3.5-linux-x86_64.egg/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/local/lib/python3.5/dist-packages/s3ql-3.3.2-py3.5-linux-x86_64.egg/s3ql/backends/swift.py", line 669, in update_meta
    self._do_request('POST', '/%s%s' % (self.prefix, key), headers=headers)
  File "/usr/local/lib/python3.5/dist-packages/s3ql-3.3.2-py3.5-linux-x86_64.egg/s3ql/backends/swift.py", line 267, in _do_request
    raise HTTPError(resp.status, resp.reason, resp.headers)
s3ql.backends.s3c.HTTPError: 404 Not Found
..processed 500486/1198310 objects (41%)..ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/local/bin/s3qladm", line 11, in <module>
    load_entry_point('s3ql==3.3.2', 'console_scripts', 's3qladm')()
  File "/usr/local/lib/python3.5/dist-packages/s3ql-3.3.2-py3.5-linux-x86_64.egg/s3ql/adm.py", line 98, in main
    return upgrade(options)
  File "/usr/local/lib/python3.5/dist-packages/s3ql-3.3.2-py3.5-linux-x86_64.egg/s3ql/common.py", line 441, in wrapper
    return fn(*a, **kw)
  File "/usr/local/lib/python3.5/dist-packages/s3ql-3.3.2-py3.5-linux-x86_64.egg/s3ql/adm.py", line 399, in upgrade
    update_obj_metadata(backend, backend_factory, db, options)
  File "/usr/local/lib/python3.5/dist-packages/s3ql-3.3.2-py3.5-linux-x86_64.egg/s3ql/adm.py", line 450, in update_obj_metadata
    t.join_and_raise()
  File "/usr/local/lib/python3.5/dist-packages/s3ql-3.3.2-py3.5-linux-x86_64.egg/s3ql/common.py", line 395, in join_and_raise
    raise EmbeddedException(exc_info, self.name)
s3ql.common.EmbeddedException: caused by an exception in thread Thread-16.
Original/inner traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/s3ql-3.3.2-py3.5-linux-x86_64.egg/s3ql/common.py", line 373, in run
    self.run_protected()
  File "/usr/local/lib/python3.5/dist-packages/s3ql-3.3.2-py3.5-linux-x86_64.egg/s3ql/common.py", line 425, in run_protected
    self.target(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/s3ql-3.3.2-py3.5-linux-x86_64.egg/s3ql/adm.py", line 494, in upgrade_loop
    backend.update_meta(key, meta)
  File "/usr/local/lib/python3.5/dist-packages/s3ql-3.3.2-py3.5-linux-x86_64.egg/s3ql/backends/comprenc.py", line 304, in update_meta
    metadata=metadata)
  File "/usr/local/lib/python3.5/dist-packages/s3ql-3.3.2-py3.5-linux-x86_64.egg/s3ql/backends/comprenc.py", line 339, in _copy_or_rename
    self.backend.update_meta(src, meta_raw)
  File "/usr/local/lib/python3.5/dist-packages/s3ql-3.3.2-py3.5-linux-x86_64.egg/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/local/lib/python3.5/dist-packages/s3ql-3.3.2-py3.5-linux-x86_64.egg/s3ql/backends/swift.py", line 669, in update_meta
    self._do_request('POST', '/%s%s' % (self.prefix, key), headers=headers)
  File "/usr/local/lib/python3.5/dist-packages/s3ql-3.3.2-py3.5-linux-x86_64.egg/s3ql/backends/swift.py", line 267, in _do_request
    raise HTTPError(resp.status, resp.reason, resp.headers)
s3ql.backends.s3c.HTTPError: 404 Not Found
```
"

after re-loading, the process starts from the beginning but already goes a little further, and again falls.

**Comment by Nikratio** [comment]
Your storage service returns 404 errors when S3QL attempts to download data that it has previously uploaded. There is not much S3QL can do here...
