### ISSUE TITLE
NoneType can't be used in 'await' expression

### ISSUE THREAD

**Issue by wonderpug** [s3ql/s3ql#159]
Since upgrading to 3.4, I get this daily:

2020-03-28 22:00:05.561 6608:MainThread s3ql.mount.unmount: Unmounting file system...
2020-03-28 22:00:05.562 6608:MainThread root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/local/bin/mount.s3ql", line 11, in <module>
    load_entry_point('s3ql==3.4.0', 'console_scripts', 'mount.s3ql')()
  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.4.0-py3.6-linux-x86_64.egg/s3ql/mount.py", line 131, in main
    trio.run(main_async, options, stdout_log_handler)
  File "/usr/local/lib/python3.6/dist-packages/trio/_core/_run.py", line 1804, in run
    raise runner.main_task_outcome.error
  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.4.0-py3.6-linux-x86_64.egg/s3ql/mount.py", line 255, in main_async
    ret = await pyfuse3.main()
  File "/usr/local/lib/python3.6/dist-packages/pyfuse3-1.3.1-py3.6-linux-x86_64.egg/_pyfuse3.py", line 30, in wrapper
    await fn(*args, **kwargs)
  File "src/pyfuse3.pyx", line 727, in main
  File "/usr/local/lib/python3.6/dist-packages/trio/_core/_run.py", line 730, in __aexit__
    raise combined_error_from_nursery
  File "/usr/local/lib/python3.6/dist-packages/pyfuse3-1.3.1-py3.6-linux-x86_64.egg/_pyfuse3.py", line 30, in wrapper
    await fn(*args, **kwargs)
  File "src/internal.pxi", line 253, in _session_loop
  File "src/handlers.pxi", line 530, in fuse_fsync_async
  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.4.0-py3.6-linux-x86_64.egg/s3ql/fs.py", line 1125, in fsync
    await self.cache.flush_local(fh, blockno)
TypeError: object NoneType can't be used in 'await' expression

**Comment by Nikratio** [comment]
Thanks for the report! Should be fixed now with the commit below.

**Comment by d--j** [comment]
after applying 3ac82f3 I get this traceback:

```
2020-04-05 18:27:27.173 51799:MainThread root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/bin/mount.s3ql", line 8, in <module>
    sys.exit(main())
  File "/opt/s3ql/s3ql/lib/python3.7/site-packages/s3ql/mount.py", line 131, in main
    trio.run(main_async, options, stdout_log_handler)
  File "/opt/s3ql/s3ql/lib/python3.7/site-packages/trio/_core/_run.py", line 1783, in run
    raise runner.main_task_outcome.error
  File "/opt/s3ql/s3ql/lib/python3.7/site-packages/s3ql/mount.py", line 256, in main_async
    ret = await pyfuse3.main()
  File "/opt/s3ql/s3ql/lib/python3.7/site-packages/_pyfuse3.py", line 30, in wrapper
    await fn(*args, **kwargs)
  File "src/pyfuse3.pyx", line 727, in main
  File "/opt/s3ql/s3ql/lib/python3.7/site-packages/trio/_core/_run.py", line 725, in __aexit__
    raise combined_error_from_nursery
  File "/opt/s3ql/s3ql/lib/python3.7/site-packages/_pyfuse3.py", line 30, in wrapper
    await fn(*args, **kwargs)
  File "src/internal.pxi", line 253, in _session_loop
  File "src/handlers.pxi", line 530, in fuse_fsync_async
  File "/opt/s3ql/s3ql/lib/python3.7/site-packages/s3ql/fs.py", line 1128, in fsync
    await self.cache.flush_local(fh, blockno)
  File "/opt/s3ql/s3ql/lib/python3.7/site-packages/s3ql/block_cache.py", line 854, in flush_local
    await el.flush()
```

looks like one needs to either add an `async`

 block_cache.py: CacheEntry
```diff
-    def flush(self):
+    async def flush(self):
         self.fh.flush()
```

or remove the `await`

block_cache.py: BlockCache
```diff
     async def flush_local(self, inode, blockno):
         """Flush buffers for given block"""
 
         try:
             el = self.cache[(inode, blockno)]
         except KeyError:
             return
 
-        await el.flush()
+       el.flush()
```

**Comment by Nikratio** [comment]
Sorry about that, should be truly fixed now.
