### ISSUE TITLE
AttributeError: 'BlockCache' object has no attribute 'flush_local'

### ISSUE THREAD

**Issue by wonderpug** [s3ql/s3ql#160]
Hi, I made the change from the await bu and now getting the below. Maybe I didn't do it right?

2020-04-03 16:44:18.865 28129:MainThread root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/local/bin/mount.s3ql", line 11, in <module>
    load_entry_point('s3ql==3.4.0', 'console_scripts', 'mount.s3ql')()
  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.4.0-py3.6-linux-x86_64.egg/s3ql/mount.py", line 131, in main
    trio.run(main_async, options, stdout_log_handler)
  File "/usr/local/lib/python3.6/dist-packages/trio/_core/_run.py", line 1804, in run
    raise runner.main_task_outcome.error
  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.4.0-py3.6-linux-x86_64.egg/s3ql/mount.py", line 255, in main_async
    ret = await pyfuse3.main()
  File "/usr/local/lib/python3.6/dist-packages/pyfuse3-1.3.1-py3.6-linux-x86_64.egg/_pyfuse3.py", line 30, in wrapper
    await fn(*args, **kwargs)
  File "src/pyfuse3.pyx", line 727, in main
  File "/usr/local/lib/python3.6/dist-packages/trio/_core/_run.py", line 730, in __aexit__
    raise combined_error_from_nursery
  File "/usr/local/lib/python3.6/dist-packages/pyfuse3-1.3.1-py3.6-linux-x86_64.egg/_pyfuse3.py", line 30, in wrapper
    await fn(*args, **kwargs)
  File "src/internal.pxi", line 253, in _session_loop
  File "src/handlers.pxi", line 530, in fuse_fsync_async
  File "/usr/local/lib/python3.6/dist-packages/s3ql-3.4.0-py3.6-linux-x86_64.egg/s3ql/fs.py", line 1125, in fsync
    await self.cache.flush_local(fh, blockno)
AttributeError: 'BlockCache' object has no attribute 'flush_local'

**Comment by Nikratio** [comment]
You most likely didn't apply the change right, but it's hard to say what went wrong since you didn't say how the changed files look like. 

I'd suggest to just download the updated files.
