### ISSUE TITLE
Metadata upload interval of 0 causes mount to crash on latest release

### ISSUE THREAD

**Issue by amvoegeli** [s3ql/s3ql#171]
We recently upgraded from S3QL version 3.2.2 to 3.4.1.  We had previously been using a metadata-upload-interval of 0 when mounting.  There were no issues with this on the previous release.  With 3.4.1 however, it causes the mount to crash with the following stack trace in mount.log:

2020-05-27 13:55:13.107 1114:MainThread s3ql.mount.main_async: Mounting s3c://mysystem.com:8082/archive/PVC6E+fXa9DxDb4 at /mnt/s3mount...
2020-05-27 13:55:13.113 1117:MainThread s3ql.daemonize.detach_process_context: Daemonizing, new PID is 1119
2020-05-27 13:55:13.134 1119:MainThread py.warnings._showwarnmsg: /usr/local/lib/python3.7/dist-packages/s3ql-3.4.1-py3.7-linux-x86_64.egg/s3ql/block_cache.py:220: TrioDeprecationWarning: trio.hazmat is deprecated since Trio 0.15.0; use trio.lowlevel instead (https://github.com/python-trio/trio/issues/476)

2020-05-27 13:55:13.146 1119:MainThread py.warnings._showwarnmsg: /usr/local/lib/python3.7/dist-packages/_pyfuse3.py:30: TrioDeprecationWarning: trio.hazmat is deprecated since Trio 0.15.0; use trio.lowlevel instead (https://github.com/python-trio/trio/issues/476)
  await fn(*args, **kwargs)

2020-05-27 13:55:13.148 1119:MainThread s3ql.mount.unmount: Unmounting file system...
2020-05-27 13:55:13.149 1119:MainThread root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/local/bin/mount.s3ql", line 11, in <module>
    load_entry_point('s3ql==3.4.1', 'console_scripts', 'mount.s3ql')()
  File "/usr/local/lib/python3.7/dist-packages/s3ql-3.4.1-py3.7-linux-x86_64.egg/s3ql/mount.py", line 131, in main
    trio.run(main_async, options, stdout_log_handler)
  File "/usr/local/lib/python3.7/dist-packages/trio/_core/_run.py", line 1718, in run
    raise runner.main_task_outcome.error
  File "/usr/local/lib/python3.7/dist-packages/s3ql-3.4.1-py3.7-linux-x86_64.egg/s3ql/mount.py", line 270, in main_async
    unmount_clean = True
  File "/usr/local/lib/python3.7/dist-packages/trio/_core/_run.py", line 723, in __aexit__
    raise combined_error_from_nursery
  File "/usr/local/lib/python3.7/dist-packages/s3ql-3.4.1-py3.7-linux-x86_64.egg/s3ql/mount.py", line 603, in run
    with trio.move_on_after(self.interval):
  File "/usr/local/lib/python3.7/dist-packages/trio/_timeouts.py", line 29, in move_on_after
    if seconds < 0:
TypeError: '<' not supported between instances of 'NoneType' and 'int'

I've narrowed things down to the following:

In mount.py, if we see that the metadata upload interval is 0 then the metadata upload interval gets changed to a value of "None".  We then try to compare this "None" value with 0 in the trio "move_on_after" method and that is where things are crashing. I'm not sure if I should try to fix this in s3ql or in trio.  Also, I'm not sure if there was a specific reason why the metadata upload interval was getting changed to "None". 

Does anyone have any recommendations on this?  I'd be happy to submit a fix but wanted to make sure I didn't break anything else in the process.

**Comment by Nikratio** [comment]
Thanks for the report! I do not remember the details about this. The best way to fix this is probably to adjust S3QL to confirm with the changed Trio API. I haven't looked at the code, but it seems to me that maybe this piece of code ought not to be called in the first place if periodic metadata uploads are disabled.

**Comment by amvoegeli** [comment]
This was fixed with pull request #173
