### ISSUE TITLE
s3qlrm: pyfuse3.invalidate_entry fails with ENOENT

### ISSUE THREAD

**Issue by segator** [s3ql/s3ql#176]
**Version**: Master branch at today

when executing s3qlrm I got this error per file removed in the log of mount s3ql
```
Traceback (most recent call last):
  File "src/internal.pxi", line 125, in pyfuse3._notify_loop
  File "src/pyfuse3.pyx", line 889, in pyfuse3.invalidate_entry
FileNotFoundError: [Errno 2] fuse_lowlevel_notify_inval_entry returned: No such file or directory
2020-06-17 13:11:27.362 3358614:Thread-31 pyfuse3.run: Failed to submit invalidate_entry request for parent inode 1179869, name b'xxxxxxxxxxxxxxxxxxxxx'
Traceback (most recent call last):
  File "src/internal.pxi", line 125, in pyfuse3._notify_loop
  File "src/pyfuse3.pyx", line 889, in pyfuse3.invalidate_entry
FileNotFoundError: [Errno 2] fuse_lowlevel_notify_inval_entry returned: No such file or directory
2020-06-17 13:11:27.362 3358614:Thread-31 pyfuse3.run: Failed to submit invalidate_entry request for parent inode 1179869, name b'xxxxxxxxxxxxxxxxxxxxxxxxx'
```

blocks in the S3 seems removed, it seems a bug with pyfuse3 only?

**Comment by r0ps3c** [comment]
I am also starting to see this with s3ql-3.4.1 and pyfuse3-1.3.1

**Comment by segator** [comment]
3.4.1 seems so buggy I found diferents bugs :(

**Comment by d--j** [comment]
s3qlrm works for me (S3QL 3.4.1, pyfuse3-1.3.1)

Can you provide more details? Does it work sometimes but not always? Output of `pip3 list` of your venv. Which version of libfuse are you using?
```
$ dpkg -l | fgrep libfuse
ii  libfuse2:amd64                              2.9.4-1ubuntu3.1                            amd64        Filesystem in Userspace (library)
ii  libfuse3-3:amd64                            3.9.0-2~xenial                              amd64        Filesystem in Userspace (library) (3.x version)
```

**Comment by Nikratio** [comment]
I'm closing this bug report for now. Please note that this isn't meant to imply that you haven't found a bug - you most likely have and I'm grateful that you took the time to report it. However, without additional information it is unlikely that anyone is going to be able to do anything but this, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues). 

Please feel free to re-open this if you can provide the requested information!
