### ISSUE TITLE
ModuleNotFoundError due to B2Backend

### ISSUE THREAD

**Issue by r0ps3c** [s3ql/s3ql#183]
When attempting to use s3ql from master (65ee19a3), I immediately get an import/module error:

```
# mkdir /tmp/test
# mkfs.s3ql local:///tmp/test/
Traceback (most recent call last):
  File "/usr/local/bin/mkfs.s3ql", line 33, in <module>
    sys.exit(load_entry_point('s3ql==3.4.1', 'console_scripts', 'mkfs.s3ql')())
  File "/usr/local/bin/mkfs.s3ql", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/site-packages/s3ql-3.4.1-py3.8-linux-x86_64.egg/s3ql/mkfs.py", line 11, in <module>
    from .backends.comprenc import ComprencBackend
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/site-packages/s3ql-3.4.1-py3.8-linux-x86_64.egg/s3ql/backends/__init__.py", line 10, in <module>
    from .b2.b2_backend import B2Backend
ModuleNotFoundError: No module named 's3ql.backends.b2'
```

**Comment by r0ps3c** [comment]
This seems to be due to a missing __init__.py for the backblaze (b2) module/implementation

**Comment by powerpaul17** [comment]
Oh.. seems I forgot to commit this file and it was left missing.. :disappointed: Thanks for fixing!
