### ISSUE TITLE
S3QL master crashes on Arch Linux when writing a file (TypeError: an integer is required)

### ISSUE THREAD

**Issue by intelfx** [s3ql/s3ql#187]
S3QL master (`release-3.4.1-10-g02b4b5b0`) crashes on Arch Linux when writing to any file in a freshly created filesystem. Tests also catch this problem.

Dependencies:
- trio 0.16.0
- pyfuse3 2.0.0
- fuse3 3.9.2

Test trace:
```
tests/t4_fuse.py::TestFuse::test FAILED                                                                                                                 [ 85%]

========================================================================== FAILURES ===========================================================================
________________________________________________________________________ TestFuse.test ________________________________________________________________________
Traceback (most recent call last):
  File "/tmp/makepkg/s3ql-git/src/s3ql/tests/t4_fuse.py", line 168, in test
    self.tst_link()
  File "/tmp/makepkg/s3ql-git/src/s3ql/tests/t4_fuse.py", line 274, in tst_link
    shutil.copyfile(src, name1)
  File "/usr/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
ConnectionAbortedError: [Errno 103] Software caused connection abort: '/tmp/s3ql-mnt-gm3cf3w5/s3ql_2'
-------------------------------------------------------------------- Captured stdout call ---------------------------------------------------------------------
Please store the following master key in a safe location. It allows
decryption of the S3QL file system in case the storage objects holding
this information get corrupted:
---BEGIN MASTER KEY---
4qjw +a7R 7z+W AhI6 et9F 8qrj Cx0P 0kUY 1hIW TK89 tPo=
---END MASTER KEY---
-------------------------------------------------------------------- Captured stderr call ---------------------------------------------------------------------
WARNING: Maximum object sizes less than 1 MiB will degrade performance.
WARNING: /usr/lib/python3.8/site-packages/_pyfuse3.py:30: TrioDeprecationWarning: trio.hazmat is deprecated since Trio 0.15.0; use trio.lowlevel instead (https://github.com/python-trio/trio/issues/476)
  await fn(*args, **kwargs)

ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/tmp/makepkg/s3ql-git/src/s3ql/bin/mount.s3ql", line 21, in <module>
    s3ql.mount.main(sys.argv[1:])
  File "/tmp/makepkg/s3ql-git/src/s3ql/src/s3ql/mount.py", line 131, in main
    trio.run(main_async, options, stdout_log_handler)
  File "/usr/lib/python3.8/site-packages/trio/_core/_run.py", line 1896, in run
    raise runner.main_task_outcome.error
  File "/tmp/makepkg/s3ql-git/src/s3ql/src/s3ql/mount.py", line 255, in main_async
    ret = await pyfuse3.main()
  File "/usr/lib/python3.8/site-packages/_pyfuse3.py", line 30, in wrapper
    await fn(*args, **kwargs)
  File "src/pyfuse3.pyx", line 767, in main
  File "/usr/lib/python3.8/site-packages/trio/_core/_run.py", line 741, in __aexit__
    raise combined_error_from_nursery
  File "/usr/lib/python3.8/site-packages/_pyfuse3.py", line 30, in wrapper
    await fn(*args, **kwargs)
  File "src/internal.pxi", line 253, in _session_loop
  File "src/handlers.pxi", line 858, in fuse_create_async
TypeError: an integer is required
=================================================================== short test summary info ===================================================================
FAILED tests/t4_fuse.py::TestFuse::test - ConnectionAbortedError: [Errno 103] Software caused connection abort: '/tmp/s3ql-mnt-gm3cf3w5/s3ql_2'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================== 1 failed, 294 passed, 6 skipped in 30.29s ==========================================================

```

**Comment by intelfx** [comment]
Okay, please disregard and don't laugh — I forgot that I maintain the pyfuse3 package and assumed 2.0.0 is the latest version :)
