### ISSUE TITLE
fsck fails right after mkfs

### ISSUE THREAD

**Issue by axl8713** [s3ql/s3ql#195]
I'm starting with S3QL, but I'm striving because a number of exceptions I get using it.
The strangest one came right after the creation of the file system:
```
mkfs.s3ql --max-obj-size 10240 s3c://[...]
```
After, if I try to launch `fsck`:
```
fsck.s3ql s3c://[...]
```
The output I get is:
```
Enter file system encryption passphrase: 
Starting fsck of s3c://[...]
Using cached metadata.
ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/bin/fsck.s3ql", line 11, in <module>
    load_entry_point('s3ql==3.3.2', 'console_scripts', 'fsck.s3ql')()
  File "/usr/lib/s3ql/s3ql/fsck.py", line 1170, in main
    elif backend.lookup(meta_obj_name)['seq_no'] != param['seq_no']:
  File "/usr/lib/s3ql/s3ql/backends/comprenc.py", line 92, in lookup
    return self._verify_meta(key, meta_raw)[1]
  File "/usr/lib/s3ql/s3ql/backends/comprenc.py", line 174, in _verify_meta
    raise CorruptedObjectError('Object content does not match its key (%s vs %s)'
s3ql.backends.common.CorruptedObjectError: Object content does not match its key (s3ql_metadata_new vs s3ql_metadata)
```
Is the filesystem corrupted just after the creation?

**Comment by Nikratio** [comment]
This is unlikely, since it works in the unit test and for pretty much everyone else.

I suspect that you are working with a backend that is not actually S3 compatible.
