### ISSUE TITLE
AttributeError in contrib/clone_fs.py

### ISSUE THREAD

**Issue by zogith** [s3ql/s3ql#20]
Hi, It looks like the changes to the argument parsing code have stopped the very handy contrib utility contrib/clone_fs.py from working.

When I run it fails with an assertion, as it is fed source and destination URLs, not a single storage URL:

```
contrib/clone_fs.py  local://tmp/a local://tmp/b
Traceback (most recent call last):
  File "contrib/clone_fs.py", line 160, in <module>
    main(sys.argv[1:])
  File "contrib/clone_fs.py", line 98, in main
    options = parse_args(args)
  File "contrib/clone_fs.py", line 57, in parse_args
    return parser.parse_args(args)
  File "/home/user/s3ql-2.28/src/s3ql/parse_args.py", line 215, in parse_args
    assert options.storage_url
AttributeError: 'Namespace' object has no attribute 'storage_url'
```

**Comment by Nikratio** [comment]
Thanks for the report! Yeah, looks like this broke at some point. Will look into it when I find some time.
