### ISSUE TITLE
Test fails after build

### ISSUE THREAD

**Issue by ravenpride** [s3ql/s3ql#203]
Hello,

I've downloaded the package for s3ql v3.5.1 and installed the packages as specified by the following `requirements.txt`. The file is from one of the PR branches targeting container support:

```
# build
cython==0.29.21

# runtime
cryptography==3.1.1
defusedxml==0.6.0
apsw==3.9.2.post1
trio==0.17.0
pyfuse3==3.1.0
dugong==3.7.5

# test
pytest==6.1.0
pytest_trio==0.6.0

# GCS optional deps
requests==2.24.0
google-auth==1.21.3
google-auth-oauthlib==0.4.1
```

On my Ubuntu 20.04 LTS system building as specified in the user guide succeeds, but running the tests fails:
```
root@docker:~/s3ql-3.5.1# python3 -m pytest tests/

============================================================================================================ test session starts ============================================================================================================
platform linux -- Python 3.8.2, pytest-6.1.0, py-1.9.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /root/s3ql-3.5.1/tests, configfile: pytest.ini
plugins: trio-0.6.0
collected 351 items

tests/t1_backends.py::test_read_write[local/aes] ERROR                                                                                                                                                                                [  0%]
tests/t1_backends.py::test_read_write[local/aes] ERROR                                                                                                                                                                                [  0%]

================================================================================================================== ERRORS ===================================================================================================================
_______________________________________________________________________________________________ ERROR at setup of test_read_write[local/aes] ________________________________________________________________________________________________
Traceback (most recent call last):
  File "/root/s3ql-3.5.1/tests/pytest_checklogs.py", line 137, in pytest_runtest_setup
    check_output(item)
  File "/root/s3ql-3.5.1/tests/pytest_checklogs.py", line 133, in check_output
    check_test_log(item.catch_log_handler)
AttributeError: 'Function' object has no attribute 'catch_log_handler'
______________________________________________________________________________________________ ERROR at teardown of test_read_write[local/aes] ______________________________________________________________________________________________
Traceback (most recent call last):
  File "/root/s3ql-3.5.1/tests/pytest_checklogs.py", line 143, in pytest_runtest_teardown
    check_output(item)
  File "/root/s3ql-3.5.1/tests/pytest_checklogs.py", line 133, in check_output
    check_test_log(item.catch_log_handler)
AttributeError: 'Function' object has no attribute 'catch_log_handler'
========================================================================================================== short test summary info ==========================================================================================================
ERROR tests/t1_backends.py::test_read_write[local/aes] - AttributeError: 'Function' object has no attribute 'catch_log_handler'
ERROR tests/t1_backends.py::test_read_write[local/aes] - AttributeError: 'Function' object has no attribute 'catch_log_handler'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 2 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================================================= 2 errors in 0.75s =============================================================================================================
```

Any help is appreciated.

**Comment by d--j** [comment]
Could you try these versions?
https://github.com/s3ql/s3ql/blob/cab41e7ff33d67e981ee65500e14fce903657b8d/tests/travis-install.sh#L25-L37

(especially `pytest` < 5.0) 


They work for me on Ubuntu 20.04 (in a fresh docker container and inside a venv with `--system-site-packages`)

**Comment by ravenpride** [comment]
Thank you very much! It works for me now. The `--system-site-packages` seems to do the trick.
