### ISSUE TITLE
Running s3qlrm can generate lots of `FileNotFoundError` entries in `mount.log`

### ISSUE THREAD

**Issue by Nikratio** [s3ql/s3ql#217]
I have found a large number of errors in my `~/.s3ql/mount.log`:

```
2020-11-04 18:33:37.380 5454:Thread-25 pyfuse3.run: Failed to submit invalidate_entry request for parent inode 200499000, name b'security'
Traceback (most recent call last):
  File "src/internal.pxi", line 125, in pyfuse3._notify_loop
  File "src/pyfuse3.pyx", line 849, in pyfuse3.invalidate_entry
FileNotFoundError: [Errno 2] fuse_lowlevel_notify_inval_entry returned: No such file or directory
```

I suspect these are generated when running `s3qlrm` shortly before unmount and are harmless. Since invalidate requests are processed in a queue, the kernel may issue forget requests on its own before S3QL gets around to sending the invalidate request to the kernel.

Still, it would be great to (1) confirm that this is indeed what happens and (2) find a way to avoid the errors.

**Comment by nand2** [comment]
Ah! I got something similar I was going to post about, which also ends with 
```
FileNotFoundError: [Errno 2] fuse_lowlevel_notify_inval_entry returned: No such file or directory
```

Here is my scenario : I run S3QL v3.5.0, I do a s3qlcp and right after I do an unmount.

99.95% of the time, it goes fine : 
```
[...]
2020-11-12 10:30:56.394 30067:MainThread s3ql.daemonize.detach_process_context: Daemonizing, new PID is 30068
2020-11-12 12:31:54.768 30068:MainThread s3ql.mount.main_async: FUSE main loop terminated.
2020-11-12 12:31:54.768 30068:MainThread s3ql.mount.unmount: Unmounting file system...
2020-11-12 12:31:55.113 30068:MainThread s3ql.metadata.dump_and_upload_metadata: Dumping metadata...
[...]
```
but then, 0.05% of the time, I got a filesystem crash, **while running s3qlcp** before I do the unmount : 

```
2020/11/13 11:14:56 [...] ERROR: Uncaught top-level exception:\nTraceback (most recent call last):\n  File \"/data/s3ql/bin/s3qlcp\", line 21, in \u003cmodule\u003e\n    s3ql.cp.main(sys.argv[1:])\n  File \"/data/s3ql/src/s3ql/cp.py\", line 93, in main\n    ('(%d, %d)' % (fstat_s.st_ino, fstat_t.st_ino)).encode())\n  File \"src/pyfuse3.pyx\", line 618, in pyfuse3.setxattr\nConnectionAbortedError: [Errno 103] Software caused connection abort: '/[...]/s3ql-mount/share/.__s3ql__ctrl__'\n
```

```
2020-11-13 09:13:58.506 2420:MainThread s3ql.daemonize.detach_process_context: Daemonizing, new PID is 2421
2020-11-13 11:14:56.616 2421:MainThread s3ql.mount.unmount: Unmounting file system...
2020-11-13 11:14:56.618 2421:MainThread root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/data/s3ql/bin/mount.s3ql", line 21, in <module>
    s3ql.mount.main(sys.argv[1:])
  File "/data/s3ql/src/s3ql/mount.py", line 131, in main
    trio.run(main_async, options, stdout_log_handler)
  File "/home/manager/.local/lib/python3.6/site-packages/trio/_core/_run.py", line 1896, in run
    raise runner.main_task_outcome.error
  File "/data/s3ql/src/s3ql/mount.py", line 255, in main_async
    ret = await pyfuse3.main()
  File "/home/manager/.local/lib/python3.6/site-packages/_pyfuse3.py", line 30, in wrapper
    await fn(*args, **kwargs)
  File "src/pyfuse3.pyx", line 767, in main
  File "/home/manager/.local/lib/python3.6/site-packages/trio/_core/_run.py", line 741, in __aexit__
    raise combined_error_from_nursery
  File "/home/manager/.local/lib/python3.6/site-packages/_pyfuse3.py", line 30, in wrapper
    await fn(*args, **kwargs)
  File "src/internal.pxi", line 253, in _session_loop
  File "src/handlers.pxi", line 708, in pyfuse3.fuse_setxattr_async
  File "/data/s3ql/src/s3ql/fs.py", line 254, in setxattr
    await self.copy_tree(*tup)
  File "/data/s3ql/src/s3ql/fs.py", line 523, in copy_tree
    pyfuse3.invalidate_inode(target_inode.id)
  File "src/pyfuse3.pyx", line 834, in pyfuse3.invalidate_inode
FileNotFoundError: [Errno 2] fuse_lowlevel_notify_inval_inode returned: No such file or directory
```


What surprises me is 

1/ the fact that I see 
```
MainThread s3ql.mount.unmount: Unmounting file system...
```
and not 
```
MainThread s3ql.mount.main_async: FUSE main loop terminated.
``` 
unlike in the normal cases.

2/ The fact that a s3qlcp somehow triggers an unmount. 

I am relatively confident I don't have a race condition somewhere (s3qlcp and an unmount launched at the same time), and that I don't do an unmount after s3qlcp fails. But it could have a bug.

Do you have any pointers on the possibles reasons? And I will research it. Thanks!

**Comment by nand2** [comment]
Ok I think I understand better : s3qlcp calls fuse.setxattr which is forwarded to fs.py, to copy_tree(), and finally pyfuse3.invalidate_inode which fails. This failure goes back up and the umount is trigerred as part of the failure process.

Noob question : 
```
        # Make replication visible
        self.db.execute('UPDATE contents SET parent_inode=? WHERE parent_inode=?',
                        (target_inode.id, tmp.id))
        del self.inodes[tmp.id]
        pyfuse3.invalidate_inode(target_inode.id)
```
Here the tmp.id inode seems to be the one modified, is it normal that pyfuse3.invalidate_inode() is called on the parent?

**Comment by Nikratio** [comment]
The `EXECUTE` statement updates all the directory entries that are children of `tmp.id` and moves them into `target_inode.id`.

Since `target_inode.id` now has new contents that the kernel isn't aware of, we need to invalidate the kernel cache.

**Comment by Nikratio** [comment]
There should be no way for a caller to trigger an S3QL crash, even if  `umount.s3ql` and `s3qlcp` are called at the same time. This is certainly a bug in S3QL.

However, you are seeing a different bug than the one described in this issue. `invalidate_inode` is a blocking call, so this cannot be caused by asynchronous queue processing.

**Comment by nand2** [comment]
Thanks @Nikratio for the infos, I opened a separate issue : https://github.com/s3ql/s3ql/issues/222
I will try to find out in the coming weeks.
