### ISSUE TITLE
TypeError in contrib/benchmark.py

### ISSUE THREAD

**Issue by bitwave** [s3ql/s3ql#22]
I got the following error:

```
Test file size: 500.00 MiB
compressing with lzma-6...
ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/share/doc/s3ql/contrib/benchmark.py", line 225, in <module>
    main(sys.argv[1:])
  File "/usr/share/doc/s3ql/contrib/benchmark.py", line 163, in main
    backend = ComprencBackend(b'pass', (alg, 6), Backend('local://' + backend_dir, None, None))
TypeError: __init__() takes 2 positional arguments but 4 were given
```

maybe benchmark.py needs fixing.

used version is: 2.28

regards,
bitwave

**Comment by Nikratio** [comment]
It does, thanks for the report!

**Comment by bitwave** [comment]
No problem :)
