### ISSUE TITLE
Google Storage Backend does not always recognize when auth token has expired

### ISSUE THREAD

**Issue by Grunthos** [s3ql/s3ql#224]
Using 3.3.2 with a Google Cloud backend via oauth, I get an "unauthorized" message in the mount log occasionally:

```
2020-11-23 04:15:05.324 9005:MainThread s3ql.daemonize.detach_process_context: Daemonizing, new PID is 9006
2020-11-23 05:16:08.228 9006:Thread-3 root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/lib/s3ql/s3ql/mount.py", line 58, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/s3ql/s3ql/block_cache.py", line 446, in _upload_loop
    self._do_upload(*tmp)
  File "/usr/lib/s3ql/s3ql/block_cache.py", line 472, in _do_upload
    obj_size = backend.perform_write(do_write, 's3ql_data_%d'
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 279, in perform_write
    return fn(fh)
  File "/usr/lib/s3ql/s3ql/backends/comprenc.py", line 389, in __exit__
    self.close()
  File "/usr/lib/s3ql/s3ql/backends/comprenc.py", line 383, in close
    self.fh.close()
  File "/usr/lib/s3ql/s3ql/backends/comprenc.py", line 548, in close
    self.fh.close()
  File "/usr/lib/s3ql/s3ql/backends/gs.py", line 893, in close
    self.backend.write_fh(self.fh, self.key, self.md5.digest(),
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/lib/s3ql/s3ql/backends/gs.py", line 445, in write_fh
    raise _map_request_error(exc, key) or exc
s3ql.backends.gs.RequestError: <RequestError, code=401, reason='Unauthorized', with body data>
```

I noticed the other bug like this was fixed in head in March 2019, and that 3.3.2 was released 6 months later, so I assume that is not the problem.

FWIW, I have set a relatively small cache (1G) and was running a large rsync with many new files, and the most recent crash occurred about 1 hour after the mount. It makes me suspicious of some kind of timing issue.

**Comment by Grunthos** [comment]
Sadly the subsequent fsck failed at 1h5 (or so); with an initial "no rows found" error, followed by "unauthorized". I'm hoping the first error is normal, and the second is the same problem as above.

```
2020-11-24 10:11:22 E: WARNING: Writing dirty block 0 of inode 1059 to backend
2020-11-24 10:12:42 E: WARNING: Writing dirty block 0 of inode 1032 to backend
2020-11-24 10:15:18 E: WARNING: Writing dirty block 1 of inode 1074 to backend
2020-11-24 10:17:53 E: Dropping temporary indices...
2020-11-24 10:17:53 E: ERROR: Uncaught top-level exception:
2020-11-24 10:17:53 E: Traceback (most recent call last):
2020-11-24 10:17:53 E:   File "/usr/lib/s3ql/s3ql/database.py", line 143, in get_row
2020-11-24 10:17:53 E:     row = next(res)
2020-11-24 10:17:53 E: StopIteration
2020-11-24 10:17:53 E:
2020-11-24 10:17:53 E: During handling of the above exception, another exception occurred:
2020-11-24 10:17:53 E:
2020-11-24 10:17:53 E: Traceback (most recent call last):
2020-11-24 10:17:53 E:   File "/usr/lib/s3ql/s3ql/fsck.py", line 236, in check_cache
2020-11-24 10:17:53 E:     (block_id, obj_id) = self.conn.get_row('SELECT id, obj_id FROM blocks WHERE hash=?', (hash_,))
2020-11-24 10:17:53 E:   File "/usr/lib/s3ql/s3ql/database.py", line 145, in get_row
2020-11-24 10:17:53 E:     raise NoSuchRowError()
2020-11-24 10:17:53 E: s3ql.database.NoSuchRowError: Query produced 0 result rows
2020-11-24 10:17:53 E:
2020-11-24 10:17:53 E: During handling of the above exception, another exception occurred:
2020-11-24 10:17:53 E:
2020-11-24 10:17:53 E: Traceback (most recent call last):
2020-11-24 10:17:53 E:   File "/usr/bin/fsck.s3ql", line 11, in <module>
2020-11-24 10:17:53 E:     load_entry_point('s3ql==3.3.2', 'console_scripts', 'fsck.s3ql')()
2020-11-24 10:17:53 E:   File "/usr/lib/s3ql/s3ql/fsck.py", line 1279, in main
2020-11-24 10:17:53 E:     fsck.check(check_cache)
2020-11-24 10:17:53 E:   File "/usr/lib/s3ql/s3ql/fsck.py", line 83, in check
2020-11-24 10:17:53 E:     self.check_cache(check_cache == 'keep')
2020-11-24 10:17:53 E:   File "/usr/lib/s3ql/s3ql/fsck.py", line 247, in check_cache
2020-11-24 10:17:53 E:     obj_size = self.backend.perform_write(do_write, 's3ql_data_%d' % obj_id).get_obj_size()
2020-11-24 10:17:53 E:   File "/usr/lib/s3ql/s3ql/backends/common.py", line 108, in wrapped
2020-11-24 10:17:53 E:     return method(*a, **kw)
2020-11-24 10:17:53 E:   File "/usr/lib/s3ql/s3ql/backends/common.py", line 279, in perform_write
2020-11-24 10:17:53 E:     return fn(fh)
2020-11-24 10:17:53 E:   File "/usr/lib/s3ql/s3ql/backends/comprenc.py", line 389, in __exit__
2020-11-24 10:17:53 E:     self.close()
2020-11-24 10:17:53 E:   File "/usr/lib/s3ql/s3ql/backends/comprenc.py", line 383, in close
2020-11-24 10:17:53 E:     self.fh.close()
2020-11-24 10:17:53 E:   File "/usr/lib/s3ql/s3ql/backends/comprenc.py", line 548, in close
2020-11-24 10:17:53 E:     self.fh.close()
2020-11-24 10:17:53 E:   File "/usr/lib/s3ql/s3ql/backends/gs.py", line 893, in close
2020-11-24 10:17:53 E:     self.backend.write_fh(self.fh, self.key, self.md5.digest(),
2020-11-24 10:17:53 E:   File "/usr/lib/s3ql/s3ql/backends/common.py", line 108, in wrapped
2020-11-24 10:17:53 E:     return method(*a, **kw)
2020-11-24 10:17:53 E:   File "/usr/lib/s3ql/s3ql/backends/gs.py", line 445, in write_fh
2020-11-24 10:17:53 E:     raise _map_request_error(exc, key) or exc
2020-11-24 10:17:53 E: s3ql.backends.gs.RequestError: <RequestError, code=401, reason='Unauthorized', with body data>
```

**Comment by Grunthos** [comment]
Should I be using a different auth method with google??

**Comment by d--j** [comment]
Hi @Grunthos 

someone at the mailing list might have the same issue ( See https://groups.google.com/g/s3ql/c/nwqEOseAvgo/m/dasWzOZSBAAJ for reference )

could you try changing
https://github.com/s3ql/s3ql/blob/a67659a2f8d2e9479c9632af658eda896065a350/src/s3ql/backends/gs.py#L443
to 
```python
             if exc.message == 'Invalid Credentials' or exc.code == 401:
```

to see if this might help?

**Comment by Grunthos** [comment]
Sorry, just saw this, will try!

**Comment by Grunthos** [comment]
So far, 12 hours uploading without a problem.

**Comment by Grunthos** [comment]
I left the old simple patch running to completion and it eventually failed, not, I think, due to the suggested patch, but due to a secondary error that results from the need to re-request the tokens (or some other DNS operation during uploads?). It seems that DNS was temporarily down, resulting in an FS crash (see below). Possibly/probably should consider a backoff/retry method in this case?

```
2021-01-04 09:08:20.766 1591:Thread-3 s3ql.backends.gs._get_access_token: Requesting new access token
2021-01-04 09:52:52.827 1591:Thread-4 root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 1564, in create_socket
    return socket.create_connection(address)
  File "/usr/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/s3ql/s3ql/mount.py", line 58, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/s3ql/s3ql/block_cache.py", line 446, in _upload_loop
    self._do_upload(*tmp)
  File "/usr/lib/s3ql/s3ql/block_cache.py", line 472, in _do_upload
    obj_size = backend.perform_write(do_write, 's3ql_data_%d'
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 279, in perform_write
    return fn(fh)
  File "/usr/lib/s3ql/s3ql/backends/comprenc.py", line 389, in __exit__
    self.close()
  File "/usr/lib/s3ql/s3ql/backends/comprenc.py", line 383, in close
    self.fh.close()
  File "/usr/lib/s3ql/s3ql/backends/comprenc.py", line 548, in close
    self.fh.close()
  File "/usr/lib/s3ql/s3ql/backends/gs.py", line 893, in close
    self.backend.write_fh(self.fh, self.key, self.md5.digest(),
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/lib/s3ql/s3ql/backends/gs.py", line 401, in write_fh
    resp = self._do_request('POST', path, query_string=query_string,
  File "/usr/lib/s3ql/s3ql/backends/gs.py", line 627, in _do_request
    self.conn.send_request(method, path, body=body, headers=headers,
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 575, in send_request
    eval_coroutine(self.co_send_request(method, path, headers=headers,
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 1515, in eval_coroutine
    if not next(crt).poll(timeout=timeout):
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 604, in co_send_request
    self.connect()
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 494, in connect
    self._sock = create_socket((self.hostname, self.port))
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 1568, in create_socket
    raise HostnameNotResolvable(address[0])
dugong.HostnameNotResolvable: Host www.googleapis.com does not have any ip addresses
2021-01-04 09:52:53.888 1591:Thread-3 s3ql.mount.exchook: Unhandled top-level exception during shutdown (will not be re-raised)
2021-01-04 09:52:53.888 1591:Thread-3 root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 1564, in create_socket
    return socket.create_connection(address)
  File "/usr/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/s3ql/s3ql/mount.py", line 58, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/s3ql/s3ql/block_cache.py", line 446, in _upload_loop
    self._do_upload(*tmp)
  File "/usr/lib/s3ql/s3ql/block_cache.py", line 472, in _do_upload
    obj_size = backend.perform_write(do_write, 's3ql_data_%d'
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 279, in perform_write
    return fn(fh)
  File "/usr/lib/s3ql/s3ql/backends/comprenc.py", line 389, in __exit__
    self.close()
  File "/usr/lib/s3ql/s3ql/backends/comprenc.py", line 383, in close
    self.fh.close()
  File "/usr/lib/s3ql/s3ql/backends/comprenc.py", line 548, in close
    self.fh.close()
  File "/usr/lib/s3ql/s3ql/backends/gs.py", line 893, in close
    self.backend.write_fh(self.fh, self.key, self.md5.digest(),
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/lib/s3ql/s3ql/backends/gs.py", line 401, in write_fh
    resp = self._do_request('POST', path, query_string=query_string,
  File "/usr/lib/s3ql/s3ql/backends/gs.py", line 627, in _do_request
    self.conn.send_request(method, path, body=body, headers=headers,
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 575, in send_request
    eval_coroutine(self.co_send_request(method, path, headers=headers,
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 1515, in eval_coroutine
    if not next(crt).poll(timeout=timeout):
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 604, in co_send_request
    self.connect()
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 494, in connect
    self._sock = create_socket((self.hostname, self.port))
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 1568, in create_socket
    raise HostnameNotResolvable(address[0])
dugong.HostnameNotResolvable: Host www.googleapis.com does not have any ip addresses
2021-01-04 09:52:58.884 1591:CommitThread s3ql.mount.exchook: Unhandled top-level exception during shutdown (will not be re-raised)
2021-01-04 09:52:58.885 1591:CommitThread root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/lib/s3ql/s3ql/database.py", line 143, in get_row
    row = next(res)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/s3ql/s3ql/block_cache.py", line 591, in upload_if_dirty
    block_id = self.db.get_val('SELECT id FROM blocks WHERE hash=?', (hash_,))
  File "/usr/lib/s3ql/s3ql/database.py", line 127, in get_val
    return self.get_row(*a, **kw)[0]
  File "/usr/lib/s3ql/s3ql/database.py", line 145, in get_row
    raise NoSuchRowError()
s3ql.database.NoSuchRowError: Query produced 0 result rows

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/s3ql/s3ql/mount.py", line 58, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/s3ql/s3ql/mount.py", line 724, in run
    self.block_cache.upload_if_dirty(el)
  File "/usr/lib/s3ql/s3ql/block_cache.py", line 611, in upload_if_dirty
    self._queue_upload((el, obj_id))
  File "/usr/lib/s3ql/s3ql/block_cache.py", line 656, in _queue_upload
    raise NoWorkerThreads('no upload threads')
s3ql.block_cache.NoWorkerThreads: no upload threads
2021-01-04 09:53:04.992 1591:MainThread s3ql.block_cache.destroy: Unable to flush cache, no upload threads left alive
2021-01-04 09:53:10.009 1591:MainThread s3ql.mount.unmount: Unmounting file system...
2021-01-04 09:53:10.044 1591:MainThread root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/lib/s3ql/s3ql/mount.py", line 214, in main
    raise RuntimeError('Received signal %d, terminating' % (ret,))
RuntimeError: Received signal 15, terminating

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/mount.s3ql", line 11, in <module>
    load_entry_point('s3ql==3.3.2', 'console_scripts', 'mount.s3ql')()
  File "/usr/lib/s3ql/s3ql/mount.py", line 229, in main
    unmount_clean = True
  File "/usr/lib/python3.8/contextlib.py", line 525, in __exit__
    raise exc_details[1]
  File "/usr/lib/python3.8/contextlib.py", line 510, in __exit__
    if cb(*exc_details):
  File "/usr/lib/python3.8/contextlib.py", line 382, in _exit_wrapper
    callback(*args, **kwds)
  File "/usr/lib/s3ql/s3ql/block_cache.py", line 432, in destroy
    os.rmdir(self.path)

<--- ATTEMPTED TO MANUALLY REMOUNT

OSError: [Errno 39] Directory not empty: '/root/.s3ql/gs:=2F=2F-NAME-HIDDEN=2F-cache'
2021-01-04 10:51:19.111 17972:MainThread root.excepthook: Mountpoint does not exist.
```

**Comment by d--j** [comment]
yes, this looks like unrelated Internet or DNS problems. Maybe a local caching DNS resolver (like e.g. [pdns-recursor](https://packages.ubuntu.com/groovy/pdns-recursor)) can help.

S3Ql already retries for DNS errors. This is handled via dugong (see https://github.com/python-dugong/python-dugong/blob/release-3.7.4/dugong/__init__.py#L1520 and https://github.com/python-dugong/python-dugong/blob/release-3.7.4/dugong/__init__.py#L1571 )

You first exception is not recognised as a temporary error – looks like it is an [EAI_BADFLAGS](https://man7.org/linux/man-pages/man3/getaddrinfo.3.html#RETURN_VALUE) error. I have no clue what that is and why you get that.

**Comment by Grunthos** [comment]
I'm no expert on dugong, or s3ql, but looking at the first exception:
```
socket.gaierror: [Errno -3] Temporary failure in name resolution
```
Which was, seemingly, passed up the chain, rather than retried.

I am insufficiently familiar with s3ql to know if the relevant code calls ```is_temp_failure``` in this instance, but _do_request in gs.py (around line 627) does not seem to check for temp errors.

**Comment by Grunthos** [comment]
EAI_BADFLAGS is -1 on my Ubuntu machine; EAI_AGAIN is -3, so I'm confused.

Should this be logged as another bug?
