### ISSUE TITLE
Incorrect or buggy handling of EAI_AGAIN on Google Cloud backend

### ISSUE THREAD

**Issue by Grunthos** [s3ql/s3ql#236]
If DNS has a transient outage, the Google Cloud backed (at least) dies ungracefully:
```
2021-01-04 09:08:20.766 1591:Thread-3 s3ql.backends.gs._get_access_token: Requesting new access token
2021-01-04 09:52:52.827 1591:Thread-4 root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 1564, in create_socket
    return socket.create_connection(address)
  File "/usr/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/s3ql/s3ql/mount.py", line 58, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/s3ql/s3ql/block_cache.py", line 446, in _upload_loop
    self._do_upload(*tmp)
  File "/usr/lib/s3ql/s3ql/block_cache.py", line 472, in _do_upload
    obj_size = backend.perform_write(do_write, 's3ql_data_%d'
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 279, in perform_write
    return fn(fh)
  File "/usr/lib/s3ql/s3ql/backends/comprenc.py", line 389, in __exit__
    self.close()
  File "/usr/lib/s3ql/s3ql/backends/comprenc.py", line 383, in close
    self.fh.close()
  File "/usr/lib/s3ql/s3ql/backends/comprenc.py", line 548, in close
    self.fh.close()
  File "/usr/lib/s3ql/s3ql/backends/gs.py", line 893, in close
    self.backend.write_fh(self.fh, self.key, self.md5.digest(),
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/lib/s3ql/s3ql/backends/gs.py", line 401, in write_fh
    resp = self._do_request('POST', path, query_string=query_string,
  File "/usr/lib/s3ql/s3ql/backends/gs.py", line 627, in _do_request
    self.conn.send_request(method, path, body=body, headers=headers,
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 575, in send_request
    eval_coroutine(self.co_send_request(method, path, headers=headers,
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 1515, in eval_coroutine
    if not next(crt).poll(timeout=timeout):
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 604, in co_send_request
    self.connect()
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 494, in connect
    self._sock = create_socket((self.hostname, self.port))
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 1568, in create_socket
    raise HostnameNotResolvable(address[0])
dugong.HostnameNotResolvable: Host www.googleapis.com does not have any ip addresses
2021-01-04 09:52:53.888 1591:Thread-3 s3ql.mount.exchook: Unhandled top-level exception during shutdown (will not be re-raised)
2021-01-04 09:52:53.888 1591:Thread-3 root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 1564, in create_socket
    return socket.create_connection(address)
  File "/usr/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/s3ql/s3ql/mount.py", line 58, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/s3ql/s3ql/block_cache.py", line 446, in _upload_loop
    self._do_upload(*tmp)
  File "/usr/lib/s3ql/s3ql/block_cache.py", line 472, in _do_upload
    obj_size = backend.perform_write(do_write, 's3ql_data_%d'
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 279, in perform_write
    return fn(fh)
  File "/usr/lib/s3ql/s3ql/backends/comprenc.py", line 389, in __exit__
    self.close()
  File "/usr/lib/s3ql/s3ql/backends/comprenc.py", line 383, in close
    self.fh.close()
  File "/usr/lib/s3ql/s3ql/backends/comprenc.py", line 548, in close
    self.fh.close()
  File "/usr/lib/s3ql/s3ql/backends/gs.py", line 893, in close
    self.backend.write_fh(self.fh, self.key, self.md5.digest(),
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/lib/s3ql/s3ql/backends/gs.py", line 401, in write_fh
    resp = self._do_request('POST', path, query_string=query_string,
  File "/usr/lib/s3ql/s3ql/backends/gs.py", line 627, in _do_request
    self.conn.send_request(method, path, body=body, headers=headers,
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 575, in send_request
    eval_coroutine(self.co_send_request(method, path, headers=headers,
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 1515, in eval_coroutine
    if not next(crt).poll(timeout=timeout):
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 604, in co_send_request
    self.connect()
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 494, in connect
    self._sock = create_socket((self.hostname, self.port))
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 1568, in create_socket
    raise HostnameNotResolvable(address[0])
dugong.HostnameNotResolvable: Host www.googleapis.com does not have any ip addresses
2021-01-04 09:52:58.884 1591:CommitThread s3ql.mount.exchook: Unhandled top-level exception during shutdown (will not be re-raised)
2021-01-04 09:52:58.885 1591:CommitThread root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/lib/s3ql/s3ql/database.py", line 143, in get_row
    row = next(res)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/s3ql/s3ql/block_cache.py", line 591, in upload_if_dirty
    block_id = self.db.get_val('SELECT id FROM blocks WHERE hash=?', (hash_,))
  File "/usr/lib/s3ql/s3ql/database.py", line 127, in get_val
    return self.get_row(*a, **kw)[0]
  File "/usr/lib/s3ql/s3ql/database.py", line 145, in get_row
    raise NoSuchRowError()
s3ql.database.NoSuchRowError: Query produced 0 result rows

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/s3ql/s3ql/mount.py", line 58, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/s3ql/s3ql/mount.py", line 724, in run
    self.block_cache.upload_if_dirty(el)
  File "/usr/lib/s3ql/s3ql/block_cache.py", line 611, in upload_if_dirty
    self._queue_upload((el, obj_id))
  File "/usr/lib/s3ql/s3ql/block_cache.py", line 656, in _queue_upload
    raise NoWorkerThreads('no upload threads')
s3ql.block_cache.NoWorkerThreads: no upload threads
2021-01-04 09:53:04.992 1591:MainThread s3ql.block_cache.destroy: Unable to flush cache, no upload threads left alive
2021-01-04 09:53:10.009 1591:MainThread s3ql.mount.unmount: Unmounting file system...
2021-01-04 09:53:10.044 1591:MainThread root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/lib/s3ql/s3ql/mount.py", line 214, in main
    raise RuntimeError('Received signal %d, terminating' % (ret,))
RuntimeError: Received signal 15, terminating

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/mount.s3ql", line 11, in <module>
    load_entry_point('s3ql==3.3.2', 'console_scripts', 'mount.s3ql')()
  File "/usr/lib/s3ql/s3ql/mount.py", line 229, in main
    unmount_clean = True
  File "/usr/lib/python3.8/contextlib.py", line 525, in __exit__
    raise exc_details[1]
  File "/usr/lib/python3.8/contextlib.py", line 510, in __exit__
    if cb(*exc_details):
  File "/usr/lib/python3.8/contextlib.py", line 382, in _exit_wrapper
    callback(*args, **kwds)
  File "/usr/lib/s3ql/s3ql/block_cache.py", line 432, in destroy
    os.rmdir(self.path)

<--- ATTEMPTED TO MANUALLY REMOUNT

OSError: [Errno 39] Directory not empty: '/root/.s3ql/gs:=2F=2F-NAME-HIDDEN=2F-cache'
2021-01-04 10:51:19.111 17972:MainThread root.excepthook: Mountpoint does not exist.
```
It was incorrectly observerd previously that error -3 was EAI_BADFLAGS, but on a recent Ubuntu is translates to EAI_AGAIN (which is the text that is reported in the original error message).

For some reason it looks like this causes a crash in the backend, and no retry. Since Google Cloud (at least) seems to require hourly lookups this probably need to be more resilient.

Note: I was unsure if this should be rolled into https://github.com/s3ql/s3ql/issues/228 , but that Issue seems to relate to IO errors in B2 backends.

**Comment by Nikratio** [comment]
There problem is that there is no reliable way to distinguish between a hostname not existing and a temporary DNS problem preventing resolution - at least with the Python APIs available at the time the code was written.

Therefore, dugong uses a heuristic:

https://github.com/python-dugong/python-dugong/blob/master/dugong/__init__.py#L1545

Maybe that code could be improved, but we need to make sure that we are not fixing the failure mode reported here while at the same time introducing a new failure in a different situation (e.g. mount.s3ql perpetually trying to resolve a hostname that does not exist).

**Comment by Grunthos** [comment]
To deal with very short term transient errors, it might be best to us an exponential backoff, totalling no more than 30 seconds or so, at least in the case of EIA_AGAIN, maybe?

**Comment by Nikratio** [comment]
This is fixed in dugong now: https://github.com/python-dugong/python-dugong/commit/74c7a078ab50d68c497797610f8c6d3644854266
