### ISSUE TITLE
Error when setting backend option `tcp-timeout`

### ISSUE THREAD

**Issue by xgonc** [s3ql/s3ql#237]
When setting the `tcp-timeout` option in B2 backend, I get this:

```
$ fsck.s3ql  --backend-options disable-versions,tcp-timeout=60 b2://mybucket
ERROR: Uncaught top-level exception:
Traceback (most recent call last):
File "/usr/local/bin/fsck.s3ql", line 11, in <module>
load_entry_point('s3ql==3.7.0', 'console_scripts', 'fsck.s3ql')()
File "/usr/local/lib/python3.8/site-packages/s3ql-3.7.0-py3.8-linux-x86_64.egg/s3ql/fsck.py", line 1141, in main
backend = get_backend(options)
File "/usr/local/lib/python3.8/site-packages/s3ql-3.7.0-py3.8-linux-x86_64.egg/s3ql/common.py", line 248, in get_backend
return get_backend_factory(options)()
File "/usr/local/lib/python3.8/site-packages/s3ql-3.7.0-py3.8-linux-x86_64.egg/s3ql/common.py", line 265, in get_backend_factory
backend.fetch('s3ql_passphrase')
File "/usr/local/lib/python3.8/site-packages/s3ql-3.7.0-py3.8-linux-x86_64.egg/s3ql/backends/common.py", line 293, in fetch
return self.perform_read(do_read, key)
File "/usr/local/lib/python3.8/site-packages/s3ql-3.7.0-py3.8-linux-x86_64.egg/s3ql/backends/common.py", line 108, in wrapped
return method(*a, **kw)
File "/usr/local/lib/python3.8/site-packages/s3ql-3.7.0-py3.8-linux-x86_64.egg/s3ql/backends/common.py", line 256, in perform_read
fh = self.open_read(key)
File "/usr/local/lib/python3.8/site-packages/s3ql-3.7.0-py3.8-linux-x86_64.egg/s3ql/backends/common.py", line 108, in wrapped
return method(*a, **kw)
File "/usr/local/lib/python3.8/site-packages/s3ql-3.7.0-py3.8-linux-x86_64.egg/s3ql/backends/b2/b2_backend.py", line 424, in open_read
response = self._do_download_request('GET', key)
File "/usr/local/lib/python3.8/site-packages/s3ql-3.7.0-py3.8-linux-x86_64.egg/s3ql/backends/b2/b2_backend.py", line 272, in _do_download_request
response, body = self._do_request(self._get_download_connection(), method, path, download_body=False)
File "/usr/local/lib/python3.8/site-packages/s3ql-3.7.0-py3.8-linux-x86_64.egg/s3ql/backends/b2/b2_backend.py", line 235, in _do_request
response = connection.read_response()
File "/usr/local/lib/python3.8/site-packages/dugong/__init__.py", line 790, in read_response
return eval_coroutine(self.co_read_response(), self.timeout)
File "/usr/local/lib/python3.8/site-packages/dugong/__init__.py", line 1531, in eval_coroutine
if not next(crt).poll(timeout=timeout):
File "/usr/local/lib/python3.8/site-packages/dugong/__init__.py", line 157, in poll
return bool(poll.poll(timeout*1000)) # convert to ms
TypeError: timeout must be an integer or None
```
Is the syntax wrong of the backend options?

**Comment by d--j** [comment]
> [...] Is the syntax wrong of the backend options?

No. That's the correct syntax. PR #238 should fix this bug.
