### ISSUE TITLE
backend response error (wasabi)

### ISSUE THREAD

**Issue by eleaner** [s3ql/s3ql#24]
Hi

I am using version 2.28 with wasabisys as s3 backend.
few times a day s3ql will report such error (see below)
does it mean that there is a problem with wasabisys compatibility?

--------------

ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/home/kisiel/s3ql-2.28/src/s3ql/mount.py", line 64, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kisiel/s3ql-2.28/src/s3ql/block_cache.py", line 409, in _upload_loop
    self._do_upload(*tmp)
  File "/home/kisiel/s3ql-2.28/src/s3ql/block_cache.py", line 436, in _do_upload
    % obj_id).get_obj_size()
  File "/home/kisiel/s3ql-2.28/src/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/home/kisiel/s3ql-2.28/src/s3ql/backends/common.py", line 340, in perform_write
    return fn(fh)
  File "/home/kisiel/s3ql-2.28/src/s3ql/backends/comprenc.py", line 371, in __exit__
    self.close()
  File "/home/kisiel/s3ql-2.28/src/s3ql/backends/comprenc.py", line 365, in close
    self.fh.close()
  File "/home/kisiel/s3ql-2.28/src/s3ql/backends/comprenc.py", line 530, in close
    self.fh.close()
  File "/home/kisiel/s3ql-2.28/src/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/home/kisiel/s3ql-2.28/src/s3ql/backends/s3c.py", line 948, in close
    headers=self.headers, body=self.fh)
  File "/home/kisiel/s3ql-2.28/src/s3ql/backends/s3c.py", line 550, in _do_request
    self._parse_error_response(resp)
  File "/home/kisiel/s3ql-2.28/src/s3ql/backends/s3c.py", line 572, in _parse_error_response
    raise HTTPError(resp.status, resp.reason, resp.headers)
s3ql.backends.s3c.HTTPError: 400 Bad Request: Network error.

**Comment by Nikratio** [comment]
Looks like a problem with your proxy or the remote server. For more questions, please use the mailing list.

(I'd like to reserve use of the issue tracker for actual bugs in S3QL rather than general user support.  To subscribe to the list, send an email to `s3ql+subscribe@googlegroups.com`. After that you can post your question by sending it to `s3ql@googlegroups.com`. Alternatively, you can subscribe and access the list online at https://groups.google.com/d/forum/s3ql).
