### ISSUE TITLE
Can't do anthing(verify, fsck, mount, etc)

### ISSUE THREAD

**Issue by Kihara777** [s3ql/s3ql#25]
I upgrade the ubuntu server from 16.04 to 18.04, and then the s3ql stopped working. Each time I try to fsck or mount even verify it, it comes with tons of  errors and then stucked until sending ^C to force quit.
fsck.log:
`2018-06-26 16:09:54.654 21674:MainThread s3ql.backends.common.get_ssl_context: Reading default CA certificates.
2018-06-26 16:09:54.654 21674:MainThread s3ql.backends.swift._do_request: started with 'GET', '/', None, {'limit': 1}, None, None
2018-06-26 16:09:54.655 21674:MainThread s3ql.backends.swift._do_request: no active connection, calling _get_conn()
2018-06-26 16:09:54.655 21674:MainThread s3ql.backends.swiftks._get_conn: started
2018-06-26 16:09:55.103 21674:MainThread s3ql.backends.swift._detect_features: GET /info
2018-06-26 16:09:55.113 21674:MainThread s3ql.backends.swift._detect_features: Wrong server response.
500 Internal Error
Content-Length: 17
Content-Type: text/plain
X-Trans-Id: tx2c67a7ab594647c7aa827-005b31e6c3
Date: Tue, 26 Jun 2018 07:09:55 +0000

An error occurred
2018-06-26 16:09:55.114 21674:MainThread s3ql.backends.common.wrapped: Average retry rate: 0.02 Hz
2018-06-26 16:09:55.114 21674:MainThread s3ql.backends.common.wrapped: Encountered HTTPError (500 Internal Error), retrying Backend._get_conn (attempt 1)...
2018-06-26 16:09:55.136 21674:MainThread s3ql.backends.swiftks._get_conn: started
2018-06-26 16:09:55.328 21674:MainThread s3ql.backends.swift._detect_features: GET /info
2018-06-26 16:09:55.338 21674:MainThread s3ql.backends.swift._detect_features: Wrong server response.
500 Internal Error
Content-Length: 17
Content-Type: text/plain
X-Trans-Id: tx1b8b5bca0def4d8d8aab0-005b31e6c3
Date: Tue, 26 Jun 2018 07:09:55 +0000

An error occurred
2018-06-26 16:09:55.339 21674:MainThread s3ql.backends.common.wrapped: Average retry rate: 0.03 Hz
2018-06-26 16:09:55.339 21674:MainThread s3ql.backends.common.wrapped: Encountered HTTPError (500 Internal Error), retrying Backend._get_conn (attempt 2)...
2018-06-26 16:09:55.383 21674:MainThread s3ql.backends.swiftks._get_conn: started
2018-06-26 16:09:55.651 21674:MainThread s3ql.backends.swift._detect_features: GET /info
2018-06-26 16:09:55.660 21674:MainThread s3ql.backends.swift._detect_features: Wrong server response.
500 Internal Error
Content-Length: 17
Content-Type: text/plain
X-Trans-Id: tx2b4059b5df354536896da-005b31e6c3
Date: Tue, 26 Jun 2018 07:09:55 +0000

An error occurred
2018-06-26 16:09:55.660 21674:MainThread s3ql.backends.common.wrapped: Average retry rate: 0.05 Hz
2018-06-26 16:09:55.660 21674:MainThread s3ql.backends.common.wrapped: Encountered HTTPError (500 Internal Error), retrying Backend._get_conn (attempt 3)...
2018-06-26 16:09:55.755 21674:MainThread s3ql.backends.swiftks._get_conn: started
2018-06-26 16:09:55.986 21674:MainThread s3ql.backends.swift._detect_features: GET /info
2018-06-26 16:09:55.996 21674:MainThread s3ql.backends.swift._detect_features: Wrong server response.
500 Internal Error
Content-Length: 17
Content-Type: text/plain
X-Trans-Id: txbb149a9327a243b4babf4-005b31e6c3
Date: Tue, 26 Jun 2018 07:09:56 +0000

An error occurred
2018-06-26 16:09:55.996 21674:MainThread s3ql.backends.common.wrapped: Average retry rate: 0.07 Hz
2018-06-26 16:09:55.997 21674:MainThread s3ql.backends.common.wrapped: Encountered HTTPError (500 Internal Error), retrying Backend._get_conn (attempt 4)...
2018-06-26 16:09:56.177 21674:MainThread s3ql.backends.swiftks._get_conn: started
2018-06-26 16:09:56.360 21674:MainThread s3ql.backends.swift._detect_features: GET /info
2018-06-26 16:09:56.370 21674:MainThread s3ql.backends.swift._detect_features: Wrong server response.
500 Internal Error
Content-Length: 17
Content-Type: text/plain
X-Trans-Id: tx2ba107ee1a3b4107a1f59-005b31e6c4
Date: Tue, 26 Jun 2018 07:09:56 +0000

An error occurred
2018-06-26 16:09:56.371 21674:MainThread s3ql.backends.common.wrapped: Average retry rate: 0.08 Hz
2018-06-26 16:09:56.371 21674:MainThread s3ql.backends.common.wrapped: Encountered HTTPError (500 Internal Error), retrying Backend._get_conn (attempt 5)...
2018-06-26 16:09:56.753 21674:MainThread s3ql.backends.swiftks._get_conn: started
2018-06-26 16:09:56.966 21674:MainThread s3ql.backends.swift._detect_features: GET /info
2018-06-26 16:09:56.977 21674:MainThread s3ql.backends.swift._detect_features: Wrong server response.
500 Internal Error
Content-Length: 17
Content-Type: text/plain
X-Trans-Id: tx2c6c0ccc9e4841f2bdf97-005b31e6c4
Date: Tue, 26 Jun 2018 07:09:56 +0000

An error occurred
2018-06-26 16:09:56.977 21674:MainThread s3ql.backends.common.wrapped: Average retry rate: 0.10 Hz
2018-06-26 16:09:56.977 21674:MainThread s3ql.backends.common.wrapped: Encountered HTTPError (500 Internal Error), retrying Backend._get_conn (attempt 6)...
2018-06-26 16:09:57.666 21674:MainThread s3ql.backends.swiftks._get_conn: started
2018-06-26 16:09:57.907 21674:MainThread s3ql.backends.swift._detect_features: GET /info
2018-06-26 16:09:57.918 21674:MainThread s3ql.backends.swift._detect_features: Wrong server response.
500 Internal Error
Content-Length: 17
Content-Type: text/plain
X-Trans-Id: tx8e45843ed25942369ecc5-005b31e6c5
Date: Tue, 26 Jun 2018 07:09:57 +0000

An error occurred
2018-06-26 16:09:57.918 21674:MainThread s3ql.backends.common.wrapped: Average retry rate: 0.12 Hz
2018-06-26 16:09:57.918 21674:MainThread s3ql.backends.common.wrapped: Encountered HTTPError (500 Internal Error), retrying Backend._get_conn (attempt 7)...
2018-06-26 16:09:59.640 21674:MainThread s3ql.backends.swiftks._get_conn: started
2018-06-26 16:09:59.832 21674:MainThread s3ql.backends.swift._detect_features: GET /info
2018-06-26 16:09:59.841 21674:MainThread s3ql.backends.swift._detect_features: Wrong server response.
500 Internal Error
Content-Length: 17
Content-Type: text/plain
X-Trans-Id: tx43d4f404491a4bcaa6d6d-005b31e6c7
Date: Tue, 26 Jun 2018 07:09:59 +0000

An error occurred
2018-06-26 16:09:59.841 21674:MainThread s3ql.backends.common.wrapped: Average retry rate: 0.13 Hz
2018-06-26 16:09:59.841 21674:MainThread s3ql.backends.common.wrapped: Encountered HTTPError (500 Internal Error), retrying Backend._get_conn (attempt 8)...
2018-06-26 16:10:03.327 21674:MainThread s3ql.backends.swiftks._get_conn: started
2018-06-26 16:10:03.755 21674:MainThread s3ql.backends.swift._detect_features: GET /info
2018-06-26 16:10:03.766 21674:MainThread s3ql.backends.swift._detect_features: Wrong server response.
500 Internal Error
Content-Length: 17
Content-Type: text/plain
X-Trans-Id: tx4001e16652a14ec6a97ae-005b31e6cb
Date: Tue, 26 Jun 2018 07:10:03 +0000

An error occurred
2018-06-26 16:10:03.767 21674:MainThread s3ql.backends.common.wrapped: Average retry rate: 0.15 Hz
2018-06-26 16:10:03.767 21674:MainThread s3ql.backends.common.wrapped: Encountered HTTPError (500 Internal Error), retrying Backend._get_conn (attempt 9)...
2018-06-26 16:10:09.623 21674:MainThread s3ql.backends.swiftks._get_conn: started
2018-06-26 16:10:09.881 21674:MainThread s3ql.backends.swift._detect_features: GET /info
2018-06-26 16:10:09.897 21674:MainThread s3ql.backends.swift._detect_features: Wrong server response.
500 Internal Error
Content-Length: 17
Content-Type: text/plain
X-Trans-Id: txf3dd8d88a875427487431-005b31e6d1
Date: Tue, 26 Jun 2018 07:10:09 +0000

An error occurred
2018-06-26 16:10:09.897 21674:MainThread s3ql.backends.common.wrapped: Average retry rate: 0.17 Hz
2018-06-26 16:10:09.897 21674:MainThread s3ql.backends.common.wrapped: Encountered HTTPError (500 Internal Error), retrying Backend._get_conn (attempt 10)...
2018-06-26 16:10:23.040 21674:MainThread s3ql.backends.swiftks._get_conn: started
2018-06-26 16:10:23.219 21674:MainThread s3ql.backends.swift._detect_features: GET /info
2018-06-26 16:10:23.232 21674:MainThread s3ql.backends.swift._detect_features: Wrong server response.
500 Internal Error
Content-Length: 17
Content-Type: text/plain
X-Trans-Id: tx1f96150e72e442b1875ac-005b31e6df
Date: Tue, 26 Jun 2018 07:10:23 +0000

An error occurred
2018-06-26 16:10:23.232 21674:MainThread s3ql.backends.common.wrapped: Average retry rate: 0.18 Hz
2018-06-26 16:10:23.232 21674:MainThread s3ql.backends.common.wrapped: Encountered HTTPError (500 Internal Error), retrying Backend._get_conn (attempt 11)...
2018-06-26 16:10:46.695 21674:MainThread s3ql.backends.swiftks._get_conn: started
2018-06-26 16:10:46.875 21674:MainThread s3ql.backends.swift._detect_features: GET /info
2018-06-26 16:10:46.889 21674:MainThread s3ql.backends.swift._detect_features: Wrong server response.
500 Internal Error
Content-Length: 17
Content-Type: text/plain
X-Trans-Id: txac7ed591e0c34e628f3bc-005b31e6f6
Date: Tue, 26 Jun 2018 07:10:46 +0000

An error occurred
2018-06-26 16:10:46.889 21674:MainThread s3ql.backends.common.wrapped: Average retry rate: 0.20 Hz
2018-06-26 16:10:46.889 21674:MainThread s3ql.backends.common.wrapped: Encountered HTTPError (500 Internal Error), retrying Backend._get_conn (attempt 12)...
2018-06-26 16:11:46.948 21674:MainThread s3ql.backends.swiftks._get_conn: started
2018-06-26 16:11:47.169 21674:MainThread s3ql.backends.swift._detect_features: GET /info
2018-06-26 16:11:47.181 21674:MainThread s3ql.backends.swift._detect_features: Wrong server response.
500 Internal Error
Content-Length: 17
Content-Type: text/plain
X-Trans-Id: tx35d994097a9e4cb0b0377-005b31e733
Date: Tue, 26 Jun 2018 07:11:47 +0000

An error occurred
2018-06-26 16:11:47.181 21674:MainThread s3ql.backends.common.wrapped: Average retry rate: 0.02 Hz
2018-06-26 16:11:47.181 21674:MainThread s3ql.backends.common.wrapped: Encountered HTTPError (500 Internal Error), retrying Backend._get_conn (attempt 13)...
2018-06-26 16:13:47.924 21674:MainThread s3ql.backends.swiftks._get_conn: started
2018-06-26 16:13:48.175 21674:MainThread s3ql.backends.swift._detect_features: GET /info
2018-06-26 16:13:48.189 21674:MainThread s3ql.backends.swift._detect_features: Wrong server response.
500 Internal Error
Content-Length: 17
Content-Type: text/plain
X-Trans-Id: tx78356866cb4343d0bd76f-005b31e7ac
Date: Tue, 26 Jun 2018 07:13:48 +0000

An error occurred
2018-06-26 16:13:48.190 21674:MainThread s3ql.backends.common.wrapped: Average retry rate: 0.02 Hz
2018-06-26 16:13:48.190 21674:MainThread s3ql.backends.common.wrapped: Encountered HTTPError (500 Internal Error), retrying Backend._get_conn (attempt 14)...
2018-06-26 16:17:22.549 21674:MainThread s3ql.backends.swiftks._get_conn: started
2018-06-26 16:17:22.764 21674:MainThread s3ql.backends.swift._detect_features: GET /info
2018-06-26 16:17:22.774 21674:MainThread s3ql.backends.swift._detect_features: Wrong server response.
500 Internal Error
Content-Length: 17
Content-Type: text/plain
X-Trans-Id: txab0772ca0865444b865a8-005b31e882
Date: Tue, 26 Jun 2018 07:17:22 +0000

An error occurred
2018-06-26 16:17:22.775 21674:MainThread s3ql.backends.common.wrapped: Average retry rate: 0.02 Hz
2018-06-26 16:17:22.775 21674:MainThread s3ql.backends.common.wrapped: Encountered HTTPError (500 Internal Error), retrying Backend._get_conn (attempt 15)...
2018-06-26 16:24:24.024 21674:MainThread s3ql.backends.swiftks._get_conn: started
2018-06-26 16:24:24.246 21674:MainThread s3ql.backends.swift._detect_features: GET /info
2018-06-26 16:24:24.257 21674:MainThread s3ql.backends.swift._detect_features: Wrong server response.
500 Internal Error
Content-Length: 17
Content-Type: text/plain
X-Trans-Id: tx7eb97c39a4c4427f9ef6b-005b31ea28
Date: Tue, 26 Jun 2018 07:24:24 +0000

An error occurred
2018-06-26 16:24:24.258 21674:MainThread s3ql.backends.common.wrapped: Average retry rate: 0.02 Hz
2018-06-26 16:24:24.258 21674:MainThread s3ql.backends.common.wrapped: Encountered HTTPError (500 Internal Error), retrying Backend._get_conn (attempt 16)...
2018-06-26 16:30:55.383 21674:MainThread root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/bin/fsck.s3ql", line 11, in <module>
    load_entry_point('s3ql==2.26', 'console_scripts', 'fsck.s3ql')()
  File "/usr/lib/s3ql/s3ql/fsck.py", line 1188, in main
    backend = get_backend(options)
  File "/usr/lib/s3ql/s3ql/common.py", line 260, in get_backend
    getattr(options, 'compress', ('lzma', 2)), raw)()
  File "/usr/lib/s3ql/s3ql/common.py", line 335, in get_backend_factory
    backend_options)
  File "/usr/lib/s3ql/s3ql/backends/swiftks.py", line 26, in __init__
    super().__init__(storage_url, login, password, options)
  File "/usr/lib/s3ql/s3ql/backends/swift.py", line 72, in __init__
    self._container_exists()
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/lib/s3ql/s3ql/backends/swift.py", line 87, in _container_exists
    self._do_request('GET', '/', query_string={'limit': 1 })
  File "/usr/lib/s3ql/s3ql/backends/swift.py", line 231, in _do_request
    self.conn =  self._get_conn()
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 147, in wrapped
    time.sleep(interval * random.uniform(1, 1.5))
KeyboardInterrupt
`

**Comment by Nikratio** [comment]
The server always returns a 500 error. Not much S3QL can do. Maybe it doesn't support requests to /info? This may have not been used by the S3QL version you used before...

**Comment by Nikratio** [comment]
(Closing for now, I don't see what we could possibly do here on the S3QL side. if the server would at least return 404 we could try to use reasonable defaults)

**Comment by Kihara777** [comment]
You are right...
I just use the 2.15 binary with dome tricks on 18.04, and it works perfect now.
Is there any way to turn that "/info" feature off?

**Comment by Nikratio** [comment]
I believe it is already conditional, if the server reports that /info does not exist, then it won't be used. If the server reports an error, how should S3QL decide if this server normally supports /info but is currently broken, or if /info is not supported? Treating it as a server error is the only safe choice.
