### ISSUE TITLE
mounted filesystem fails on Uncaught top-level exception

### ISSUE THREAD

**Issue by dimonb** [s3ql/s3ql#255]
If trying to backup TimeMachine to s3ql over smb it failed with 

ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/local/bin/mount.s3ql", line 33, in <module>
    sys.exit(load_entry_point('s3ql==3.7.3', 'console_scripts', 'mount.s3ql')())
  File "/usr/local/lib/python3.8/site-packages/s3ql-3.7.3-py3.8-linux-x86_64.egg/s3ql/mount.py", line 131, in main
    trio.run(main_async, options, stdout_log_handler)
  File "/usr/local/lib/python3.8/site-packages/trio/_core/_run.py", line 1932, in run
    raise runner.main_task_outcome.error
  File "/usr/local/lib/python3.8/site-packages/s3ql-3.7.3-py3.8-linux-x86_64.egg/s3ql/mount.py", line 275, in main_async
    await pyfuse3.main()
  File "/usr/local/lib/python3.8/site-packages/_pyfuse3.py", line 30, in wrapper
    await fn(*args, **kwargs)
  File "src/pyfuse3.pyx", line 773, in main
  File "/usr/local/lib/python3.8/site-packages/trio/_core/_run.py", line 815, in __aexit__
    raise combined_error_from_nursery
  File "/usr/local/lib/python3.8/site-packages/_pyfuse3.py", line 30, in wrapper
    await fn(*args, **kwargs)
  File "src/internal.pxi", line 272, in _session_loop
  File "src/handlers.pxi", line 698, in fuse_setxattr_async
TypeError: getxattr() missing 1 required positional argument: 'ctx'

The simple patch I've made. Fix this issue and timemachine backup work as expected
[s3ql_default.txt](https://github.com/s3ql/s3ql/files/7090908/s3ql_default.txt)

**Comment by Nikratio** [comment]
Thanks for the patch! I think the code is correct as-is though. Is possible that you have an incompatible (aka old) pyfuse3 installed?

**Comment by dimonb** [comment]
I use pyfuse3 == 3.2.0
From https://hub.docker.com/r/salokyn/docker-s3ql this docker container

**Comment by Nikratio** [comment]
Thanks for the report! Looks like you actually found a bug in pyfuse3. I think it should be fixed in https://github.com/libfuse/pyfuse3/commit/f5f71c75d3ed7b. 

Could you try to install pyfuse3 from Git HEAD and see if that fixes the problem?

**Comment by dimonb** [comment]
with trunk version I have this error:

```
Traceback (most recent call last):
  File "setup.py", line 36, in <module>
    import s3ql
  File "/s3ql-3.7.3/src/s3ql/__init__.py", line 39, in <module>
    from pyfuse3 import ROOT_INODE
ImportError: cannot import name 'ROOT_INODE' from 'pyfuse3'
```

**Comment by Nikratio** [comment]
Did you build it properly, including the `build_cython` step? (http://www.rath.org/pyfuse3-docs/install.html#development-version)

**Comment by dimonb** [comment]
I've done it)
Yes, fixed pyfuse3 is fine

**Comment by Nikratio** [comment]
Thanks for checking.
