### ISSUE TITLE
ERROR: Uncaught top-level exception when mounting

### ISSUE THREAD

**Issue by depeo** [s3ql/s3ql#256]
Hello, I have been trying to get s3ql working, but when mounting the filesystem I get this error(fsck works fine though)
Any ideas what can be wrong? I have tried both HEAD version and the latest release, same error.

The server is latest Minio)

```
root@[~/s3ql/bin]# ./mount.s3ql --backend-options no-ssl --authfile authfile --debug --fg --allow-other s3c://nas:9000/backup /mnt/bucket
```

```
Using 10 upload threads.
Autodetected 524226 file descriptors available for cache entries
Using cached metadata.
Setting cache size to 9121 MB
Loaded 0 entries from cache
Mounting s3c://nas:9000/backup/ at /mnt/bucket...
Unmounting file system...
ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/root/s3ql/src/s3ql/mount.py", line 242, in main_async
    block_cache.init(options.threads)
  File "/root/s3ql/src/s3ql/block_cache.py", line 220, in init
    self.trio_token = trio.lowlevel.current_trio_token()
  File "/usr/lib/python3/dist-packages/trio/_deprecate.py", line 125, in __getattr__
    raise AttributeError(name)
AttributeError: lowlevel

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/s3ql/bin/./mount.s3ql", line 21, in <module>
    s3ql.mount.main(sys.argv[1:])
  File "/root/s3ql/src/s3ql/mount.py", line 131, in main
    trio.run(main_async, options, stdout_log_handler)
  File "/usr/lib/python3/dist-packages/trio/_core/_run.py", line 1804, in run
    raise runner.main_task_outcome.error
  File "/root/s3ql/src/s3ql/mount.py", line 290, in main_async
    unmount_clean = True
  File "/usr/lib/python3.9/contextlib.py", line 651, in __aexit__
    raise exc_details[1]
  File "/usr/lib/python3.9/contextlib.py", line 634, in __aexit__
    cb_suppress = await cb(*exc_details)
  File "/usr/lib/python3.9/contextlib.py", line 545, in _exit_wrapper
    await callback(*args, **kwds)
  File "/root/s3ql/src/s3ql/block_cache.py", line 284, in destroy
    while self.to_remove.get_nowait() is QuitSentinel:
AttributeError: 'NoneType' object has no attribute 'get_nowait'

```

**Comment by Nikratio** [comment]
Thanks for the report! What's your `trio` version? Does it help if you add `import trio.lowlevel` at the beginning of `src/s3ql/block_cache.py`?

**Comment by depeo** [comment]
Thanks! I was using the trio from Debian repo, and lowlevel wouldn't import when adding the line.

I installed trio from pip now, and its working!
