### ISSUE TITLE
Connection closed after a few minutes

### ISSUE THREAD

**Issue by delucca** [s3ql/s3ql#266]
Hi! First and foremost, thanks for this amazing tool :)

I've been using it for a few months in my personal cloud server to mount an S3 bucket (hosted by Wasabi) in my FS. It worked like a charm, running for days without any issues.

A few days ago, for some reason, the connection broke and now I can't keep it up for more than 10-30 minutes. Whenever I start it, after a few minutes it crashes. When I try to `ls` the mountpoint dir I got the following error: `ls: cannot access '/mnt/bucket.fonsecafloriano.com': Transport endpoint is not connected`.

Everytime that happens I need to reboot my cloud machine, run a `fsck.s3ql` and them mount it again. After that, it starts working again, but just for a few minutes.

Here is my `mount.log`:
```
...
2022-01-24 14:01:21.015 3345:MainThread s3ql.mount.main: Mounting s3c://s3.wasabisys.com:443/bucket.fonsecafloriano.com/ at /mnt/bucket.fonsecafloriano.com...
2022-01-24 14:18:21.730 3345:fuse-worker-26 s3ql.backends.common.wrapped: Encountered InternalError (InternalError: We encountered an internal error.  Please retry the operation again later.), retrying Backend.open_read (attempt 3)...
2022-01-24 14:18:21.843 3345:fuse-worker-26 s3ql.backends.common.wrapped: Encountered ConnectionClosed (server closed connection), retrying Backend.open_read (attempt 4)...
2022-01-24 14:18:22.036 3345:fuse-worker-26 s3ql.backends.common.wrapped: Encountered InternalError (InternalError: We encountered an internal error.  Please retry the operation again later.), retrying Backend.open_read (attempt 5)...
2022-01-24 14:18:22.394 3345:fuse-worker-26 s3ql.backends.common.wrapped: Encountered ConnectionClosed (server closed connection), retrying Backend.open_read (attempt 6)...
2022-01-24 14:18:23.068 3345:fuse-worker-26 s3ql.backends.common.wrapped: Encountered InternalError (InternalError: We encountered an internal error.  Please retry the operation again later.), retrying Backend.open_read (attempt 7)...
2022-01-24 14:18:24.421 3345:fuse-worker-26 s3ql.backends.common.wrapped: Encountered ConnectionClosed (server closed connection), retrying Backend.open_read (attempt 8)...
2022-01-24 14:18:27.897 3345:fuse-worker-26 s3ql.backends.common.wrapped: Encountered InternalError (InternalError: We encountered an internal error.  Please retry the operation again later.), retrying Backend.open_read (attempt 9)...
2022-01-24 14:18:34.766 3345:fuse-worker-26 s3ql.backends.common.wrapped: Encountered ConnectionClosed (server closed connection), retrying Backend.open_read (attempt 10)...
2022-01-24 14:18:47.152 3345:fuse-worker-26 s3ql.backends.common.wrapped: Encountered InternalError (InternalError: We encountered an internal error.  Please retry the operation again later.), retrying Backend.open_read (attempt 11)...
2022-01-24 14:19:04.511 3345:Thread-9 s3ql.backends.common.wrapped: Encountered ConnectionClosed (server closed connection), retrying Backend.delete (attempt 3)...
2022-01-24 14:19:04.628 3345:Thread-9 s3ql.backends.common.wrapped: Encountered InternalError (InternalError: We encountered an internal error.  Please retry the operation again later.), retrying Backend.delete (attempt 4)...
2022-01-24 14:19:04.791 3345:Thread-9 s3ql.backends.common.wrapped: Encountered ConnectionClosed (server closed connection), retrying Backend.delete (attempt 5)...
2022-01-24 14:19:05.392 3345:Thread-9 s3ql.backends.common.wrapped: Encountered InternalError (InternalError: We encountered an internal error.  Please retry the operation again later.), retrying Backend.delete (attempt 6)...
2022-01-24 14:19:05.720 3345:Thread-15 s3ql.backends.common.wrapped: Encountered ConnectionClosed (server closed connection), retrying Backend.delete (attempt 3)...
2022-01-24 14:19:05.831 3345:Thread-15 s3ql.backends.common.wrapped: Encountered InternalError (InternalError: We encountered an internal error.  Please retry the operation again later.), retrying Backend.delete (attempt 4)...
2022-01-24 14:19:06.041 3345:Thread-15 s3ql.backends.common.wrapped: Encountered ConnectionClosed (server closed connection), retrying Backend.delete (attempt 5)...
2022-01-24 14:19:06.338 3345:Thread-9 s3ql.backends.common.wrapped: Encountered ConnectionClosed (server closed connection), retrying Backend.delete (attempt 7)...
2022-01-24 14:19:06.540 3345:Thread-15 s3ql.backends.common.wrapped: Encountered InternalError (InternalError: We encountered an internal error.  Please retry the operation again later.), retrying Backend.delete (attempt 6)...
2022-01-24 14:19:07.484 3345:Thread-15 s3ql.backends.common.wrapped: Encountered ConnectionClosed (server closed connection), retrying Backend.delete (attempt 7)...
2022-01-24 14:19:07.728 3345:Thread-9 s3ql.backends.common.wrapped: Encountered InternalError (InternalError: We encountered an internal error.  Please retry the operation again later.), retrying Backend.delete (attempt 8)...
2022-01-24 14:19:11.025 3345:fuse-worker-26 s3ql.backends.common.wrapped: Encountered ConnectionClosed (server closed connection), retrying Backend.open_read (attempt 12)...
2022-01-24 14:19:11.102 3345:Thread-9 s3ql.backends.common.wrapped: Encountered ConnectionClosed (server closed connection), retrying Backend.delete (attempt 9)...
2022-01-24 14:19:16.343 3345:Thread-9 s3ql.backends.common.wrapped: Encountered InternalError (InternalError: We encountered an internal error.  Please retry the operation again later.), retrying Backend.delete (attempt 10)...
2022-01-24 14:19:28.480 3345:Thread-4 root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/lib/s3ql/s3ql/mount.py", line 58, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/s3ql/s3ql/block_cache.py", line 446, in _upload_loop
    self._do_upload(*tmp)
  File "/usr/lib/s3ql/s3ql/block_cache.py", line 472, in _do_upload
    obj_size = backend.perform_write(do_write, 's3ql_data_%d'
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 279, in perform_write
    return fn(fh)
  File "/usr/lib/s3ql/s3ql/backends/comprenc.py", line 389, in __exit__
    self.close()
  File "/usr/lib/s3ql/s3ql/backends/comprenc.py", line 383, in close
    self.fh.close()
  File "/usr/lib/s3ql/s3ql/backends/comprenc.py", line 548, in close
    self.fh.close()
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/lib/s3ql/s3ql/backends/s3c.py", line 909, in close
    resp = self.backend._do_request('PUT', '/%s%s' % (self.backend.prefix, self.key),
  File "/usr/lib/s3ql/s3ql/backends/s3c.py", line 528, in _do_request
    self._parse_error_response(resp)
  File "/usr/lib/s3ql/s3ql/backends/s3c.py", line 562, in _parse_error_response
    raise get_S3Error(tree.findtext('Code'), tree.findtext('Message'), resp.headers)
s3ql.backends.s3c.S3Error: TemporarilyUnavailable: Storage service is temporarily not available.  Please try again later (name: UnexpectedError | detail: ConnWaitError)
2022-01-24 14:19:28.721 3345:Thread-9 s3ql.backends.common.wrapped: Encountered ConnectionClosed (server closed connection), retrying Backend.delete (attempt 11)...
2022-01-24 14:19:33.684 3345:Thread-10 s3ql.backends.common.wrapped: Encountered InternalError (InternalError: We encountered an internal error.  Please retry the operation again later.), retrying Backend.delete (attempt 3)...
2022-01-24 14:19:33.775 3345:Thread-10 s3ql.backends.common.wrapped: Encountered ConnectionClosed (server closed connection), retrying Backend.delete (attempt 4)...
2022-01-24 14:19:34.006 3345:Thread-10 s3ql.backends.common.wrapped: Encountered InternalError (InternalError: We encountered an internal error.  Please retry the operation again later.), retrying Backend.delete (attempt 5)...
2022-01-24 14:19:34.401 3345:Thread-10 s3ql.backends.common.wrapped: Encountered ConnectionClosed (server closed connection), retrying Backend.delete (attempt 6)...
2022-01-24 14:19:58.373 3345:MainThread s3ql.mount.unmount: Unmounting file system...
2022-01-24 14:19:58.412 3345:MainThread root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/lib/s3ql/s3ql/mount.py", line 214, in main
    raise RuntimeError('Received signal %d, terminating' % (ret,))
RuntimeError: Received signal 15, terminating

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/mount.s3ql", line 11, in <module>
    load_entry_point('s3ql==3.3.2', 'console_scripts', 'mount.s3ql')()
  File "/usr/lib/s3ql/s3ql/mount.py", line 229, in main
    unmount_clean = True
  File "/usr/lib/python3.8/contextlib.py", line 525, in __exit__
    raise exc_details[1]
  File "/usr/lib/python3.8/contextlib.py", line 510, in __exit__
    if cb(*exc_details):
  File "/usr/lib/python3.8/contextlib.py", line 382, in _exit_wrapper
    callback(*args, **kwds)
  File "/usr/lib/s3ql/s3ql/mount.py", line 173, in unmount
    llfuse.close(unmount=unmount_clean)
  File "src/fuse_api.pxi", line 523, in llfuse.close
  File "src/handlers.pxi", line 23, in llfuse.fuse_destroy
  File "src/handlers.pxi", line 24, in llfuse.fuse_destroy
  File "/usr/lib/s3ql/s3ql/fs.py", line 120, in destroy
    self.forget(list(self.open_inodes.items()))
  File "/usr/lib/s3ql/s3ql/fs.py", line 1172, in forget
    self.cache.remove(id_, 0, inode.size // self.max_obj_size + 1)
  File "/usr/lib/s3ql/s3ql/block_cache.py", line 966, in remove
    self._deref_block(block_id)
  File "/usr/lib/s3ql/s3ql/block_cache.py", line 721, in _deref_block
    self._queue_removal(obj_id)
  File "/usr/lib/s3ql/s3ql/block_cache.py", line 663, in _queue_removal
    self.to_remove.put(obj, timeout=5)
AttributeError: 'NoneType' object has no attribute 'put'
```

Anyone can help me, please? :)

Thanks!

**Comment by Nikratio** [comment]
Thanks for your interest in S3QL! As far as I can tell, this is a question about how to use/install S3QL (in short, your server sends errors, and there is nothing S3QL could do about it). Could you please send it to the S3QL mailing list instead? 

I'd like to reserve use of the issue tracker for actual bugs in S3QL rather than general user support.  To subscribe to the list, send an email to `s3ql+subscribe@googlegroups.com`. After that you can post your question by sending it to `s3ql@googlegroups.com`. Alternatively, you can subscribe and access the list online at https://groups.google.com/d/forum/s3ql.

Thanks!
