### ISSUE TITLE
fsck.s3ql crashes with Uncaught top-level exception

### ISSUE THREAD

**Issue by redneb** [s3ql/s3ql#273]
My computer crashed while a s3ql volume was mounted. When I restarted my computer, I had to use `fsck.s3ql` because of the unclean unmount. But when I run `fsck.s3ql` it fails with an `Uncaught top-level exception`:
```
Enter backend login: 
Enter backend password: 
Detected Swift features for storage.sbg.cloud.ovh.net:443: copy via COPY, Bulk delete 1000 keys at a time, maximum meta value length is 255 bytes
Enter file system encryption passphrase: 
Starting fsck of swiftks://auth.cloud.ovh.net/!!!REDACTED!!!
Using cached metadata.
WARNING: Remote metadata is outdated.
Backend reports that file system is still mounted elsewhere. Either
the file system has not been unmounted cleanly or the data has not yet
propagated through the backend. In the later case, waiting for a while
should fix the problem, in the former case you should try to run fsck
on the computer where the file system has been mounted most recently.
You may also continue and use whatever metadata is available in the
backend. However, in that case YOU MAY LOOSE ALL DATA THAT HAS BEEN
UPLOADED OR MODIFIED SINCE THE LAST SUCCESSFULL METADATA UPLOAD.
Moreover, files and directories that you have deleted since then MAY
REAPPEAR WITH SOME OF THEIR CONTENT LOST.
Enter "continue, I know what I am doing" to use the outdated data anyway:
continue, I know what I am doing
Checking DB integrity...
Creating temporary extra indices...
Checking lost+found...
Checking for dirty cache objects...
Checking names (refcounts)...
Checking contents (names)...
WARNING: Content entry for inode 3 refers to non-existing name with id 1, moving to /lost+found/-3
Dropping temporary indices...
> ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/s3ql/database.py", line 143, in get_row
    row = next(res)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/s3ql/common.py", line 117, in inode_for_path
    inode = conn.get_val("SELECT inode FROM contents_v WHERE name=? AND parent_inode=?",
  File "/usr/lib/python3.9/site-packages/s3ql/database.py", line 127, in get_val
    return self.get_row(*a, **kw)[0]
  File "/usr/lib/python3.9/site-packages/s3ql/database.py", line 145, in get_row
    raise NoSuchRowError()
s3ql.database.NoSuchRowError: Query produced 0 result rows

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.9/fsck.s3ql", line 33, in <module>
    sys.exit(load_entry_point('s3ql==3.8.1', 'console_scripts', 'fsck.s3ql')())
  File "/usr/lib/python3.9/site-packages/s3ql/fsck.py", line 1289, in main
    fsck.check(check_cache)
  File "/usr/lib/python3.9/site-packages/s3ql/fsck.py", line 86, in check
    self.check_contents_name()
  File "/usr/lib/python3.9/site-packages/s3ql/fsck.py", line 323, in check_contents_name
    (id_p_new, newname) = self.resolve_free(b"/lost+found", newname)
  File "/usr/lib/python3.9/site-packages/s3ql/fsck.py", line 1068, in resolve_free
    inode_p = inode_for_path(path, self.conn)
  File "/usr/lib/python3.9/site-packages/s3ql/common.py", line 120, in inode_for_path
    raise KeyError('Path %s does not exist' % path)
KeyError: "Path b'lost+found' does not exist"
```

So the first issue that `fsck.s3ql` seems to find, is the following:
```
WARNING: Content entry for inode 3 refers to non-existing name with id 1, moving to /lost+found/-3
```
It appears that inode 3 has name with id 1, which `fsck.s3ql` thinks it doesn't exist, but this is simply not true. Here's what the db looks like *before* `fsck.s3ql` is ran:
```
sqlite> SELECT * FROM contents WHERE inode=3;
┌───────┬─────────┬───────┬──────────────┐
│ rowid │ name_id │ inode │ parent_inode │
├───────┼─────────┼───────┼──────────────┤
│ 1     │ 1       │ 3     │ 1            │
└───────┴─────────┴───────┴──────────────┘
sqlite> SELECT * FROM names WHERE id=1;
┌────┬────────────┬──────────┐
│ id │    name    │ refcount │
├────┼────────────┼──────────┤
│ 1  │ lost+found │ 1        │
└────┴────────────┴──────────┘
```
So the name with id 1 does in fact exist.

So `fsck.s3ql` tries to fix what it considers to be an issue with a non existent name, by moving inode 3 to `lost+found`, i.e. itself. So it sets `parent_inode` of inode 3 to 3, which of course creates a circular reference. So after the (failed) run of `fsck.s3ql` the db looks like this:
```
sqlite> SELECT * FROM contents_v WHERE inode=3;
┌───────┬─────────┬───────┬──────────────┬────────┬──────┬──────────┐
│ rowid │ name_id │ inode │ parent_inode │   id   │ name │ refcount │
├───────┼─────────┼───────┼──────────────┼────────┼──────┼──────────┤
│ 1     │ 574852  │ 3     │ 3            │ 574852 │ -3   │ 1        │
└───────┴─────────┴───────┴──────────────┴────────┴──────┴──────────┘
```

Any ideas why this might be happening?

**Comment by redneb** [comment]
Upon further investigation, this is not caused by a s3ql bug, it caused by a nasty [sqlite bug](https://sqlite.org/forum/forumpost/031e262a89b6a9d2). It has been fixed in sqlite 3.38.3.

Despite that, I think maybe it would make sense for s3ql to add a check to avoid trying to move `lost+found` inside `lost+found`. While the root cause of the above issue was a sqlite bug, the behavior of `fsck.s3ql` made it even worse.

**Comment by d--j** [comment]
@redneb  if you still have an affected installation, could you try the PR #275 with your installation? Use https://github.com/s3ql/s3ql/pull/275#issuecomment-1120428488 to replace the files of your local installation.

**Comment by redneb** [comment]
@d--j Thanks for looking into this. I was able to recover my db in my case. But your changes in #275 look good.
