### ISSUE TITLE
fsck.s3ql crashes ERROR: Uncaught top-level exception: "Path b'lost+found' does not exist"

### ISSUE THREAD

**Issue by mcdatho** [s3ql/s3ql#274]
I have and old s3ql filesystem, I don't have the VM and I closed s3ql with a system shutdown or ctrl-c (the last time i used it) so the filesystem is not in clean state. I run fsck and failed with "Path b'lost+found' does not exist" This is a second time that I use a fsck without synced metadata, and the folder lost+found was create that time.

Enter backend login: 
Enter backend password: 
Enter file system encryption passphrase: 
Starting fsck of S3URL_REDACTED
Backend reports that file system is still mounted elsewhere. Either
the file system has not been unmounted cleanly or the data has not yet
propagated through the backend. In the later case, waiting for a while
should fix the problem, in the former case you should try to run fsck
on the computer where the file system has been mounted most recently.
You may also continue and use whatever metadata is available in the
backend. However, in that case YOU MAY LOOSE ALL DATA THAT HAS BEEN
UPLOADED OR MODIFIED SINCE THE LAST SUCCESSFULL METADATA UPLOAD.
Moreover, files and directories that you have deleted since then MAY
REAPPEAR WITH SOME OF THEIR CONTENT LOST.
Enter "continue, I know what I am doing" to use the outdated data anyway:
continue, I know what I am doing
> Downloading and decompressing metadata...
Reading metadata...
..objects..
..blocks..
..inodes..
..inode_blocks..
..symlink_targets..
..names..
..contents..
..ext_attributes..
Creating temporary extra indices...
Checking lost+found...
Checking for dirty cache objects...
Checking names (refcounts)...
Checking contents (names)...
WARNING: Content entry for inode 3 refers to non-existing name with id 1, moving to /lost+found/-3
Dropping temporary indices...
> ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/s3ql-3.8.1-py3.8-linux-x86_64.egg/s3ql/database.py", line 143, in get_row
    row = next(res)
StopIteration

During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/s3ql-3.8.1-py3.8-linux-x86_64.egg/s3ql/common.py", line 117, in inode_for_path
    inode = conn.get_val("SELECT inode FROM contents_v WHERE name=? AND parent_inode=?",
  File "/usr/local/lib/python3.8/dist-packages/s3ql-3.8.1-py3.8-linux-x86_64.egg/s3ql/database.py", line 127, in get_val
    return self.get_row(*a, **kw)[0]
  File "/usr/local/lib/python3.8/dist-packages/s3ql-3.8.1-py3.8-linux-x86_64.egg/s3ql/database.py", line 145, in get_row
    raise NoSuchRowError()
s3ql.database.NoSuchRowError: Query produced 0 result rows

During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/usr/local/bin/fsck.s3ql", line 11, in <module>
    load_entry_point('s3ql==3.8.1', 'console_scripts', 'fsck.s3ql')()
  File "/usr/local/lib/python3.8/dist-packages/s3ql-3.8.1-py3.8-linux-x86_64.egg/s3ql/fsck.py", line 1289, in main
    fsck.check(check_cache)
  File "/usr/local/lib/python3.8/dist-packages/s3ql-3.8.1-py3.8-linux-x86_64.egg/s3ql/fsck.py", line 86, in check
    self.check_contents_name()
  File "/usr/local/lib/python3.8/dist-packages/s3ql-3.8.1-py3.8-linux-x86_64.egg/s3ql/fsck.py", line 323, in check_contents_name
    (id_p_new, newname) = self.resolve_free(b"/lost+found", newname)
  File "/usr/local/lib/python3.8/dist-packages/s3ql-3.8.1-py3.8-linux-x86_64.egg/s3ql/fsck.py", line 1068, in resolve_free
    inode_p = inode_for_path(path, self.conn)
  File "/usr/local/lib/python3.8/dist-packages/s3ql-3.8.1-py3.8-linux-x86_64.egg/s3ql/common.py", line 120, in inode_for_path
    raise KeyError('Path %s does not exist' % path)
KeyError: "Path b'lost+found' does not exist"

A second fsck

> Enter backend login: 
Enter backend password: 
Enter file system encryption passphrase: 
Starting fsck of S3URL_REDACTED
Using cached metadata.
WARNING: Remote metadata is outdated.
Checking DB integrity...
Creating temporary extra indices...
Checking lost+found...
Checking for dirty cache objects...
Checking names (refcounts)...
Checking contents (names)...
Dropping temporary indices...
ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/local/bin/fsck.s3ql", line 11, in <module>
    load_entry_point('s3ql==3.8.1', 'console_scripts', 'fsck.s3ql')()
  File "/usr/local/lib/python3.8/dist-packages/s3ql-3.8.1-py3.8-linux-x86_64.egg/s3ql/fsck.py", line 1289, in main
    fsck.check(check_cache)
  File "/usr/local/lib/python3.8/dist-packages/s3ql-3.8.1-py3.8-linux-x86_64.egg/s3ql/fsck.py", line 86, in check
    self.check_contents_name()
  File "/usr/local/lib/python3.8/dist-packages/s3ql-3.8.1-py3.8-linux-x86_64.egg/s3ql/fsck.py", line 318, in check_contents_name
    path = get_path(inode_p, self.conn)[1:]
  File "/usr/local/lib/python3.8/dist-packages/s3ql-3.8.1-py3.8-linux-x86_64.egg/s3ql/common.py", line 147, in get_path
    raise RuntimeError('Failed to resolve name "%s" at inode %d to path',
RuntimeError: ('Failed to resolve name "%s" at inode %d to path', None, 3)

apt list sqlite3
3.31.1-4ubuntu0.3 amd64 [installed]

s3ql version
s3ql-3.8.1

Ubuntu 20.04

i don't remember the s3ql version of the old VM

**Comment by d--j** [comment]
This looks like #273:  Your sqlite has a new feature (bloom filter indexes) that has a bug until version 3.38.3

Unfortunately `fsck.s3ql` does not account for this bug and moves the folder `lost+found` into `lost+found`. You need to fix that with the sqlite CLI manually after you got yourself a fixed version of sqlite.

**Comment by d--j** [comment]
@mcdatho could you try the PR #275 with your installation? Use https://github.com/s3ql/s3ql/pull/275#issuecomment-1120428488 to replace the files of your local installation.

**Comment by szepeviktor** [comment]
@Nikratio Does S3QL have a new life? 🧬
