### ISSUE TITLE
TypeError when parsing error response

### ISSUE THREAD

**Issue by kescherCode** [s3ql/s3ql#278]
At https://github.com/s3ql/s3ql/blob/896e1debfb4886329e96bcef90860a3d37956094/src/s3ql/backends/s3c.py#L550

there is a TypeError that can occur, causing the filesystem to crash.
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/s3ql/mount.py", line 58, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/site-packages/s3ql/block_cache.py", line 318, in _upload_loop
    self._do_upload(*tmp)
  File "/usr/lib/python3.10/site-packages/s3ql/block_cache.py", line 383, in _do_upload
    obj_size = backend.perform_write(do_write, 's3ql_data_%d'
  File "/usr/lib/python3.10/site-packages/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/lib/python3.10/site-packages/s3ql/backends/common.py", line 278, in perform_write
    with self.open_write(key, metadata, is_compressed) as fh:
  File "/usr/lib/python3.10/site-packages/s3ql/backends/comprenc.py", line 389, in __exit__
    self.close()
  File "/usr/lib/python3.10/site-packages/s3ql/backends/comprenc.py", line 383, in close
    self.fh.close()
  File "/usr/lib/python3.10/site-packages/s3ql/backends/comprenc.py", line 548, in close
    self.fh.close()
  File "/usr/lib/python3.10/site-packages/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/lib/python3.10/site-packages/s3ql/backends/s3c.py", line 913, in close
    resp = self.backend._do_request('PUT', '/%s%s' % (self.backend.prefix, self.key),
  File "/usr/lib/python3.10/site-packages/s3ql/backends/s3c.py", line 532, in _do_request
    self._parse_error_response(resp)
  File "/usr/lib/python3.10/site-packages/s3ql/backends/s3c.py", line 552, in _parse_error_response
    if not XML_CONTENT_RE.match(content_type) or resp.length == 0:
TypeError: expected string or bytes-like object
```

**Comment by kescherCode** [comment]
Fixed by #277
