### ISSUE TITLE
Bad binding argument type supplied - type dict

### ISSUE THREAD

**Issue by paulharris** [s3ql/s3ql#336]
Hi, great project!

I'm trying it out with b2 backend (probably not relevant here).
side-question: how do I connect to b2 with the s3c backend driver?  b2 has an s3 compatible API, but I'm not sure what the backend host:port should be.

Creating a folder triggered this exception (and then a "Transport endpoint is not connected" message)

```
2023-11-28 12:10:05.359 3418008 DEBUG    Thread-1 s3ql.http.co_readall: got 1034 bytes                                                                                                           
2023-11-28 12:10:05.359 3418008 DEBUG    Thread-1 s3ql.http.co_read: start (len=65536)                                                                                                           
2023-11-28 12:10:05.359 3418008 DEBUG    Thread-1 s3ql.http._co_read_id: start (len=65536)
2023-11-28 12:10:05.359 3418008 DEBUG    Thread-1 s3ql.http.co_readall: got 0 bytes
2023-11-28 12:10:05.359 3418008 DEBUG    Thread-1 s3ql.http.co_readall: done (1034 bytes)
2023-11-28 12:10:05.360 3418008 DEBUG    Thread-1 s3ql.block_cache._do_upload: uploaded 7 bytes in 3.116 seconds, 0.00 MiB/s                                                                     
2023-11-28 12:10:05.360 3418008 ERROR    Thread-1 s3ql.mount.exchook: Unhandled exception in thread, terminating                                                                                  
Traceback (most recent call last):                                                                                                                                                               
File "/usr/local/lib/python3.9/dist-packages/s3ql-5.1.2-py3.9-linux-x86_64.egg/s3ql/mount.py", line 72, in run_with_except_hook
run_old(*args, **kw)
File "/usr/lib/python3.9/threading.py", line 892, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.9/dist-packages/s3ql-5.1.2-py3.9-linux-x86_64.egg/s3ql/block_cache.py", line 322, in _upload_loop
self._do_upload(*tmp)                                                                                                                                                                        
File "/usr/local/lib/python3.9/dist-packages/s3ql-5.1.2-py3.9-linux-x86_64.egg/s3ql/block_cache.py", line 381, in _do_upload                                                                        
trio.from_thread.run(with_event_loop, sys.exc_info(), trio_token=self.trio_token)                                                                                                            
File "/usr/local/lib/python3.9/dist-packages/trio/_threads.py", line 533, in from_thread_run
return message_to_trio.queue.get().unwrap()                                                                                                                                                  
File "/usr/lib/python3/dist-packages/outcome/_sync.py", line 111, in unwrap
raise captured_error                                                                                                                                                                            
File "/usr/local/lib/python3.9/dist-packages/trio/_threads.py", line 91, in unprotected_afn
return await coro                                                                                                                                                                               
File "/usr/local/lib/python3.9/dist-packages/s3ql-5.1.2-py3.9-linux-x86_64.egg/s3ql/block_cache.py", line 334, in with_event_loop                                                                   
self.db.execute('UPDATE objects SET phys_size=? WHERE id=?', (obj_size, obj_id))                                                                                                             
File "/usr/local/lib/python3.9/dist-packages/s3ql-5.1.2-py3.9-linux-x86_64.egg/s3ql/database.py", line 210, in execute                                                                              
self.conn.cursor().execute(*a, **kw)                                                                                                                                                          
TypeError: Bad binding argument type supplied - argument #1: type dict
2023-11-28 12:10:05.362 3418008 DEBUG    MainThread s3ql.mount.stop: started                                                                                                                     
2023-11-28 12:10:05.362 3418008 ERROR    Thread-1 __main__.excepthook: Uncaught top-level exception:                                                                                              
Traceback (most recent call last):                                                                                                                                                                  
File "/usr/local/lib/python3.9/dist-packages/s3ql-5.1.2-py3.9-linux-x86_64.egg/s3ql/mount.py", line 72, in run_with_except_hook                                                                     
run_old(*args, **kw)
File "/usr/lib/python3.9/threading.py", line 892, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.9/dist-packages/s3ql-5.1.2-py3.9-linux-x86_64.egg/s3ql/block_cache.py", line 322, in _upload_loop
self._do_upload(*tmp)
File "/usr/local/lib/python3.9/dist-packages/s3ql-5.1.2-py3.9-linux-x86_64.egg/s3ql/block_cache.py", line 381, in _do_upload
trio.from_thread.run(with_event_loop, sys.exc_info(), trio_token=self.trio_token)
File "/usr/local/lib/python3.9/dist-packages/trio/_threads.py", line 533, in from_thread_run
return message_to_trio.queue.get().unwrap()
File "/usr/lib/python3/dist-packages/outcome/_sync.py", line 111, in unwrap
raise captured_error
File "/usr/local/lib/python3.9/dist-packages/trio/_threads.py", line 91, in unprotected_afn
return await coro
File "/usr/local/lib/python3.9/dist-packages/s3ql-5.1.2-py3.9-linux-x86_64.egg/s3ql/block_cache.py", line 334, in with_event_loop
self.db.execute('UPDATE objects SET phys_size=? WHERE id=?', (obj_size, obj_id))
File "/usr/local/lib/python3.9/dist-packages/s3ql-5.1.2-py3.9-linux-x86_64.egg/s3ql/database.py", line 210, in execute
self.conn.cursor().execute(*a, **kw)
TypeError: Bad binding argument type supplied - argument #1: type dict
2023-11-28 12:10:05.362 3418008 DEBUG    MainThread s3ql.mount.stop: started
2023-11-28 12:10:05.363 3418008 INFO     MainThread s3ql.mount.unmount: Unmounting file system...
```

**Comment by paulharris** [comment]
I dug, looks like the problem is a result of a recent update to b2 backend.

Commit #fada8362ace2f1bae40314eb5f7f64a3edd7b77d

Doesn't anyone else use b2?  Should I be using the s3c backend?

b2_backend.py:521
returns json_response

but it should just return the size of the blob.

This is what it returns instead (one example):
```
{'accountId': 'xxxx', 'action': 'upload', 'bucketId': 'xxxx', 'contentLength': 328, 'contentMd5': '893b5d39ddfcd10db15114d2ff30845f', 'contentSha1': '077b7a4253523c370b1ec2d8fffb6caf504ef997', 'contentType': 'application/octet-stream', 'fileId': '4_z904fbd62c410183789c4001c_f1003b121df073d73_d20231128_m051727_c005_v0501011_t0000_u01701148647322', 'fileInfo': {'meta-md5': 'JfFNFr903ow5QDMqzSZRBw==', 'meta-format': 'raw2', 'meta-000': "'format_version': 2,'compression': 'LZMA','encryption': 'AES_v2','nonce': b'0zAY9l1Z2UFzM3FsX3BhcmFtcw==','data': b'qorPAw==','object_id': 's3ql_params','signature': b'xo/1VohM8i0qdEpqp0eQ0k6CHZuDYhNVJwUTI+ub8c8=',"}, 'fileName': 'data1/s3ql_params', 'fileRetention': {'isClientAuthorizedToRead': False, 'value': None}, 'legalHold': {'isClientAuthorizedToRead': False, 'value': None}, 'serverSideEncryption': {'algorithm': 'AES256', 'mode': 'SSE-B2'}, 'uploadTimestamp': 1701148647322}
```

I see we could return `jsonresponse['contentLength']`
or, follow what other backends appear to do, ie returns the original parameter `len_`

I'm not sure what the design requires, or if the two lengths could be different, so I've modified the code to return len_ as per the other backends.
