### ISSUE TITLE
Retry requests when server closes connection

### ISSUE THREAD

**Issue by johlra** [s3ql/s3ql#343]
I have trouble with version 5 of s3ql (version 4 don't have this problem) that it crashes on upload of data. It doesn't happens all the time, but to often. I suspect it happens when there is high load on the server but haven't found a good way to confirm.
```
2024-01-04 16:22:44.141 2242457:Thread-4 (_upload_loop) s3ql.mount.exchook: Unhandled exception in thread, terminating
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/backends/common.py", line 114, in wrapped
    return method(*a, **kw)
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/backends/s3c.py", line 404, in _write_fh
    resp = self._do_request(
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/backends/s3c.py", line 483, in _do_request
    resp = self._do_request_inner(
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/backends/s3c.py", line 743, in _do_request_inner
    resp = self.conn.read_response()
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/http.py", line 735, in read_response
    return eval_coroutine(self.co_read_response())
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/http.py", line 1388, in eval_coroutine
    next(it)
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/http.py", line 759, in co_read_response
    (status, reason) = await self._co_read_status()
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/http.py", line 884, in _co_read_status
    line = await self._co_readstr_until(b'\r\n', MAX_LINE_SIZE)
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/http.py", line 1184, in _co_readstr_until
    raise ConnectionClosed('server closed connection')
s3ql.http.ConnectionClosed: server closed connection
```
It also happens when fsck uploadind dirty blocks
```
2024-01-05 04:27:22.060 2361847:MainThread __main__.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/database.py", line 272, in get_row
    row = next(res)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/fsck.py", line 246, in check_cache
    obj_id = self.conn.get_val('SELECT id FROM objects WHERE hash=?', (hash_should,))
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/database.py", line 256, in get_val
    return self.get_row(*a, **kw)[0]
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/database.py", line 274, in get_row
    raise NoSuchRowError()
s3ql.database.NoSuchRowError: Query produced 0 result rows

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/backends/common.py", line 114, in wrapped
    return method(*a, **kw)
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/backends/s3c.py", line 404, in _write_fh
    resp = self._do_request(
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/backends/s3c.py", line 483, in _do_request
    resp = self._do_request_inner(
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/backends/s3c.py", line 743, in _do_request_inner
    resp = self.conn.read_response()
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/http.py", line 735, in read_response
    return eval_coroutine(self.co_read_response())
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/http.py", line 1388, in eval_coroutine
    next(it)
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/http.py", line 759, in co_read_response
    (status, reason) = await self._co_read_status()
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/http.py", line 884, in _co_read_status
    line = await self._co_readstr_until(b'\r\n', MAX_LINE_SIZE)
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/http.py", line 1184, in _co_readstr_until
    raise ConnectionClosed('server closed connection')
s3ql.http.ConnectionClosed: server closed connection

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/fsck.s3ql", line 33, in <module>
    sys.exit(load_entry_point('s3ql==5.1.3', 'console_scripts', 'fsck.s3ql')())
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/fsck.py", line 1352, in main
    fsck.check(check_cache)
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/fsck.py", line 103, in check
    self.check_cache(check_cache == 'keep')
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/fsck.py", line 256, in check_cache
    obj_size = self.backend.write_fh('s3ql_data_%d' % obj_id, fh)
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/backends/comprenc.py", line 279, in write_fh
    return self.backend.write_fh(key, fh, meta_raw)
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/backends/s3c.py", line 393, in write_fh
    return self._write_fh(key, fh, off, len_, metadata or {})
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/backends/common.py", line 118, in wrapped
    if not self.is_temp_failure(exc):
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/backends/s3c.py", line 151, in is_temp_failure
    self.conn.reset()
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/http.py", line 1321, in reset
    self.connect()
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/http.py", line 459, in connect
    self._sock = create_socket((self.hostname, self.port))
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/http.py", line 1420, in create_socket
    return try_connect(lambda: socket.create_connection(address), address[0])
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/http.py", line 1412, in try_connect
    return fn()
  File "/usr/local/lib/python3.10/dist-packages/s3ql-5.1.3-py3.10-linux-x86_64.egg/s3ql/http.py", line 1420, in <lambda>
    return try_connect(lambda: socket.create_connection(address), address[0])
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```
Full [mount.log](https://github.com/s3ql/s3ql/files/13839842/mount.log)

**Comment by Nikratio** [comment]
If I remember correctly, S3QL does not retry if the server *refuses* the connection. The idea being that this is more likely to be a permanent than temporary problem, and retrying would just delay the time until the user finally gets notified that something is wrong. I don't have strong feelings about this though. Changing it should be as easy as adding `ConnectionRefusedError` to the right list somewhere in http.py.

**Comment by paulharris** [comment]
I've seen this as well,

There is also a warning about "During handling of the above exception, another exception occurred",
I guess that is the "Refused Connection" issue.

I'd much rather it wait a little bit and try again.
When it breaks, the container has be manually stopped, the mount unmounted, fsck, and then mount and container start...


```
2024-04-24 02:46:30.371 809688 DEBUG    MainThread s3ql.block_cache.destroy: waiting for removal threads...                                          [76/94198]
2024-04-24 02:46:30.374 809688 DEBUG    MainThread s3ql.block_cache.destroy: cleanup done.                                                                     
2024-04-24 02:46:30.375 809688 ERROR    MainThread __main__.excepthook: Uncaught top-level exception:                                                          
Traceback (most recent call last):                                                                                                                             
  File "/home/paul/s3ql/s3ql/src/s3ql/block_cache.py", line 684, in _get_entry                                                                                 
    el = self.cache[(inode, blockno)]                                                                                                                          
KeyError: (1716, 346)                                                                                                                                          
                                                                                                                                                               
During handling of the above exception, another exception occurred:                                                                                            
                                                                                                                                                               
Traceback (most recent call last):                                                                                                                             
  File "/home/paul/s3ql/s3ql/bin/./mount.s3ql", line 21, in <module>                                                                                           
    s3ql.mount.main(sys.argv[1:])                                                                                                                              
  File "/home/paul/s3ql/s3ql/src/s3ql/mount.py", line 149, in main                                                                                             
    trio.run(main_async, options, stdout_log_handler)                                                                                                          
  File "/home/paul/.local/lib/python3.9/site-packages/trio/_core/_run.py", line 2251, in run                                                                   
    raise runner.main_task_outcome.error                                                                                                                       
  File "/home/paul/s3ql/s3ql/src/s3ql/mount.py", line 307, in main_async                                                                                       
    await pyfuse3.main()                                                                                                                                       
  File "/usr/lib/python3/dist-packages/_pyfuse3.py", line 30, in wrapper                                                                                       
    await fn(*args, **kwargs)                                                                                                                                  
  File "src/pyfuse3.pyx", line 776, in main                                                                                                                    
  File "/home/paul/.local/lib/python3.9/site-packages/trio/_core/_run.py", line 948, in __aexit__                                                              
    raise combined_error_from_nursery                                                                                                                          
  File "/usr/lib/python3/dist-packages/_pyfuse3.py", line 30, in wrapper                                                                                       
    await fn(*args, **kwargs)                                                                                                                                  
  File "src/internal.pxi", line 278, in _session_loop                                                                                                          
  File "src/handlers.pxi", line 413, in fuse_read_async                                                                                                        
  File "/home/paul/s3ql/s3ql/src/s3ql/fs.py", line 1167, in read                                                                                               
    tmp = await self._readwrite(fh, offset, length=length)                                                                                                     
  File "/home/paul/s3ql/s3ql/src/s3ql/fs.py", line 1245, in _readwrite                                                                                         
    async with self.cache.get(id_, blockno, max_write=max_write) as fh:                                                                                        
  File "/usr/lib/python3.9/contextlib.py", line 175, in __aenter__                                                                                             
    return await self.gen.__anext__()                                                                                                                          
  File "/home/paul/s3ql/s3ql/src/s3ql/block_cache.py", line 663, in get                                                                                        
    el = await self._get_entry(inode, blockno)                                                                                                                 
  File "/home/paul/s3ql/s3ql/src/s3ql/block_cache.py", line 718, in _get_entry                                                                                 
    await trio.to_thread.run_sync(with_lock_released)                                                                                                          
  File "/home/paul/.local/lib/python3.9/site-packages/trio/_threads.py", line 404, in to_thread_run_sync                                                       
    return msg_from_thread.unwrap()                                                                                                
 File "/home/paul/.local/lib/python3.9/site-packages/trio/_threads.py", line 404, in to_thread_run_sync                                             [38/94198]
    return msg_from_thread.unwrap()                                                                                                                            
  File "/home/paul/.local/lib/python3.9/site-packages/outcome/_impl.py", line 213, in unwrap                                                                   
    raise captured_error                                                                                                                                       
  File "/home/paul/.local/lib/python3.9/site-packages/trio/_threads.py", line 326, in do_release_then_return_result                                            
    return result.unwrap()                                                                                                                                     
  File "/home/paul/.local/lib/python3.9/site-packages/outcome/_impl.py", line 213, in unwrap                                                                   
    raise captured_error                                                                                                                                       
  File "/home/paul/.local/lib/python3.9/site-packages/trio/_threads.py", line 351, in worker_fn                                                                
    ret = sync_fn(*args)                                                                                                                                       
  File "/home/paul/s3ql/s3ql/src/s3ql/block_cache.py", line 716, in with_lock_released                                                                         
    backend.readinto_fh('s3ql_data_%d' % obj_id, tmpfh)                                                                                                        
  File "/home/paul/s3ql/s3ql/src/s3ql/backends/comprenc.py", line 173, in readinto_fh                                                                          
    meta_raw = self.backend.readinto_fh(key, buf1)                                                                                                             
  File "/home/paul/s3ql/s3ql/src/s3ql/backends/b2/b2_backend.py", line 417, in readinto_fh                                                                     
    return self._readinto_fh(key, fh, fh.tell())                                                                                                               
  File "/home/paul/s3ql/s3ql/src/s3ql/backends/common.py", line 118, in wrapped                                                                                
    if not self.is_temp_failure(exc):                                                                                                                          
  File "/home/paul/s3ql/s3ql/src/s3ql/backends/b2/b2_backend.py", line 340, in is_temp_failure                                                                 
    self._reset_connections()                                                                                                                                  
  File "/home/paul/s3ql/s3ql/src/s3ql/backends/b2/b2_backend.py", line 155, in _reset_connections                                                              
    self.upload_connection.reset()                                                                                                                             
  File "/home/paul/s3ql/s3ql/src/s3ql/http.py", line 1321, in reset                                                                                            
    self.connect()                                                                                                                                             
  File "/home/paul/s3ql/s3ql/src/s3ql/http.py", line 459, in connect                                                                                           
    self._sock = create_socket((self.hostname, self.port))                                                                                                     
  File "/home/paul/s3ql/s3ql/src/s3ql/http.py", line 1420, in create_socket                                                                                    
    return try_connect(lambda: socket.create_connection(address), address[0])                                                                                  
  File "/home/paul/s3ql/s3ql/src/s3ql/http.py", line 1412, in try_connect                                                                                      
    return fn()                                                                                                                                                
  File "/home/paul/s3ql/s3ql/src/s3ql/http.py", line 1420, in <lambda>                                                                                         
    return try_connect(lambda: socket.create_connection(address), address[0])                                                                                  
  File "/usr/lib/python3.9/socket.py", line 843, in create_connection                                                                                          
    raise err                                                                                                                                                  
  File "/usr/lib/python3.9/socket.py", line 831, in create_connection                                                                                          
    sock.connect(sa)                                                                                                                                           
ConnectionRefusedError: [Errno 111] Connection refused                                                                                                         
2024-04-24 02:46:30.380 809688 DEBUG    MainThread s3ql.http.disconnect: start                                                                                 
2024-04-24 02:46:30.380 809688 DEBUG    MainThread s3ql.http.connect: start                                                                                    
2024-04-24 02:46:30.380 809688 DEBUG    MainThread s3ql.http.connect: connecting to ('api005.backblazeb2.com', 443)                  
2024-04-24 02:46:30.644 809688 DEBUG    MainThread s3ql.http.connect: establishing ssl layer                                                                   
2024-04-24 02:46:30.909 809688 DEBUG    MainThread s3ql.http.connect: done                                                                                     
2024-04-24 02:46:30.909 809688 DEBUG    MainThread s3ql.http.disconnect: start                                                                                 
2024-04-24 02:46:30.909 809688 DEBUG    MainThread s3ql.http.connect: start                                                                                    
2024-04-24 02:46:30.909 809688 DEBUG    MainThread s3ql.http.connect: connecting to ('f005.backblazeb2.com', 443)                                              
2024-04-24 02:46:31.175 809688 DEBUG    MainThread s3ql.http.connect: establishing ssl layer                                                                   
2024-04-24 02:46:31.442 809688 DEBUG    MainThread s3ql.http.connect: done                                                                                     
2024-04-24 02:46:31.442 809688 DEBUG    MainThread s3ql.http.disconnect: start                                                                                 
2024-04-24 02:46:31.442 809688 DEBUG    MainThread s3ql.http.disconnect: already closed                                                                        
2024-04-24 02:46:31.442 809688 DEBUG    MainThread s3ql.http.connect: start                                                                                    
2024-04-24 02:46:31.442 809688 DEBUG    MainThread s3ql.http.connect: connecting to ('pod-050-1010-08.backblaze.com', 443)                                     
Error in atexit._run_exitfuncs:                                                                                                                                
Traceback (most recent call last):                                                                                                                             
  File "/home/paul/s3ql/s3ql/src/s3ql/backends/pool.py", line 59, in flush                                                                                     
    self.pool.pop().close()                                                                                                                                    
  File "/home/paul/s3ql/s3ql/src/s3ql/backends/comprenc.py", line 294, in close                                                                                
    self.backend.close()                                                                                                                                       
  File "/home/paul/s3ql/s3ql/src/s3ql/backends/b2/b2_backend.py", line 639, in close                                                                           
    self._reset_connections()                                                                                                                                  
  File "/home/paul/s3ql/s3ql/src/s3ql/backends/b2/b2_backend.py", line 155, in _reset_connections                                                              
    self.upload_connection.reset()                                                                                                                             
  File "/home/paul/s3ql/s3ql/src/s3ql/http.py", line 1321, in reset                                                                                            
    self.connect()                                                                                                                                             
  File "/home/paul/s3ql/s3ql/src/s3ql/http.py", line 459, in connect                                                                                           
    self._sock = create_socket((self.hostname, self.port))                                                                                                     
  File "/home/paul/s3ql/s3ql/src/s3ql/http.py", line 1420, in create_socket                                                                                    
    return try_connect(lambda: socket.create_connection(address), address[0])                                                                                  
  File "/home/paul/s3ql/s3ql/src/s3ql/http.py", line 1412, in try_connect                                                                                      
    return fn()                                                                                                                                                
  File "/home/paul/s3ql/s3ql/src/s3ql/http.py", line 1420, in <lambda>                                                                                         
    return try_connect(lambda: socket.create_connection(address), address[0])                                                                                  
  File "/usr/lib/python3.9/socket.py", line 843, in create_connection                                                                                          
    raise err                                                                                                                                                  
  File "/usr/lib/python3.9/socket.py", line 831, in create_connection                                                                                          
    sock.connect(sa)                                                                                                                                           
ConnectionRefusedError: [Errno 111] Connection refused                                            
```

**Comment by paulharris** [comment]
Any guidance on where to add the exception handler in http.py ?

**Comment by Nikratio** [comment]
https://github.com/s3ql/s3ql/blob/master/src/s3ql/http.py#L1449

**Comment by johlra** [comment]
This issue is fixed for me with the release of S3QL 5.2.2
