### ISSUE TITLE
Disconnection after some time of running

### ISSUE THREAD

**Issue by dimonb** [s3ql/s3ql#344]
After 10-12 hours and notebook sleep next exception happen:

```traceback
2024-01-18 04:21:14.290 2810:Trio worker thread 22 s3ql.database.upload_metadata: Uploading metadata...
2024-01-18 04:21:14.290 2810:MainThread s3ql.database.upload_metadata: Uploading metadata...
2024-01-18 04:21:14.291 2810:MainThread s3ql.database.upload_metadata: Calculating metadata checksum...
2024-01-18 04:21:17.899 2810:MainThread s3ql.backends.gs._get_access_token: Requesting new access token
2024-01-18 04:21:18.150 2810:MainThread s3ql.mount.unmount: Unmounting file system...
2024-01-18 04:21:18.995 2810:Thread-6 (_upload_loop) s3ql.mount.exchook: Unhandled exception in thread, termin
ating
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/s3ql-5.1.3-py3.11-linux-aarch64.egg/s3ql/mount.py", line 72, in run_
with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/site-packages/s3ql-5.1.3-py3.11-linux-aarch64.egg/s3ql/block_cache.py", line 315, 
in _upload_loop
    tmp = trio.from_thread.run(self.to_upload[1].receive, trio_token=self.trio_token)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/trio/_threads.py", line 304, in from_thread_run
    return _run_fn_as_system_task(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/trio/_threads.py", line 245, in _run_fn_as_system_task
    return q.get().unwrap()
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/outcome/_impl.py", line 213, in unwrap
    raise captured_error
  File "/usr/lib/python3.11/site-packages/trio/_threads.py", line 287, in unprotected_afn
    return await coro
  File "/usr/lib/python3.11/site-packages/trio/_channel.py", line 314, in receive
    return await trio.lowlevel.wait_task_rescheduled(abort_fn)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/trio/_core/_traps.py", line 166, in wait_task_rescheduled
    return (await _async_yield(WaitTaskRescheduled(abort_func))).unwrap()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/outcome/_impl.py", line 213, in unwrap
    raise captured_error
  File "/usr/lib/python3.11/site-packages/trio/_core/_run.py", line 1173, in raise_cancel
    raise Cancelled._create()
trio.Cancelled: Cancelled

2024-01-18 04:21:18.997 2810:MainThread __main__.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/s3ql-5.1.3-py3.11-linux-aarch64.egg/s3ql/backends/gs.py", line 527, 
in _get_access_token
    self.adc[0].refresh(self.adc[1])
  File "/usr/lib/python3.11/site-packages/google/oauth2/service_account.py", line 441, in refresh
    access_token, expiry, _ = _client.jwt_grant(
                              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/google/oauth2/_client.py", line 308, in jwt_grant
    response_data = _token_endpoint_request(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/google/oauth2/_client.py", line 279, in _token_endpoint_request
    _handle_error_response(response_data, retryable_error)
  File "/usr/lib/python3.11/site-packages/google/oauth2/_client.py", line 72, in _handle_error_response
    raise exceptions.RefreshError(
google.auth.exceptions.RefreshError: ('invalid_grant: Invalid JWT: Token must be a short-lived token (60 minut
es) and in a reasonable timeframe. Check your iat and exp values in the JWT claim.', {'error': 'invalid_grant'
, 'error_description': 'Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timefr
ame. Check your iat and exp values in the JWT claim.'})
```

Look like refresh token was invalidated and not refreshed in time (because of sleep)

**Comment by dimonb** [comment]
It seams the problem is in clock

**Comment by Nikratio** [comment]
I'm not sure I understand what you are saying. S3QL is using the user-specified refresh token to periodically refresh the access token. I'm not sure if there's anything here we could do differently. Or are you saying there is a bug in Google's oauth client? Does this happen every time when you suspend, or is it possible that you have hit a rare race condition?

**Comment by Nikratio** [comment]
I'm closing this issue for now. Please note that this isn't meant to imply that you haven't found a real bug or worthwhile potential improvement - you most likely have and I'm grateful that you took the time to report it.

Unfortunately, without additional information it's unlikely that anyone will be able to work on this.
