### ISSUE TITLE
ETag parsing error after upgrade

### ISSUE THREAD

**Issue by Self-Perfection** [s3ql/s3ql#35]
I've been using s3ql 2.21 about a year with custom server (minio) and worked quite well.

Today I've upgraded to s3ql 2.28 and s3ql can't mount FS anymore. First it complained about possible version mismatch, so I've performed `s3qladm upgrade` - completed successfully as I recall. Now I can't do anything with s3ql. For instance

```
fsck.s3ql --force  --backend-options no-ssl s3c://custom.host:customport/custom/path
WARNING: Object closed prematurely, can't check MD5, and have to reset connection
ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/bin/fsck.s3ql", line 11, in <module>
    load_entry_point('s3ql==2.28', 'console_scripts', 'fsck.s3ql')()
  File "/usr/lib/python3.6/site-packages/s3ql/fsck.py", line 1203, in main
    backend = get_backend(options)
  File "/usr/lib/python3.6/site-packages/s3ql/common.py", line 248, in get_backend
    return get_backend_factory(options)()
  File "/usr/lib/python3.6/site-packages/s3ql/common.py", line 265, in get_backend_factory
    backend.fetch('s3ql_passphrase')
  File "/usr/lib/python3.6/site-packages/s3ql/backends/common.py", line 354, in fetch
    return self.perform_read(do_read, key)
  File "/usr/lib/python3.6/site-packages/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/lib/python3.6/site-packages/s3ql/backends/common.py", line 319, in perform_read
    res = fn(fh)
  File "/usr/lib/python3.6/site-packages/s3ql/backends/common.py", line 351, in do_read
    data = fh.read()
  File "/usr/lib/python3.6/site-packages/s3ql/backends/s3c.py", line 857, in read
    etag = self.resp.headers['ETag'].strip('"')
AttributeError: 'NoneType' object has no attribute 'strip'
```

I have not looked closer, and it seems this might be server-side bug, but still - it used to work!

**Comment by Nikratio** [comment]
Thanks for the report! I'm somewhat at a loss here, since this indeed looks like a server problem (the server is no longer sending an ETag header), and apparently you are the only one that is encountering this. Are you sure that this is caused by the S3QL upgrade, rather than just coinciding with it by chance?

**Comment by Nikratio** [comment]
If Minion claims to be AWS S3 compatible, then that's a bug on their side, yes: https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html

Maybe Minion only provides ETags if they have been sent with the upload request? There's two ways to verify that the upload went fine: send an ETag with the upload and let the server check it, or calculate the ETag during the upload and compare it with the value returned by the server in response to the upload request.  It is possible that S3QL changed behavior here a while ago.
