### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_nowait'

### ISSUE THREAD

**Issue by dalgwen** [s3ql/s3ql#356]
Hello,

First, many thanks for your work, i've been using s3ql for many, many years.

After a crash occuring during an automated backup (probably because of a disconnection ?)

```
Keeping backup 2023-01-21_02:45:01 (current age 526) for age range 400 to 1000
Keeping backup 2024-03-29_02:45:01 (current age 94) for age range 80 to 240 in 2 cycles
Backup 2024-06-29_02:45:01 is no longer needed, removing...
Saving state..
ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/home/nextclouds3ql/s3ql-4.0.0/bin//../contrib/expire_backups.py", line 281, in <module>
    main(sys.argv[1:])
  File "/home/nextclouds3ql/s3ql-4.0.0/bin//../contrib/expire_backups.py", line 133, in main
    with open(options.state + '.new', 'wb') as fh:
OSError: [Errno 107] Transport endpoint is not connected: '.expire_backups.dat.new'
```

And after I did the mandatory fsck (with success) caused by this disconnection,
I tried to restart s3ql.

I encountered this error  (s3ql version 4.0.0) : 

```
Jul 01 08:54:10 mount.s3ql[1651379]: Unmounting file system...
Jul 01 08:54:10 mount.s3ql[1651379]: ERROR: Uncaught top-level exception:
Jul 01 08:54:10 mount.s3ql[1651379]: Traceback (most recent call last):
Jul 01 08:54:10 mount.s3ql[1651379]:   File "/home/nextclouds3ql/s3ql-4.0.0/src/s3ql/mount.py", line 242, in main_async
Jul 01 08:54:10 mount.s3ql[1651379]:     block_cache.init(options.threads)
Jul 01 08:54:10 mount.s3ql[1651379]:   File "/home/nextclouds3ql/s3ql-4.0.0/src/s3ql/block_cache.py", line 219, in init
Jul 01 08:54:10 mount.s3ql[1651379]:     self.trio_token = trio.lowlevel.current_trio_token()
Jul 01 08:54:10 mount.s3ql[1651379]:   File "/usr/lib/python3/dist-packages/trio/_deprecate.py", line 125, in __getattr__
Jul 01 08:54:10 mount.s3ql[1651379]:     raise AttributeError(name)
Jul 01 08:54:10 mount.s3ql[1651379]: AttributeError: lowlevel
Jul 01 08:54:10 mount.s3ql[1651379]: During handling of the above exception, another exception occurred:
Jul 01 08:54:10 mount.s3ql[1651379]: Traceback (most recent call last):
Jul 01 08:54:10 mount.s3ql[1651379]:   File "/home/nextclouds3ql/s3ql-4.0.0/bin/mount.s3ql", line 21, in <module>
Jul 01 08:54:10 mount.s3ql[1651379]:     s3ql.mount.main(sys.argv[1:])
Jul 01 08:54:10 mount.s3ql[1651379]:   File "/home/nextclouds3ql/s3ql-4.0.0/src/s3ql/mount.py", line 131, in main
Jul 01 08:54:10 mount.s3ql[1651379]:     trio.run(main_async, options, stdout_log_handler)
Jul 01 08:54:10 mount.s3ql[1651379]:   File "/usr/lib/python3/dist-packages/trio/_core/_run.py", line 1804, in run
Jul 01 08:54:10 mount.s3ql[1651379]:     raise runner.main_task_outcome.error
Jul 01 08:54:10 mount.s3ql[1651379]:   File "/home/nextclouds3ql/s3ql-4.0.0/src/s3ql/mount.py", line 290, in main_async
Jul 01 08:54:10 mount.s3ql[1651379]:     unmount_clean = True
Jul 01 08:54:10 mount.s3ql[1651379]:   File "/usr/lib/python3.9/contextlib.py", line 651, in __aexit__
Jul 01 08:54:10 mount.s3ql[1651379]:     raise exc_details[1]
Jul 01 08:54:10 mount.s3ql[1651379]:   File "/usr/lib/python3.9/contextlib.py", line 634, in __aexit__
Jul 01 08:54:10 mount.s3ql[1651379]:     cb_suppress = await cb(*exc_details)
Jul 01 08:54:10 mount.s3ql[1651379]:   File "/usr/lib/python3.9/contextlib.py", line 545, in _exit_wrapper
Jul 01 08:54:10 mount.s3ql[1651379]:     await callback(*args, **kwds)
Jul 01 08:54:10 mount.s3ql[1651379]:   File "/home/nextclouds3ql/s3ql-4.0.0/src/s3ql/block_cache.py", line 283, in destroy
Jul 01 08:54:10 mount.s3ql[1651379]:     while self.to_remove.get_nowait() is QuitSentinel:
Jul 01 08:54:10 mount.s3ql[1651379]: AttributeError: 'NoneType' object has no attribute 'get_nowait'
```

After two fsck cycles, with always the same result, I decided to upgrade to s3ql 5.2.0 (with success), but I'm stuck with the same error (thought, logically, different line number)

```
Jul 01 10:55:58 mount.s3ql[1660794]: Using 10 upload threads.
Jul 01 10:55:58 mount.s3ql[1660794]: Autodetected 524226 file descriptors available for cache entries
Jul 01 10:55:58 mount.s3ql[1660794]: Detected Swift features for storage.gra.cloud.ovh.net:443: Bulk delete 1000 keys at a time, maximum meta value length is 255 bytes
Jul 01 10:55:59 mount.s3ql[1660794]: Using cached metadata.
Jul 01 10:55:59 mount.s3ql[1660794]: Loaded 0 entries from cache
Jul 01 10:55:59 mount.s3ql[1660794]: Mounting swiftks://auth.cloud.ovh.net/GRA:CloudData/ at /mnt/s3ql...
Jul 01 10:56:01 mount.s3ql[1660794]: Unmounting file system...
Jul 01 10:56:01 mount.s3ql[1660794]: ERROR: Uncaught top-level exception:
Jul 01 10:56:01 mount.s3ql[1660794]: Traceback (most recent call last):
Jul 01 10:56:01 mount.s3ql[1660794]:   File "/home/nextclouds3ql/s3ql-5.2.0/src/s3ql/mount.py", line 273, in main_async
Jul 01 10:56:01 mount.s3ql[1660794]:     block_cache.init(options.threads)
Jul 01 10:56:01 mount.s3ql[1660794]:   File "/home/nextclouds3ql/s3ql-5.2.0/src/s3ql/block_cache.py", line 226, in init
Jul 01 10:56:01 mount.s3ql[1660794]:     self.trio_token = trio.lowlevel.current_trio_token()
Jul 01 10:56:01 mount.s3ql[1660794]:   File "/usr/lib/python3/dist-packages/trio/_deprecate.py", line 125, in __getattr__
Jul 01 10:56:01 mount.s3ql[1660794]:     raise AttributeError(name)
Jul 01 10:56:01 mount.s3ql[1660794]: AttributeError: lowlevel
Jul 01 10:56:01 mount.s3ql[1660794]: During handling of the above exception, another exception occurred:
Jul 01 10:56:01 mount.s3ql[1660794]: Traceback (most recent call last):
Jul 01 10:56:01 mount.s3ql[1660794]:   File "/home/nextclouds3ql/s3ql-5.2.0/bin/mount.s3ql", line 21, in <module>
Jul 01 10:56:01 mount.s3ql[1660794]:     s3ql.mount.main(sys.argv[1:])
Jul 01 10:56:01 mount.s3ql[1660794]:   File "/home/nextclouds3ql/s3ql-5.2.0/src/s3ql/mount.py", line 149, in main
Jul 01 10:56:01 mount.s3ql[1660794]:     trio.run(main_async, options, stdout_log_handler)
Jul 01 10:56:01 mount.s3ql[1660794]:   File "/usr/lib/python3/dist-packages/trio/_core/_run.py", line 1804, in run
Jul 01 10:56:01 mount.s3ql[1660794]:     raise runner.main_task_outcome.error
Jul 01 10:56:01 mount.s3ql[1660794]:   File "/home/nextclouds3ql/s3ql-5.2.0/src/s3ql/mount.py", line 322, in main_async
Jul 01 10:56:01 mount.s3ql[1660794]:     unmount_clean = True
Jul 01 10:56:01 mount.s3ql[1660794]:   File "/usr/lib/python3.9/contextlib.py", line 651, in __aexit__
Jul 01 10:56:01 mount.s3ql[1660794]:     raise exc_details[1]
Jul 01 10:56:01 mount.s3ql[1660794]:   File "/usr/lib/python3.9/contextlib.py", line 634, in __aexit__
Jul 01 10:56:01 mount.s3ql[1660794]:     cb_suppress = await cb(*exc_details)
Jul 01 10:56:01 mount.s3ql[1660794]:   File "/usr/lib/python3.9/contextlib.py", line 545, in _exit_wrapper
Jul 01 10:56:01 mount.s3ql[1660794]:     await callback(*args, **kwds)
Jul 01 10:56:01 mount.s3ql[1660794]:   File "/home/nextclouds3ql/s3ql-5.2.0/src/s3ql/block_cache.py", line 290, in destroy
Jul 01 10:56:01 mount.s3ql[1660794]:     while self.to_remove.get_nowait() is QuitSentinel:
Jul 01 10:56:01 mount.s3ql[1660794]: AttributeError: 'NoneType' object has no attribute 'get_nowait'
```

I found this mail ("https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1919253.html") mentionning the error  `"AttributeError: 'NoneType' object has no attribute 'get_nowait'"`, but it doesn't seem related. I, of course, already have fuse3 installed.

By the way, don't know if it's related, but when investigating old log, I found a strange one I'm having, **for months**, at least once a day, only during backup : 
```
Jun 19 02:48:16 mount.s3ql[3269]: ERROR: Failed to submit invalidate_entry request for parent inode 477866080, name b'files'
Jun 19 02:48:16 mount.s3ql[3269]: Traceback (most recent call last):
Jun 19 02:48:16 mount.s3ql[3269]:   File "src/internal.pxi", line 125, in pyfuse3._notify_loop
Jun 19 02:48:16 mount.s3ql[3269]:   File "src/pyfuse3.pyx", line 918, in pyfuse3.invalidate_entry
Jun 19 02:48:16 mount.s3ql[3269]: FileNotFoundError: [Errno 2] fuse_lowlevel_notify_inval_entry returned: No such file or directory
Jun 19 02:48:16 mount.s3ql[3269]: ERROR: Failed to submit invalidate_entry request for parent inode 477866080, name b'files_versions'
Jun 19 02:48:16 mount.s3ql[3269]: Traceback (most recent call last):
Jun 19 02:48:16 mount.s3ql[3269]:   File "src/internal.pxi", line 125, in pyfuse3._notify_loop
Jun 19 02:48:16 mount.s3ql[3269]:   File "src/pyfuse3.pyx", line 918, in pyfuse3.invalidate_entry
Jun 19 02:48:16 mount.s3ql[3269]: FileNotFoundError: [Errno 2] fuse_lowlevel_notify_inval_entry returned: No such file or directory
Jun 19 02:48:16 mount.s3ql[3269]: ERROR: Failed to submit invalidate_entry request for parent inode 477866080, name b'files_trashbin'
Jun 19 02:48:16 mount.s3ql[3269]: Traceback (most recent call last):
Jun 19 02:48:16 mount.s3ql[3269]:   File "src/internal.pxi", line 125, in pyfuse3._notify_loop
Jun 19 02:48:16 mount.s3ql[3269]:   File "src/pyfuse3.pyx", line 918, in pyfuse3.invalidate_entry
Jun 19 02:48:16 mount.s3ql[3269]: FileNotFoundError: [Errno 2] fuse_lowlevel_notify_inval_entry returned: No such file or directory
Jun 19 02:48:16 mount.s3ql[3269]: ERROR: Failed to submit invalidate_entry request for parent inode 477866079, name b'cache'
Jun 19 02:48:16 mount.s3ql[3269]: Traceback (most recent call last):
Jun 19 02:48:16 mount.s3ql[3269]:   File "src/internal.pxi", line 125, in pyfuse3._notify_loop
Jun 19 02:48:16 mount.s3ql[3269]:   File "src/pyfuse3.pyx", line 918, in pyfuse3.invalidate_entry
Jun 19 02:48:16 mount.s3ql[3269]: FileNotFoundError: [Errno 2] fuse_lowlevel_notify_inval_entry returned: No such file or directory
Jun 19 02:48:16 mount.s3ql[3269]: ERROR: Failed to submit invalidate_entry request for parent inode 477866079, name b'uploads'
Jun 19 02:48:16 mount.s3ql[3269]: Traceback (most recent call last):
Jun 19 02:48:16 mount.s3ql[3269]:   File "src/internal.pxi", line 125, in pyfuse3._notify_loop
Jun 19 02:48:16 mount.s3ql[3269]:   File "src/pyfuse3.pyx", line 918, in pyfuse3.invalidate_entry
Jun 19 02:48:16 mount.s3ql[3269]: FileNotFoundError: [Errno 2] fuse_lowlevel_notify_inval_entry returned: No such file or director
```

Please, does someone have an idea ?

Many thanks for reading me.

**Comment by d--j** [comment]
The first exception
```
Jul 01 10:56:01 mount.s3ql[1660794]: Traceback (most recent call last):
Jul 01 10:56:01 mount.s3ql[1660794]:   File "/home/nextclouds3ql/s3ql-5.2.0/src/s3ql/mount.py", line 273, in main_async
Jul 01 10:56:01 mount.s3ql[1660794]:     block_cache.init(options.threads)
Jul 01 10:56:01 mount.s3ql[1660794]:   File "/home/nextclouds3ql/s3ql-5.2.0/src/s3ql/block_cache.py", line 226, in init
Jul 01 10:56:01 mount.s3ql[1660794]:     self.trio_token = trio.lowlevel.current_trio_token()
Jul 01 10:56:01 mount.s3ql[1660794]:   File "/usr/lib/python3/dist-packages/trio/_deprecate.py", line 125, in __getattr__
Jul 01 10:56:01 mount.s3ql[1660794]:     raise AttributeError(name)
Jul 01 10:56:01 mount.s3ql[1660794]: AttributeError: lowlevel
```

is the important one in this case. (The second one should not happen, but only occurs when mount.s3ql exits without having called BlockCache.init)

S3QL is [not compatible with the Trio version you are using](https://github.com/s3ql/s3ql/blob/master/rst/installation.rst#dependencies). You need at least [version 0.15.0](https://trio.readthedocs.io/en/stable/history.html#trio-0-15-0-2020-05-19)

**Comment by dalgwen** [comment]
Sorry to have missed this !
It was indeed a dependencies version error. 
I didn't check in this direction because it previously worked.

There is (to me) some python mystery behind this. How could this have worked until now ?
I suppose I did some downgrade, without knowing it ?

Many thanks, you save my day.
