### ISSUE TITLE
CacheEntry.seek() doesn't support whence=, and backends compute object length the wrong way

### ISSUE THREAD

**Issue by dalgwen** [s3ql/s3ql#358]
Hello,

Following my upgrade to the 5.2.0 version and my issue (#356, fixed ?), I now encounter a new error as soon as I update a file.

My environment is a debian 11 server, but as I suspected a mismatch in some lib (unable to update pyfuse3 to a recent version with pip and had to use the debian packaged one, which install an old trio version), I tried with a fresh s3ql docker from tiredofit and get the same error.

I have to clarify that I applied the unofficial patch from https://github.com/s3ql/s3ql/issues/355, needed because I'm also with OVH swift provider, but looking at the stack trace, I'm not sure if it is relevant here ?

I tried clearing the cache, running fsck (ok), but all to no avail, it still crashes as soon as one upload takes place.

To be thorough, I also downgraded to the 5.1.3 version, just in case (as I see that the user in issue 355 was on this specific version).

I'm trying to suspect that my metadata are corrupted beyond repair, as it is the only common point between my debian vs docker tests ?

Here the log, with 5.1.3, patch applied (so line number are a little bit off) :

```
2024-07-01 22:20:04.449 946:MainThread s3ql.mount.determine_threads: Using 10 upload threads.
2024-07-01 22:20:04.449 946:MainThread s3ql.mount.main: Autodetected 1048514 file descriptors available for cache entries
2024-07-01 22:20:06.806 946:MainThread s3ql.mount.get_metadata: Using cached metadata.
2024-07-01 22:20:06.811 946:MainThread s3ql.mount.main_async: Mounting swiftks://auth.cloud.ovh.net/GRA:CloudData/ at /data...
2024-07-01 22:21:12.768 946:Thread-10 (_upload_loop) s3ql.mount.exchook: Unhandled exception in thread, terminating
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/s3ql-5.1.3-py3.11-linux-x86_64.egg/s3ql/mount.py", line 72, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/site-packages/s3ql-5.1.3-py3.11-linux-x86_64.egg/s3ql/block_cache.py", line 322, in _upload_loop
    self._do_upload(*tmp)
  File "/usr/lib/python3.11/site-packages/s3ql-5.1.3-py3.11-linux-x86_64.egg/s3ql/block_cache.py", line 377, in _do_upload
    obj_size = backend.write_fh('s3ql_data_%d' % obj_id, el)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/s3ql-5.1.3-py3.11-linux-x86_64.egg/s3ql/backends/comprenc.py", line 279, in write_fh
    return self.backend.write_fh(key, fh, meta_raw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/s3ql-5.1.3-py3.11-linux-x86_64.egg/s3ql/backends/swift.py", line 464, in write_fh
    fh.seek(0, os.SEEK_END)
TypeError: CacheEntry.seek() takes 2 positional arguments but 3 were given
2024-07-01 22:21:12.772 946:Thread-9 (_upload_loop) s3ql.mount.exchook: Unhandled exception in thread, terminating
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/s3ql-5.1.3-py3.11-linux-x86_64.egg/s3ql/mount.py", line 72, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/site-packages/s3ql-5.1.3-py3.11-linux-x86_64.egg/s3ql/block_cache.py", line 322, in _upload_loop
    self._do_upload(*tmp)
  File "/usr/lib/python3.11/site-packages/s3ql-5.1.3-py3.11-linux-x86_64.egg/s3ql/block_cache.py", line 377, in _do_upload
    obj_size = backend.write_fh('s3ql_data_%d' % obj_id, el)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/s3ql-5.1.3-py3.11-linux-x86_64.egg/s3ql/backends/comprenc.py", line 279, in write_fh
    return self.backend.write_fh(key, fh, meta_raw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/s3ql-5.1.3-py3.11-linux-x86_64.egg/s3ql/backends/swift.py", line 464, in write_fh
    fh.seek(0, os.SEEK_END)
TypeError: CacheEntry.seek() takes 2 positional arguments but 3 were given
```

I would be very grateful if someone has an idea.

**Comment by dalgwen** [comment]
Ah, after several stack errors with "2 positional arguments but 3 were given", I just saw that I got a slightly different one just after  :

```
TypeError: CacheEntry.seek() takes 2 positional arguments but 3 were given
2024-07-01 22:21:17.851 946:MainThread s3ql.block_cache.destroy: Unable to flush cache, no upload threads left alive
2024-07-01 22:21:22.863 946:MainThread __main__.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/s3ql-5.1.3-py3.11-linux-x86_64.egg/s3ql/mount.py", line 317, in main_async
    (exc_inst, exc_tb) = exc_info
    ^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/mount.s3ql", line 33, in <module>
    sys.exit(load_entry_point('s3ql==5.1.3', 'console_scripts', 'mount.s3ql')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/s3ql-5.1.3-py3.11-linux-x86_64.egg/s3ql/mount.py", line 149, in main
    trio.run(main_async, options, stdout_log_handler)
  File "/usr/lib/python3.11/site-packages/trio/_core/_run.py", line 2251, in run
    raise runner.main_task_outcome.error
  File "/usr/lib/python3.11/site-packages/s3ql-5.1.3-py3.11-linux-x86_64.egg/s3ql/mount.py", line 218, in main_async
    async with AsyncExitStack() as cm:
  File "/usr/lib/python3.11/contextlib.py", line 733, in __aexit__
    raise exc_details[1]
  File "/usr/lib/python3.11/contextlib.py", line 716, in __aexit__
    cb_suppress = await cb(*exc_details)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/contextlib.py", line 621, in _exit_wrapper
    await callback(*args, **kwds)
  File "/usr/lib/python3.11/site-packages/s3ql-5.1.3-py3.11-linux-x86_64.egg/s3ql/block_cache.py", line 303, in destroy
    os.rmdir(self.path)
OSError: [Errno 39] Directory not empty: '/cache/swiftks:=2F=2Fauth.cloud.ovh.net=2FGRA:CloudData=2F-cache'

```

**Comment by Nikratio** [comment]
Could you post the error message that you get when using the newest version with no custom patches?

**Comment by dalgwen** [comment]
Thanks for your quick reply.

Of course, here it is : 

`2024-07-02 07:36:10.576 958:MainThread s3ql.mount.determine_threads: Using 10 upload threads.
2024-07-02 07:36:10.576 958:MainThread s3ql.mount.main: Autodetected 1048514 file descriptors available for cache entries
2024-07-02 07:36:12.637 958:MainThread s3ql.mount.get_metadata: Using cached metadata.
2024-07-02 07:36:12.642 958:MainThread s3ql.block_cache.__init__: Loaded 0 entries from cache
2024-07-02 07:36:12.642 958:MainThread s3ql.mount.main_async: Mounting swiftks://auth.cloud.ovh.net/GRA:CloudData/ at /data...
2024-07-02 07:36:38.105 958:Thread-10 (_upload_loop) s3ql.mount.exchook: Unhandled exception in thread, terminating
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/mount.py", line 72, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/block_cache.py", line 322, in _upload_loop
    self._do_upload(*tmp)
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/block_cache.py", line 377, in _do_upload
    obj_size = backend.write_fh('s3ql_data_%d' % obj_id, el)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/backends/comprenc.py", line 279, in write_fh
    return self.backend.write_fh(key, fh, meta_raw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/backends/swift.py", line 455, in write_fh
    fh.seek(0, os.SEEK_END)
TypeError: CacheEntry.seek() takes 2 positional arguments but 3 were given
2024-07-02 07:36:38.109 958:Thread-9 (_upload_loop) s3ql.mount.exchook: Unhandled exception in thread, terminating
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/mount.py", line 72, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/block_cache.py", line 322, in _upload_loop
    self._do_upload(*tmp)
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/block_cache.py", line 377, in _do_upload
    obj_size = backend.write_fh('s3ql_data_%d' % obj_id, el)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/backends/comprenc.py", line 279, in write_fh
    return self.backend.write_fh(key, fh, meta_raw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/backends/swift.py", line 455, in write_fh
    fh.seek(0, os.SEEK_END)
TypeError: CacheEntry.seek() takes 2 positional arguments but 3 were given
2024-07-02 07:36:38.112 958:Thread-8 (_upload_loop) s3ql.mount.exchook: Unhandled exception in thread, terminating
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/mount.py", line 72, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/block_cache.py", line 322, in _upload_loop
    self._do_upload(*tmp)
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/block_cache.py", line 377, in _do_upload
    obj_size = backend.write_fh('s3ql_data_%d' % obj_id, el)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/backends/comprenc.py", line 279, in write_fh
    return self.backend.write_fh(key, fh, meta_raw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/backends/swift.py", line 455, in write_fh
    fh.seek(0, os.SEEK_END)
TypeError: CacheEntry.seek() takes 2 positional arguments but 3 were given
2024-07-02 07:36:38.125 958:Thread-10 (_upload_loop) __main__.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/mount.py", line 72, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/block_cache.py", line 322, in _upload_loop
    self._do_upload(*tmp)
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/block_cache.py", line 377, in _do_upload
    obj_size = backend.write_fh('s3ql_data_%d' % obj_id, el)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/backends/comprenc.py", line 279, in write_fh
    return self.backend.write_fh(key, fh, meta_raw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/backends/swift.py", line 455, in write_fh
    fh.seek(0, os.SEEK_END)
TypeError: CacheEntry.seek() takes 2 positional arguments but 3 were given
2024-07-02 07:36:38.125 958:Thread-9 (_upload_loop) __main__.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/mount.py", line 72, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/block_cache.py", line 322, in _upload_loop
    self._do_upload(*tmp)
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/block_cache.py", line 377, in _do_upload
    obj_size = backend.write_fh('s3ql_data_%d' % obj_id, el)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/backends/comprenc.py", line 279, in write_fh
    return self.backend.write_fh(key, fh, meta_raw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/backends/swift.py", line 455, in write_fh
    fh.seek(0, os.SEEK_END)
TypeError: CacheEntry.seek() takes 2 positional arguments but 3 were given
2024-07-02 07:36:38.125 958:MainThread s3ql.mount.unmount: Unmounting file system...
2024-07-02 07:36:38.138 958:Thread-7 (_upload_loop) s3ql.mount.exchook: Unhandled top-level exception during shutdown (will not be re-raised)
2024-07-02 07:36:38.138 958:Thread-7 (_upload_loop) __main__.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/mount.py", line 72, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/block_cache.py", line 322, in _upload_loop
    self._do_upload(*tmp)
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/block_cache.py", line 377, in _do_upload
    obj_size = backend.write_fh('s3ql_data_%d' % obj_id, el)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/backends/comprenc.py", line 279, in write_fh
    return self.backend.write_fh(key, fh, meta_raw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/backends/swift.py", line 455, in write_fh
    fh.seek(0, os.SEEK_END)
TypeError: CacheEntry.seek() takes 2 positional arguments but 3 were given
2024-07-02 07:36:38.143 958:Thread-6 (_upload_loop) s3ql.mount.exchook: Unhandled top-level exception during shutdown (will not be re-raised)
2024-07-02 07:36:38.143 958:Thread-6 (_upload_loop) __main__.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/mount.py", line 72, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/block_cache.py", line 322, in _upload_loop
    self._do_upload(*tmp)
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/block_cache.py", line 377, in _do_upload
    obj_size = backend.write_fh('s3ql_data_%d' % obj_id, el)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/backends/comprenc.py", line 279, in write_fh
    return self.backend.write_fh(key, fh, meta_raw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/backends/swift.py", line 455, in write_fh
    fh.seek(0, os.SEEK_END)
TypeError: CacheEntry.seek() takes 2 positional arguments but 3 were given
2024-07-02 07:36:38.149 958:Thread-5 (_upload_loop) s3ql.mount.exchook: Unhandled top-level exception during shutdown (will not be re-raised)
2024-07-02 07:36:38.149 958:Thread-5 (_upload_loop) __main__.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/mount.py", line 72, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/block_cache.py", line 322, in _upload_loop
    self._do_upload(*tmp)
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/block_cache.py", line 377, in _do_upload
    obj_size = backend.write_fh('s3ql_data_%d' % obj_id, el)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/backends/comprenc.py", line 279, in write_fh
    return self.backend.write_fh(key, fh, meta_raw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/backends/swift.py", line 455, in write_fh
    fh.seek(0, os.SEEK_END)
TypeError: CacheEntry.seek() takes 2 positional arguments but 3 were given
2024-07-02 07:36:38.157 958:Thread-4 (_upload_loop) s3ql.mount.exchook: Unhandled top-level exception during shutdown (will not be re-raised)
2024-07-02 07:36:38.157 958:Thread-4 (_upload_loop) __main__.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/mount.py", line 72, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/block_cache.py", line 322, in _upload_loop
    self._do_upload(*tmp)
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/block_cache.py", line 377, in _do_upload
    obj_size = backend.write_fh('s3ql_data_%d' % obj_id, el)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/backends/comprenc.py", line 279, in write_fh
    return self.backend.write_fh(key, fh, meta_raw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/backends/swift.py", line 455, in write_fh
    fh.seek(0, os.SEEK_END)
TypeError: CacheEntry.seek() takes 2 positional arguments but 3 were given
2024-07-02 07:36:38.160 958:Thread-2 (_upload_loop) s3ql.mount.exchook: Unhandled top-level exception during shutdown (will not be re-raised)
2024-07-02 07:36:38.161 958:Thread-2 (_upload_loop) __main__.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/mount.py", line 72, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/block_cache.py", line 322, in _upload_loop
    self._do_upload(*tmp)
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/block_cache.py", line 377, in _do_upload
    obj_size = backend.write_fh('s3ql_data_%d' % obj_id, el)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/backends/comprenc.py", line 279, in write_fh
    return self.backend.write_fh(key, fh, meta_raw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/backends/swift.py", line 455, in write_fh
    fh.seek(0, os.SEEK_END)
TypeError: CacheEntry.seek() takes 2 positional arguments but 3 were given
2024-07-02 07:36:38.165 958:Thread-3 (_upload_loop) s3ql.mount.exchook: Unhandled top-level exception during shutdown (will not be re-raised)
2024-07-02 07:36:38.166 958:Thread-3 (_upload_loop) __main__.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/mount.py", line 72, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/block_cache.py", line 322, in _upload_loop
    self._do_upload(*tmp)
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/block_cache.py", line 377, in _do_upload
    obj_size = backend.write_fh('s3ql_data_%d' % obj_id, el)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/backends/comprenc.py", line 279, in write_fh
    return self.backend.write_fh(key, fh, meta_raw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/backends/swift.py", line 455, in write_fh
    fh.seek(0, os.SEEK_END)
TypeError: CacheEntry.seek() takes 2 positional arguments but 3 were given
2024-07-02 07:36:38.170 958:Thread-1 (_upload_loop) s3ql.mount.exchook: Unhandled top-level exception during shutdown (will not be re-raised)
2024-07-02 07:36:38.171 958:Thread-1 (_upload_loop) __main__.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/mount.py", line 72, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/block_cache.py", line 322, in _upload_loop
    self._do_upload(*tmp)
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/block_cache.py", line 377, in _do_upload
    obj_size = backend.write_fh('s3ql_data_%d' % obj_id, el)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/backends/comprenc.py", line 279, in write_fh
    return self.backend.write_fh(key, fh, meta_raw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/backends/swift.py", line 455, in write_fh
    fh.seek(0, os.SEEK_END)
TypeError: CacheEntry.seek() takes 2 positional arguments but 3 were given
2024-07-02 07:36:43.178 958:MainThread s3ql.block_cache.destroy: Unable to flush cache, no upload threads left alive
2024-07-02 07:36:48.201 958:MainThread __main__.excepthook: Uncaught top-level exception:
  + Exception Group Traceback (most recent call last):
  |   File "/usr/bin/mount.s3ql", line 33, in <module>
  |     sys.exit(load_entry_point('s3ql==5.2.0', 'console_scripts', 'mount.s3ql')())
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/mount.py", line 149, in main
  |     trio.run(main_async, options, stdout_log_handler)
  |   File "/usr/lib/python3.11/site-packages/trio/_core/_run.py", line 2288, in run
  |     raise runner.main_task_outcome.error
  |   File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/mount.py", line 217, in main_async
  |     async with trio.open_nursery() as nursery:
  |   File "/usr/lib/python3.11/site-packages/trio/_core/_run.py", line 954, in __aexit__
  |     raise combined_error_from_nursery
  | ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/mount.py", line 317, in main_async
    |     (exc_inst, exc_tb) = exc_info
    |     ^^^^^^^^^^^^^^^^^^
    | ValueError: too many values to unpack (expected 2)
    |
    | During handling of the above exception, another exception occurred:
    |
    | Traceback (most recent call last):
    |   File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/mount.py", line 218, in main_async
    |     async with AsyncExitStack() as cm:
    |   File "/usr/lib/python3.11/contextlib.py", line 745, in __aexit__
    |     raise exc_details[1]
    |   File "/usr/lib/python3.11/contextlib.py", line 728, in __aexit__
    |     cb_suppress = await cb(*exc_details)
    |                   ^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/contextlib.py", line 633, in _exit_wrapper
    |     await callback(*args, **kwds)
    |   File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/block_cache.py", line 303, in destroy
    |     os.rmdir(self.path)
    | OSError: [Errno 39] Directory not empty: '/cache/swiftks:=2F=2Fauth.cloud.ovh.net=2FGRA:CloudData=2F-cache'
    +------------------------------------
`

**Comment by Nikratio** [comment]
Hmm. This looks like a bug in the code. `CacheEntry.seek()` does not take a `whence` argument, yet the Swift backend's `write_fh` method tries to call it with `whence=os.SEEK_END`.

What I do not understand is why this is passing unit test and working for most people, since e.g. the gs backend does the same thing.

**Comment by Nikratio** [comment]
Moreover, the code seems wrong even if `fh.seek` was working: we should be setting `len_ = fh.tell() - off` rather than `len_ = fh.tell()`.

How did this ever work for anyone? :-)

**Comment by Nikratio** [comment]
Ah, I have a theory. In most cases, `ComprencBackend` will swap the CacheEntry object for a BytesIO object, which has the correct `seek` method. 

Perhaps you are using neither compression nor encryption, and therefore ComprencBackend is just passing through the CacheEntry? Still, I'm surprised that this isn't covered by the unit tests or anyone else has encountered it so far.

**Comment by dalgwen** [comment]
> Ah, I have a theory. In most cases, `ComprencBackend` will swap the CacheEntry object for a BytesIO object, which has the correct `seek` method.
> 
> Perhaps you are using neither compression nor encryption, and therefore ComprencBackend is just passing through the CacheEntry? Still, I'm surprised that this isn't covered by the unit tests or anyone else has encountered it so far.

Yes, exactly ! No compression, no encryption.
It seems you are onto the source of my issue. Tell me if I can be of some help 👍

**Comment by Nikratio** [comment]
Without having looked into it too much, this patch might help:

```patch
diff --git a/src/s3ql/block_cache.py b/src/s3ql/block_cache.py
index a4b55fd..f506484 100644
--- a/src/s3ql/block_cache.py
+++ b/src/s3ql/block_cache.py
@@ -86,9 +86,9 @@ class CacheEntry:
     def flush(self):
         self.fh.flush()
 
-    def seek(self, off):
-        if self.pos != off:
-            self.fh.seek(off)
+    def seek(self, off, whence=None):
+        if whence is not None or self.pos != off:
+            self.fh.seek(off, whence)
             self.pos = off
 
     def tell(self):
```

**Comment by dalgwen** [comment]
Fantastic !
It seems to work.

Again, many thanks for your reactivity ! I know that open source project can be demanding and it is hard for contributors to cope with free time. So, I'm all the more grateful.

Anyway, this issue is resolved for me. I don't close it myself in case you want to keep it until the fix is properly merged.
