### ISSUE TITLE
StateError when uploading metadata using Swift

### ISSUE THREAD

**Issue by dalgwen** [s3ql/s3ql#359]
Hello again.
I'm really sorry to raise another issue 😅

After the fix with my no encryption + no compression setup, I thought it was definitely OK. But unfortunately it crashes after several hours, when the task scheduler tries to upload metadata.
Happens two times since yesterday, so it seems consistent.

Here are the logs (5.2.0, fix to block_cache from #358 and OVH/swift fix from #355 both applied)

```
2024-07-02 17:58:26.525 948:MainThread s3ql.mount.determine_threads: Using 10 upload threads.
2024-07-02 17:58:26.525 948:MainThread s3ql.mount.main: Autodetected 1048514 file descriptors available for cache entries
2024-07-02 17:58:29.088 948:MainThread s3ql.mount.get_metadata: Using cached metadata.
2024-07-02 17:58:29.093 948:MainThread s3ql.block_cache.__init__: Loaded 0 entries from cache
2024-07-02 17:58:29.094 948:MainThread s3ql.mount.main_async: Mounting swiftks://auth.cloud.ovh.net/GRA:CloudData/ at /data...
2024-07-02 23:58:29.865 948:None from metadata-upload-task s3ql.database.upload_metadata: Uploading metadata...
2024-07-02 23:58:31.135 948:MainThread s3ql.mount.unmount: Unmounting file system...
[....]
2024-07-02 23:58:31.167 948:MainThread __main__.excepthook: Uncaught top-level exception:
  + Exception Group Traceback (most recent call last):
  |   File "/usr/bin/mount.s3ql", line 33, in <module>
  |     sys.exit(load_entry_point('s3ql==5.2.0', 'console_scripts', 'mount.s3ql')())
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/mount.py", line 149, in main
  |     trio.run(main_async, options, stdout_log_handler)
  |   File "/usr/lib/python3.11/site-packages/trio/_core/_run.py", line 2288, in run
  |     raise runner.main_task_outcome.error
  |   File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/mount.py", line 217, in main_async
  |     async with trio.open_nursery() as nursery:
  |   File "/usr/lib/python3.11/site-packages/trio/_core/_run.py", line 954, in __aexit__
  |     raise combined_error_from_nursery
  | ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/mount.py", line 683, in run
    |     await trio.to_thread.run_sync(
    |   File "/usr/lib/python3.11/site-packages/trio/_threads.py", line 471, in to_thread_run_sync
    |     return msg_from_thread.unwrap()
    |            ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/site-packages/outcome/_impl.py", line 213, in unwrap
    |     raise captured_error
    |   File "/usr/lib/python3.11/site-packages/trio/_threads.py", line 397, in do_release_then_return_result
    |     return result.unwrap()
    |            ^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/site-packages/outcome/_impl.py", line 213, in unwrap
    |     raise captured_error
    |   File "/usr/lib/python3.11/site-packages/trio/_threads.py", line 416, in worker_fn
    |     ret = context.run(sync_fn, *args)
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/database.py", line 668, in upload_metadata
    |     backend.write_fh(obj, fh, len_=blocksize)
    |   File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/backends/comprenc.py", line 279, in write_fh
    |     return self.backend.write_fh(key, fh, meta_raw)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/backends/swift.py", line 464, in write_fh
    |     return self._write_fh(key, fh, off, len_, metadata or {})
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/backends/common.py", line 114, in wrapped
    |     return method(*a, **kw)
    |            ^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/backends/swift.py", line 474, in _write_fh
    |     resp = self._do_request(
    |            ^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/backends/swift.py", line 273, in _do_request
    |     resp = self._do_request_inner(
    |            ^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/backends/swift.py", line 346, in _do_request_inner
    |     resp = self.conn.read_response()
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/http.py", line 735, in read_response
    |     return eval_coroutine(self.co_read_response())
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/http.py", line 1388, in eval_coroutine
    |     next(it)
    |   File "/usr/lib/python3.11/site-packages/s3ql-5.2.0-py3.11-linux-x86_64.egg/s3ql/http.py", line 750, in co_read_response
    |     raise StateError('No pending requests')
    | s3ql.http.StateError: No pending requests
    +------------------------------------
```

Is it still something from my no encryption / no compression case ?

Again, many thanks for your support.

**Comment by Nikratio** [comment]
(Stripped your report to the relevant parts)

This feels like a bug in the Swift backend... or do you get the same problem with other backends?

**Comment by dalgwen** [comment]
> do you get the same problem with other backends?

In fact, I only have this new problem with my main bucket.
I just tested, and a newly created one (swift backend, no encryption,  no compression) can upload its metadata without crashing.

It seems that only my main bucket has this issue...
I'm hesitating. Should I try to rebuild a new bucket, by rsyncing every files from the old one to a new one ?

**Comment by Nikratio** [comment]
It's near impossible for this to depend on which bucket you are using as long as the backend is the same. So I'd encourage you to test a few more times, I think this was pure chance.
