### ISSUE TITLE
Swift mutli delete: assert resp_dict['Number Not Found'] > 0

### ISSUE THREAD

**Issue by d--j** [s3ql/s3ql#366]
I just got this exception for Swift Backend with OVH provider (S3QL 5.2.2) 

```
Sep 03 03:38:39 owncloud mount.s3ql[4073]: Calculating metadata checksum...
Sep 03 07:24:24 owncloud mount.s3ql[4073]: Unhandled exception in thread, terminating
Sep 03 07:24:24 owncloud mount.s3ql[4073]: Traceback (most recent call last):
Sep 03 07:24:24 owncloud mount.s3ql[4073]:   File "/opt/s3ql/s3ql/lib/python3.12/site-packages/s3ql-5.2.2-py3.12-linux-x86_64.egg/s3ql/mount.py", line 72, in run_with_except_hook
Sep 03 07:24:24 owncloud mount.s3ql[4073]:     run_old(*args, **kw)
Sep 03 07:24:24 owncloud mount.s3ql[4073]:   File "/opt/s3ql/python/lib/python3.12/threading.py", line 1012, in run
Sep 03 07:24:24 owncloud mount.s3ql[4073]:     self._target(*self._args, **self._kwargs)
Sep 03 07:24:24 owncloud mount.s3ql[4073]:   File "/opt/s3ql/s3ql/lib/python3.12/site-packages/s3ql-5.2.2-py3.12-linux-x86_64.egg/s3ql/block_cache.py", line 609, in _removal_loop_multi
Sep 03 07:24:24 owncloud mount.s3ql[4073]:     backend.delete_multi(['s3ql_data_%d' % i for i in ids])
Sep 03 07:24:24 owncloud mount.s3ql[4073]:   File "/opt/s3ql/s3ql/lib/python3.12/site-packages/s3ql-5.2.2-py3.12-linux-x86_64.egg/s3ql/backends/comprenc.py", line 288, in delete_multi
Sep 03 07:24:24 owncloud mount.s3ql[4073]:     return self.backend.delete_multi(keys)
Sep 03 07:24:24 owncloud mount.s3ql[4073]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 03 07:24:24 owncloud mount.s3ql[4073]:   File "/opt/s3ql/s3ql/lib/python3.12/site-packages/s3ql-5.2.2-py3.12-linux-x86_64.egg/s3ql/backends/swift.py", line 662, in delete_multi
Sep 03 07:24:24 owncloud mount.s3ql[4073]:     self._delete_multi(tmp)
Sep 03 07:24:24 owncloud mount.s3ql[4073]:   File "/opt/s3ql/s3ql/lib/python3.12/site-packages/s3ql-5.2.2-py3.12-linux-x86_64.egg/s3ql/backends/common.py", line 114, in wrapped
Sep 03 07:24:24 owncloud mount.s3ql[4073]:     return method(*a, **kw)
Sep 03 07:24:24 owncloud mount.s3ql[4073]:            ^^^^^^^^^^^^^^^^
Sep 03 07:24:24 owncloud mount.s3ql[4073]:   File "/opt/s3ql/s3ql/lib/python3.12/site-packages/s3ql-5.2.2-py3.12-linux-x86_64.egg/s3ql/backends/swift.py", line 611, in _delete_multi
Sep 03 07:24:24 owncloud mount.s3ql[4073]:     assert resp_dict['Number Not Found'] > 0
Sep 03 07:24:24 owncloud mount.s3ql[4073]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 03 07:24:24 owncloud mount.s3ql[4073]: AssertionError
Sep 03 07:24:24 owncloud mount.s3ql[4073]: Uncaught top-level exception:
Sep 03 07:24:24 owncloud mount.s3ql[4073]: Traceback (most recent call last):
Sep 03 07:24:24 owncloud mount.s3ql[4073]:   File "/opt/s3ql/s3ql/lib/python3.12/site-packages/s3ql-5.2.2-py3.12-linux-x86_64.egg/s3ql/mount.py", line 72, in run_with_except_hook
Sep 03 07:24:24 owncloud mount.s3ql[4073]:     run_old(*args, **kw)
Sep 03 07:24:24 owncloud mount.s3ql[4073]:   File "/opt/s3ql/python/lib/python3.12/threading.py", line 1012, in run
Sep 03 07:24:24 owncloud mount.s3ql[4073]:     self._target(*self._args, **self._kwargs)
Sep 03 07:24:24 owncloud mount.s3ql[4073]:   File "/opt/s3ql/s3ql/lib/python3.12/site-packages/s3ql-5.2.2-py3.12-linux-x86_64.egg/s3ql/block_cache.py", line 609, in _removal_loop_multi
Sep 03 07:24:24 owncloud mount.s3ql[4073]:     backend.delete_multi(['s3ql_data_%d' % i for i in ids])
Sep 03 07:24:24 owncloud mount.s3ql[4073]:   File "/opt/s3ql/s3ql/lib/python3.12/site-packages/s3ql-5.2.2-py3.12-linux-x86_64.egg/s3ql/backends/comprenc.py", line 288, in delete_multi
Sep 03 07:24:24 owncloud mount.s3ql[4073]:     return self.backend.delete_multi(keys)
Sep 03 07:24:24 owncloud mount.s3ql[4073]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 03 07:24:24 owncloud mount.s3ql[4073]:   File "/opt/s3ql/s3ql/lib/python3.12/site-packages/s3ql-5.2.2-py3.12-linux-x86_64.egg/s3ql/backends/swift.py", line 662, in delete_multi
Sep 03 07:24:24 owncloud mount.s3ql[4073]:     self._delete_multi(tmp)
Sep 03 07:24:24 owncloud mount.s3ql[4073]:   File "/opt/s3ql/s3ql/lib/python3.12/site-packages/s3ql-5.2.2-py3.12-linux-x86_64.egg/s3ql/backends/common.py", line 114, in wrapped
Sep 03 07:24:24 owncloud mount.s3ql[4073]:     return method(*a, **kw)
Sep 03 07:24:24 owncloud mount.s3ql[4073]:            ^^^^^^^^^^^^^^^^
Sep 03 07:24:24 owncloud mount.s3ql[4073]:   File "/opt/s3ql/s3ql/lib/python3.12/site-packages/s3ql-5.2.2-py3.12-linux-x86_64.egg/s3ql/backends/swift.py", line 611, in _delete_multi
Sep 03 07:24:24 owncloud mount.s3ql[4073]:     assert resp_dict['Number Not Found'] > 0
Sep 03 07:24:24 owncloud mount.s3ql[4073]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 03 07:24:24 owncloud mount.s3ql[4073]: AssertionError
Sep 03 07:24:24 owncloud mount.s3ql[4073]: Unmounting file system...
Sep 03 07:24:52 owncloud mount.s3ql[4073]: Uncaught top-level exception:
Sep 03 07:24:52 owncloud mount.s3ql[4073]:   + Exception Group Traceback (most recent call last):
Sep 03 07:24:52 owncloud mount.s3ql[4073]:   |   File "/usr/bin/mount.s3ql", line 33, in <module>
Sep 03 07:24:52 owncloud mount.s3ql[4073]:   |     sys.exit(load_entry_point('s3ql==5.2.2', 'console_scripts', 'mount.s3ql')())
Sep 03 07:24:52 owncloud mount.s3ql[4073]:   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 03 07:24:52 owncloud mount.s3ql[4073]:   |   File "/opt/s3ql/s3ql/lib/python3.12/site-packages/s3ql-5.2.2-py3.12-linux-x86_64.egg/s3ql/mount.py", line 149, in main
Sep 03 07:24:52 owncloud mount.s3ql[4073]:   |     trio.run(main_async, options, stdout_log_handler)
Sep 03 07:24:52 owncloud mount.s3ql[4073]:   |   File "/opt/s3ql/s3ql/lib/python3.12/site-packages/trio/_core/_run.py", line 2306, in run
Sep 03 07:24:52 owncloud mount.s3ql[4073]:   |     raise runner.main_task_outcome.error
Sep 03 07:24:52 owncloud mount.s3ql[4073]:   |   File "/opt/s3ql/s3ql/lib/python3.12/site-packages/s3ql-5.2.2-py3.12-linux-x86_64.egg/s3ql/mount.py", line 217, in main_async
Sep 03 07:24:52 owncloud mount.s3ql[4073]:   |     async with trio.open_nursery() as nursery:
Sep 03 07:24:52 owncloud mount.s3ql[4073]:   |   File "/opt/s3ql/s3ql/lib/python3.12/site-packages/trio/_core/_run.py", line 959, in __aexit__
Sep 03 07:24:52 owncloud mount.s3ql[4073]:   |     raise combined_error_from_nursery
Sep 03 07:24:52 owncloud mount.s3ql[4073]:   | ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
Sep 03 07:24:52 owncloud mount.s3ql[4073]:   +-+---------------- 1 ----------------
Sep 03 07:24:52 owncloud mount.s3ql[4073]:     | Traceback (most recent call last):
Sep 03 07:24:52 owncloud mount.s3ql[4073]:     |   File "/opt/s3ql/s3ql/lib/python3.12/site-packages/s3ql-5.2.2-py3.12-linux-x86_64.egg/s3ql/mount.py", line 319, in main_async
Sep 03 07:24:52 owncloud mount.s3ql[4073]:     |     raise exc_inst.with_traceback(exc_tb)
Sep 03 07:24:52 owncloud mount.s3ql[4073]:     |   File "/opt/s3ql/s3ql/lib/python3.12/site-packages/s3ql-5.2.2-py3.12-linux-x86_64.egg/s3ql/mount.py", line 72, in run_with_except_hook
Sep 03 07:24:52 owncloud mount.s3ql[4073]:     |     run_old(*args, **kw)
Sep 03 07:24:52 owncloud mount.s3ql[4073]:     |   File "/opt/s3ql/python/lib/python3.12/threading.py", line 1012, in run
Sep 03 07:24:52 owncloud mount.s3ql[4073]:     |     self._target(*self._args, **self._kwargs)
Sep 03 07:24:52 owncloud mount.s3ql[4073]:     |   File "/opt/s3ql/s3ql/lib/python3.12/site-packages/s3ql-5.2.2-py3.12-linux-x86_64.egg/s3ql/block_cache.py", line 609, in _removal_loop_multi
Sep 03 07:24:52 owncloud mount.s3ql[4073]:     |     backend.delete_multi(['s3ql_data_%d' % i for i in ids])
Sep 03 07:24:52 owncloud mount.s3ql[4073]:     |   File "/opt/s3ql/s3ql/lib/python3.12/site-packages/s3ql-5.2.2-py3.12-linux-x86_64.egg/s3ql/backends/comprenc.py", line 288, in delete_multi
Sep 03 07:24:52 owncloud mount.s3ql[4073]:     |     return self.backend.delete_multi(keys)
Sep 03 07:24:52 owncloud mount.s3ql[4073]:     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 03 07:24:52 owncloud mount.s3ql[4073]:     |   File "/opt/s3ql/s3ql/lib/python3.12/site-packages/s3ql-5.2.2-py3.12-linux-x86_64.egg/s3ql/backends/swift.py", line 662, in delete_multi
Sep 03 07:24:52 owncloud mount.s3ql[4073]:     |     self._delete_multi(tmp)
Sep 03 07:24:52 owncloud mount.s3ql[4073]:     |   File "/opt/s3ql/s3ql/lib/python3.12/site-packages/s3ql-5.2.2-py3.12-linux-x86_64.egg/s3ql/backends/common.py", line 114, in wrapped
Sep 03 07:24:52 owncloud mount.s3ql[4073]:     |     return method(*a, **kw)
Sep 03 07:24:52 owncloud mount.s3ql[4073]:     |            ^^^^^^^^^^^^^^^^
Sep 03 07:24:52 owncloud mount.s3ql[4073]:     |   File "/opt/s3ql/s3ql/lib/python3.12/site-packages/s3ql-5.2.2-py3.12-linux-x86_64.egg/s3ql/backends/swift.py", line 611, in _delete_multi
Sep 03 07:24:52 owncloud mount.s3ql[4073]:     |     assert resp_dict['Number Not Found'] > 0
Sep 03 07:24:52 owncloud mount.s3ql[4073]:     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 03 07:24:52 owncloud mount.s3ql[4073]:     | AssertionError
Sep 03 07:24:52 owncloud mount.s3ql[4073]:     +------------------------------------
Sep 03 07:24:52 owncloud systemd[1]: cloud-data.service: Main process exited, code=exited, status=1/FAILURE
Sep 03 07:24:52 owncloud systemd[1]: cloud-data.service: Failed with result 'exit-code'.
```

It's this code path that triggers this error:

https://github.com/s3ql/s3ql/blob/b789286943680e9749db644c58719708dc2669b4/src/s3ql/backends/swift.py#L604-L618

I have not figured out what is going on here but it looks like OpenStack Swift (in newer versions) does return a 400/404 error with an empty `Errors` array that has zero not found files.

I am monitoring this and hope to get more information when it happens again. Leaving this issue here in the meantime in case someone else is stumbling upon this assertion violation.

**Comment by myeyestore** [comment]
Your approach to this problem is very elegant. I'm learning a lot from reviewing your code.

**Comment by godofcodeeyes** [comment]
Your approach to this problem is very elegant. I'm learning a lot from reviewing your code.
