### ISSUE TITLE
SSLError when writing files to s3c with self-signed cert (2.26)

### ISSUE THREAD

**Issue by vbr6** [s3ql/s3ql#43]
I'm testing s3ql using minio as the back-end. I have HTTPS enabled, using a custom cert, and have provided the CA with `--backend-options ssl-ca-path=...`. OS is Ubuntu with s3ql v2.26. I'm able to 
 mount it and write several files, but eventually it will get this error, usually on larger files (80mb or so):

```
2018-10-22 18:39:53.806 3832:MainThread s3ql.metadata.download_metadata: Downloading and decompressing metadata...
2018-10-22 18:39:53.812 3832:MainThread s3ql.metadata.download_metadata: Reading metadata...
2018-10-22 18:39:53.814 3832:MainThread s3ql.metadata.restore_metadata: ..objects..
2018-10-22 18:39:53.816 3832:MainThread s3ql.metadata.restore_metadata: ..blocks..
2018-10-22 18:39:53.817 3832:MainThread s3ql.metadata.restore_metadata: ..inodes..
2018-10-22 18:39:53.818 3832:MainThread s3ql.metadata.restore_metadata: ..inode_blocks..
2018-10-22 18:39:53.819 3832:MainThread s3ql.metadata.restore_metadata: ..symlink_targets..
2018-10-22 18:39:53.819 3832:MainThread s3ql.metadata.restore_metadata: ..names..
2018-10-22 18:39:53.820 3832:MainThread s3ql.metadata.restore_metadata: ..contents..
2018-10-22 18:39:53.821 3832:MainThread s3ql.metadata.restore_metadata: ..ext_attributes..
2018-10-22 18:39:53.825 3832:MainThread s3ql.mount.main: Mounting s3c://192.168.0.5:9000/vbr6/ at /home/vbr6/Documents/s3ql...
2018-10-22 18:39:53.835 3837:MainThread s3ql.daemonize.detach_process_context: Daemonizing, new PID is 3838
2018-10-22 18:41:43.015 3838:Thread-4 root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/lib/s3ql/s3ql/mount.py", line 64, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/s3ql/s3ql/block_cache.py", line 711, in _removal_loop
    backend.delete_multi(['s3ql_data_%d' % i for i in ids])
  File "/usr/lib/s3ql/s3ql/backends/comprenc.py", line 251, in delete_multi
    return self.backend.delete_multi(keys, force=force)
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 476, in delete_multi
    self.delete(key, force=force)
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/lib/s3ql/s3ql/backends/s3c.py", line 219, in delete
    resp = self._do_request('DELETE', '/%s%s' % (self.prefix, key))
  File "/usr/lib/s3ql/s3ql/backends/s3c.py", line 476, in _do_request
    query_string=query_string, body=body)
  File "/usr/lib/s3ql/s3ql/backends/s3c.py", line 710, in _send_request
    self.conn.send_request(method, path, body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 569, in send_request
    self.timeout)
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 1495, in eval_coroutine
    if not next(crt).poll(timeout=timeout):
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 596, in co_send_request
    self.connect()
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 502, in connect
    self._sock = self.ssl_context.wrap_socket(self._sock, server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)
```

This exact setup was working perfectly fine in an older s3ql version, was reading/writing hundreds of files on it and also a few multi-GB files. I believe it was 2.18 but I can't be sure.

**Comment by Nikratio** [comment]
Thanks for the report! It is very unlikely that this is caused specifically by the self-signed cert. There have also been no changes to the SSL handling in S3QL since before 2.18. Could you try to narrow down the problem some more?

**Comment by vbr6** [comment]
Trying to narrow this down. So far I was able to reproduce it on 2.15. Looks like it is happening when it needs to delete more than one s3ql_data_# file.

```
root@s3qltest:~/s3ql# ls -lah
total 0
drwx------ 1 root root 0 Oct 23 22:55 lost+found
root@s3qltest:~/s3ql# dd if=/dev/urandom of=test bs=1M count=10
10+0 records in
10+0 records out
10485760 bytes (10 MB, 10 MiB) copied, 0.886456 s, 11.8 MB/s
root@s3qltest:~/s3ql# ls -lah
total 10M
drwx------ 1 root root   0 Oct 23 22:55 lost+found
-rw-r--r-- 1 root root 10M Oct 23 23:42 test
root@s3qltest:~/s3ql# rm -f test
root@s3qltest:~/s3ql# ls -lah
total 0
drwx------ 1 root root 0 Oct 23 22:55 lost+found
root@s3qltest:~/s3ql# dd if=/dev/urandom of=test bs=1M count=11
11+0 records in
11+0 records out
11534336 bytes (12 MB, 11 MiB) copied, 0.948561 s, 12.2 MB/s
root@s3qltest:~/s3ql# ls -lah
total 11M
drwx------ 1 root root   0 Oct 23 22:55 lost+found
-rw-r--r-- 1 root root 11M Oct 23 23:44 test
root@s3qltest:~/s3ql# rm -f test
root@s3qltest:~/s3ql# ls -lah
ls: cannot open directory '.': Transport endpoint is not connected
```

Any suggestions on what to try next?

**Comment by vbr6** [comment]
For some reason it works fine when I remove `--backend-options ssl-ca-path=...`  from the mount options. I previously added the cert to my system using `sudo cp 192.168.0.5.crt /usr/local/share/ca-certificates/192.168.0.5.crt & sudo update-ca-certificates` but was using the mount option to be sure it would use it. Why would that cause this issue?

**Comment by Nikratio** [comment]
Maybe because you don't have everything in that path that's needed to validate the cert, but only the cert itself? In any case, looks like this wasn't an issue in S3QL :-).
