### ISSUE TITLE
Mount error with Google Storage

### ISSUE THREAD

**Issue by kobuki** [s3ql/s3ql#47]
I'm seeing the following error when trying to mount a GS based s3ql FS. Debian 9.5 amd64, kernel 4.16.16-2~bpo9+1. Used command below. If you need additional info, please let me know.

`# mount.s3ql --allow-other gs://xxx-backup-1/backup1/ /mnt/gs/`

```
2018-10-27 18:07:35.718 30466:MainThread s3ql.mount.determine_threads: Using 4 upload threads.
2018-10-27 18:07:35.719 30466:MainThread s3ql.mount.main: Autodetected 1048532 file descriptors available for cache entries
2018-10-27 18:07:35.731 30466:MainThread s3ql.backends.gs._get_access_token: Requesting new access token
2018-10-27 18:07:36.597 30466:MainThread s3ql.mount.get_metadata: Using cached metadata.
2018-10-27 18:07:36.610 30466:MainThread s3ql.mount.main: Setting cache size to 3987 MB
2018-10-27 18:07:36.610 30466:MainThread s3ql.mount.main: Mounting gs://xxx-backup-1/backup1/ at /mnt/gs...
2018-10-27 18:07:36.643 30471:MainThread s3ql.daemonize.detach_process_context: Daemonizing, new PID is 30472
2018-10-27 18:07:36.827 30472:MainThread s3ql.mount.unmount: Unmounting file system...
2018-10-27 18:07:36.827 30472:MainThread root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/local/bin/mount.s3ql", line 11, in <module>
    load_entry_point('s3ql==2.31', 'console_scripts', 'mount.s3ql')()
  File "/usr/local/lib/python3.5/dist-packages/s3ql-2.31-py3.5-linux-x86_64.egg/s3ql/mount.py", line 210, in main
    sd_notify('READY=1')
  File "/usr/local/lib/python3.5/dist-packages/systemd/daemon.py", line 39, in notify
    raise TypeError("state must be an instance of Notification")
TypeError: state must be an instance of Notification
```

**Comment by Nikratio** [comment]
Thanks for the report! You need to install the systemd module that comes with systemd, not the third-party one (that sadly has been called systemd as well).

**Comment by kobuki** [comment]
Thanks. `apt-get install python3-systemd` did the trick.

On another note, I can open another ticket if needed, but is it normal that eg. `ls -la` doesn't list `.` and `..` directories as standard for all filesystems under Linux/unix in general? Could it be specific to the GS backend?

**Comment by Nikratio** [comment]
No, that's working as intended. Listing . and .. is optional.

**Comment by kobuki** [comment]
OK, I understand, and possibly I can only accept it. Though I'd like to know why you decided to omit these directories (`.` and `..`)?

**Comment by Nikratio** [comment]
Because it's simpler.. let me ask the other way around: what reason is there to include them?
