### ISSUE TITLE
StateError when running s3ql_verify

### ISSUE THREAD

**Issue by Nikratio** [s3ql/s3ql#81]
When running s3ql_verify with `--data`, I sooner or later always get a crash with a dugong.StateError:

```
2019-02-13 19:15:27.545 20664:MainThread root.excepthook: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/bin/s3ql_verify", line 11, in <module>
    load_entry_point('s3ql==2.33', 'console_scripts', 's3ql_verify')()
  File "/usr/lib/s3ql/s3ql/verify.py", line 100, in main
    full=options.data, offset=options.start_with)
  File "/usr/lib/s3ql/s3ql/verify.py", line 148, in retrieve_objects
    t.join_and_raise()
  File "/usr/lib/s3ql/s3ql/common.py", line 395, in join_and_raise
    raise EmbeddedException(exc_info, self.name)
s3ql.common.EmbeddedException: caused by an exception in thread Thread-1.
Original/inner traceback (most recent call last): 
Traceback (most recent call last):
  File "/usr/lib/s3ql/s3ql/common.py", line 373, in run
    self.run_protected()
  File "/usr/lib/s3ql/s3ql/common.py", line 425, in run_protected
    self.target(*self.args, **self.kwargs)
  File "/usr/lib/s3ql/s3ql/verify.py", line 206, in _retrieve_loop
    backend.perform_read(do_read, key)
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 324, in perform_read
    fh = self.open_read(key)
  File "/usr/lib/s3ql/s3ql/backends/comprenc.py", line 179, in open_read
    fh = self.backend.open_read(key)
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/lib/s3ql/s3ql/backends/gs.py", line 391, in open_read
    gs_meta = self._get_gs_meta(key)
  File "/usr/lib/s3ql/s3ql/backends/gs.py", line 374, in _get_gs_meta
    resp = self._do_request('GET', path)
  File "/usr/lib/s3ql/s3ql/backends/gs.py", line 706, in _do_request
    resp = self.conn.read_response()
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 765, in read_response
    return eval_coroutine(self.co_read_response(), self.timeout)
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 1496, in eval_coroutine
    if not next(crt).poll(timeout=timeout):
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 781, in co_read_response
    raise StateError('Previous response not read completely')
dugong.StateError: Previous response not read completely
```

Dugong debug logs say:

```
2019-02-13 19:15:26.589 20664:Thread-1 dugong._co_read_chunked: chunk complete
2019-02-13 19:15:26.589 20664:Thread-1 dugong._co_read_header: start
2019-02-13 19:15:26.589 20664:Thread-1 dugong._co_read_header: done (empty header)
2019-02-13 19:15:26.589 20664:Thread-1 dugong._co_read_chunked: done
2019-02-13 19:15:26.589 20664:Thread-1 dugong.co_readall: got 0 bytes
2019-02-13 19:15:26.589 20664:Thread-1 dugong.co_readall: done (273 bytes)
2019-02-13 19:15:26.590 20664:Thread-1 dugong.disconnect: start
2019-02-13 19:15:26.590 20664:Thread-1 dugong.eval_coroutine: polling
2019-02-13 19:15:26.590 20664:Thread-1 dugong.co_send_request: start
2019-02-13 19:15:26.590 20664:Thread-1 dugong.co_send_request: sending GET /storage/v1/b/nikratio-archive/o/s3ql_data_28955
2019-02-13 19:15:26.590 20664:Thread-1 dugong._co_send: trying to send 316 bytes
2019-02-13 19:15:26.590 20664:Thread-1 dugong._co_send: sent 316 bytes
2019-02-13 19:15:26.603 20664:Thread-1 dugong._co_send: done
2019-02-13 19:15:26.603 20664:Thread-1 dugong.eval_coroutine: polling
2019-02-13 19:15:26.603 20664:Thread-1 dugong.co_read_response: start
2019-02-13 19:15:26.603 20664:Thread-1 dugong.disconnect: start
2019-02-13 19:15:26.603 20664:Thread-1 s3ql.common.run: Thread Thread-1 terminated with exception
Traceback (most recent call last):
  File "/usr/lib/s3ql/s3ql/common.py", line 373, in run
    self.run_protected()
  File "/usr/lib/s3ql/s3ql/common.py", line 425, in run_protected
    self.target(*self.args, **self.kwargs)
  File "/usr/lib/s3ql/s3ql/verify.py", line 206, in _retrieve_loop
    backend.perform_read(do_read, key)
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 324, in perform_read
    fh = self.open_read(key)
  File "/usr/lib/s3ql/s3ql/backends/comprenc.py", line 179, in open_read
    fh = self.backend.open_read(key)
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/lib/s3ql/s3ql/backends/gs.py", line 391, in open_read
    gs_meta = self._get_gs_meta(key)
  File "/usr/lib/s3ql/s3ql/backends/gs.py", line 374, in _get_gs_meta
    resp = self._do_request('GET', path)
  File "/usr/lib/s3ql/s3ql/backends/gs.py", line 706, in _do_request
    resp = self.conn.read_response()
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 765, in read_response
    return eval_coroutine(self.co_read_response(), self.timeout)
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 1496, in eval_coroutine
    if not next(crt).poll(timeout=timeout):
  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 781, in co_read_response
    raise StateError('Previous response not read completely')
dugong.StateError: Previous response not read completely

```

**Comment by Nikratio** [comment]
This is S3QL 2.33 and dugong 3.7+dfsg-3

**Comment by Nikratio** [comment]
Reproduced with S3QL 3.0 (same dugong version)

**Comment by Nikratio** [comment]
Just tried to reproduce, but did not encounter any problems:

```
$ s3ql_verify --data gs://<....>
Reading all objects...
..processed 67110 objects (42.20%) / 9.81 GiB (54.88%) so far..Requesting new access token
..processed 159025 objects (100.00%) / 17.9 GiB (100.00%) so far..
Verified all 159025 storage objects.
```

This is with dugong 3.7.5.

**Comment by Nikratio** [comment]
Haven't encountered this in a long time, so declaring as fixed.
