### ISSUE TITLE
Timeout not supported exception in fsck

### ISSUE THREAD

**Issue by andrewchambers** [s3ql/s3ql#83]
I just upgraded to 3.0 after using an unreleased version and started getting:

```
2019-02-19_08:04:17.19769 ERROR: Uncaught top-level exception:
2019-02-19_08:04:17.19773 Traceback (most recent call last):
2019-02-19_08:04:17.19774   File "/nix/store/80m6lys5k2adczvkkrk14k8fp4w7k381-s3ql/bin/.fsck.s3ql-wrapped", line 12, in <module>
2019-02-19_08:04:17.19774     sys.exit(main())
2019-02-19_08:04:17.19774   File "/nix/store/80m6lys5k2adczvkkrk14k8fp4w7k381-s3ql/lib/python3.7/site-packages/s3ql/fsck.py", line 1135, in main
2019-02-19_08:04:17.19774     backend = get_backend(options)
2019-02-19_08:04:17.19774   File "/nix/store/80m6lys5k2adczvkkrk14k8fp4w7k381-s3ql/lib/python3.7/site-packages/s3ql/common.py", line 248, in get_backend
2019-02-19_08:04:17.19775     return get_backend_factory(options)()
2019-02-19_08:04:17.19775   File "/nix/store/80m6lys5k2adczvkkrk14k8fp4w7k381-s3ql/lib/python3.7/site-packages/s3ql/common.py", line 260, in get_backend_factory
2019-02-19_08:04:17.19775     backend = options.backend_class(options)
2019-02-19_08:04:17.19775   File "/nix/store/80m6lys5k2adczvkkrk14k8fp4w7k381-s3ql/lib/python3.7/site-packages/s3ql/backends/gs.py", line 183, in __init__
2019-02-19_08:04:17.19776     scopes=['https://www.googleapis.com/auth/devstorage.full_control'])
2019-02-19_08:04:17.19776   File "/nix/store/b65lq2bnws0ia4frr7gjs5kirj65ir7b-python3.7-google-auth-1.5.1/lib/python3.7/site-packages/google/auth/_default.py", line 294, in d
efault
2019-02-19_08:04:17.19777     credentials, project_id = checker()
2019-02-19_08:04:17.19777   File "/nix/store/b65lq2bnws0ia4frr7gjs5kirj65ir7b-python3.7-google-auth-1.5.1/lib/python3.7/site-packages/google/auth/_default.py", line 291, in <
lambda>
2019-02-19_08:04:17.19777     lambda: _get_gce_credentials(request))
2019-02-19_08:04:17.19778   File "/nix/store/b65lq2bnws0ia4frr7gjs5kirj65ir7b-python3.7-google-auth-1.5.1/lib/python3.7/site-packages/google/auth/_default.py", line 197, in _
get_gce_credentials
2019-02-19_08:04:17.19778     if _metadata.ping(request=request):
2019-02-19_08:04:17.19778   File "/nix/store/b65lq2bnws0ia4frr7gjs5kirj65ir7b-python3.7-google-auth-1.5.1/lib/python3.7/site-packages/google/auth/compute_engine/_metadata.py"
, line 74, in ping
2019-02-19_08:04:17.19778     timeout=timeout)
2019-02-19_08:04:17.19780   File "/nix/store/80m6lys5k2adczvkkrk14k8fp4w7k381-s3ql/lib/python3.7/site-packages/s3ql/backends/gs.py", line 111, in __call__
2019-02-19_08:04:17.19780     raise ValueError('*timeout* argument is not supported')
2019-02-19_08:04:17.19780 ValueError: *timeout* argument is not supported
```

Not sure why I didn't hit this before.

**Comment by AntonioIbarraOrtiz** [comment]
Hi, I corrected this following this guide https://cloud.google.com/docs/authentication/production
(Setting environment GOOGLE_APPLICATION_CREDENTIALS)

**Comment by derobert** [comment]
This also happens on mkfs.s3ql:

    $ mkfs.s3ql --cachedir /srv/S3QL-cache --plain gs://«URL-REDACTED»
    Enter backend login: (typed "adc")
    Enter backend password: whatever
    ERROR: Uncaught top-level exception:
    Traceback (most recent call last):
      File "/usr/bin/mkfs.s3ql", line 11, in <module>
        load_entry_point('s3ql==3.0', 'console_scripts', 'mkfs.s3ql')()
      File "/usr/lib/s3ql/s3ql/mkfs.py", line 91, in main
        plain_backend = get_backend(options, raw=True)
      File "/usr/lib/s3ql/s3ql/common.py", line 246, in get_backend
        return options.backend_class(options)
      File "/usr/lib/s3ql/s3ql/backends/gs.py", line 183, in __init__
        scopes=['https://www.googleapis.com/auth/devstorage.full_control'])
      File "/home/s3ql-user/.local/lib/python3.5/site-packages/google/auth/_default.py", line 305, in default
        credentials, project_id = checker()
      File "/home/s3ql-user/.local/lib/python3.5/site-packages/google/auth/_default.py", line 302, in <lambda>
        lambda: _get_gce_credentials(request))
      File "/home/s3ql-user/.local/lib/python3.5/site-packages/google/auth/_default.py", line 208, in _get_gce_credentials
        if _metadata.ping(request=request):
      File "/home/s3ql-user/.local/lib/python3.5/site-packages/google/auth/compute_engine/_metadata.py", line 78, in ping
        timeout=timeout)
      File "/usr/lib/s3ql/s3ql/backends/gs.py", line 111, in __call__
        raise ValueError('*timeout* argument is not supported')
    ValueError: *timeout* argument is not supported
