### ISSUE TITLE
ValueError: I/O operation on closed file in block_cache.py

### ISSUE THREAD

**Issue by scysys** [s3ql/s3ql#87]
Someone can say something about this?

`2019-02-25 00:47:02.019 3294:MainThread (name)s.main: FUSE main loop terminated. 
2019-02-25 01:03:50.454 3591:MainThread s3ql.mount.main: Autodetected 65497 file descriptors available for cache entries 
2019-02-25 01:03:52.960 3591:MainThread s3ql.mount.get_metadata: Ignoring locally cached metadata (outdated). 
2019-02-25 01:03:53.011 3591:MainThread s3ql.metadata.download_metadata: Downloading and decompressing metadata... 
2019-02-25 01:03:53.133 3591:MainThread s3ql.metadata.download_metadata: Reading metadata... 
2019-02-25 01:03:53.152 3591:MainThread s3ql.metadata.restore_metadata: ..objects.. 
2019-02-25 01:03:53.169 3591:MainThread s3ql.metadata.restore_metadata: ..blocks.. 
2019-02-25 01:03:53.194 3591:MainThread s3ql.metadata.restore_metadata: ..inodes.. 
2019-02-25 01:03:53.225 3591:MainThread s3ql.metadata.restore_metadata: ..inode_blocks.. 
2019-02-25 01:03:53.245 3591:MainThread s3ql.metadata.restore_metadata: ..symlink_targets.. 
2019-02-25 01:03:53.245 3591:MainThread s3ql.metadata.restore_metadata: ..names.. 
2019-02-25 01:03:53.275 3591:MainThread s3ql.metadata.restore_metadata: ..contents.. 
2019-02-25 01:03:53.308 3591:MainThread s3ql.metadata.restore_metadata: ..ext_attributes.. 
2019-02-25 01:03:53.690 3591:MainThread s3ql.mount.main: Setting cache size to 99355 MB 
2019-02-25 01:03:53.692 3591:MainThread s3ql.mount.main: Mounting swiftks://auth.cloud.ovh.net/DE1:xxxx-storage/ at /mnt/xxxx... 
2019-02-25 01:03:53.702 3599:MainThread s3ql.daemonize.detach_process_context: Daemonizing, new PID is 3600 
2019-02-25 17:15:04.578 3600:CommitThread root.excepthook: Uncaught top-level exception: Traceback (most recent call last): 
	File "/usr/lib/s3ql/s3ql/mount.py", line 64, in run_with_except_hook run_old(*args, **kw) 
	File "/usr/lib/s3ql/s3ql/mount.py", line 742, in run self.block_cache.upload(el) 
	File "/usr/lib/s3ql/s3ql/block_cache.py", line 515, in upload el.seek(0) 
	File "/usr/lib/s3ql/s3ql/block_cache.py", line 176, in seek self.fh.seek(off) 
	ValueError: I/O operation on closed file 
2019-02-25 17:15:17.242 3600:MainThread s3ql.mount.unmount: Unmounting file system...`

**Version**

S3QL 2.21

**Started with**

`mount.s3ql --allow-other --authfile ~/.s3ql/authinfo2 --threads 2 swiftks://auth.cloud.ovh.net/DE1:xxxx-storage /mnt/xxxx`

**Comment by szepeviktor** [comment]
```
2019-02-25 00:47:02.019 3294:MainThread (name)s.main: FUSE main loop terminated. 
2019-02-25 01:03:50.454 3591:MainThread s3ql.mount.main: Autodetected 65497 file descriptors available for cache entries 
2019-02-25 01:03:52.960 3591:MainThread s3ql.mount.get_metadata: Ignoring locally cached metadata (outdated). 
2019-02-25 01:03:53.011 3591:MainThread s3ql.metadata.download_metadata: Downloading and decompressing metadata... 
2019-02-25 01:03:53.133 3591:MainThread s3ql.metadata.download_metadata: Reading metadata... 
2019-02-25 01:03:53.152 3591:MainThread s3ql.metadata.restore_metadata: ..objects.. 
2019-02-25 01:03:53.169 3591:MainThread s3ql.metadata.restore_metadata: ..blocks.. 
2019-02-25 01:03:53.194 3591:MainThread s3ql.metadata.restore_metadata: ..inodes.. 
2019-02-25 01:03:53.225 3591:MainThread s3ql.metadata.restore_metadata: ..inode_blocks.. 
2019-02-25 01:03:53.245 3591:MainThread s3ql.metadata.restore_metadata: ..symlink_targets.. 
2019-02-25 01:03:53.245 3591:MainThread s3ql.metadata.restore_metadata: ..names.. 
2019-02-25 01:03:53.275 3591:MainThread s3ql.metadata.restore_metadata: ..contents.. 
2019-02-25 01:03:53.308 3591:MainThread s3ql.metadata.restore_metadata: ..ext_attributes.. 
2019-02-25 01:03:53.690 3591:MainThread s3ql.mount.main: Setting cache size to 99355 MB 
2019-02-25 01:03:53.692 3591:MainThread s3ql.mount.main: Mounting swiftks://auth.cloud.ovh.net/DE1:xxxx-storage/ at /mnt/xxxx... 
2019-02-25 01:03:53.702 3599:MainThread s3ql.daemonize.detach_process_context: Daemonizing, new PID is 3600 
2019-02-25 17:15:04.578 3600:CommitThread root.excepthook: Uncaught top-level exception: Traceback (most recent call last): 
	File "/usr/lib/s3ql/s3ql/mount.py", line 64, in run_with_except_hook run_old(*args, **kw) 
	File "/usr/lib/s3ql/s3ql/mount.py", line 742, in run self.block_cache.upload(el) 
	File "/usr/lib/s3ql/s3ql/block_cache.py", line 515, in upload el.seek(0) 
	File "/usr/lib/s3ql/s3ql/block_cache.py", line 176, in seek self.fh.seek(off) 
	ValueError: I/O operation on closed file 
2019-02-25 17:15:17.242 3600:MainThread s3ql.mount.unmount: Unmounting file system...
```

**Comment by Nikratio** [comment]
Thanks for the report! S3Ql 2.21 is rather old, so I'm afraid that unless you can reproduce this with S3QL 3.0, this is unlikely to get investigated. Would you be able to do that?

**Comment by scysys** [comment]
Sure, I will Upgrade it to V3 and see what happens.

**Comment by scysys** [comment]
Since version 3, I have no errors anymore. Thanks!
